apiVersion: cluster.x-k8s.io/v1beta2
kind: MachineHealthCheck
metadata:
  name: default
  namespace: default
spec:
  checks:
    nodeStartupTimeoutSeconds: 600
    unhealthyMachineConditions: []
    unhealthyNodeConditions: []
  clusterName: clusterclass-rollout-gnt8b0
  selector:
    matchLabels:
      cluster.x-k8s.io/control-plane: ""
      topology.cluster.x-k8s.io/owned: ""
