//go:build !ignore_autogenerated
// +build !ignore_autogenerated

/*
Copyright The Kubernetes Authors.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by conversion-gen. DO NOT EDIT.

package v1beta2

import (
	unsafe "unsafe"

	v1 "k8s.io/api/core/v1"
	metav1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	conversion "k8s.io/apimachinery/pkg/conversion"
	runtime "k8s.io/apimachinery/pkg/runtime"
	intstr "k8s.io/apimachinery/pkg/util/intstr"
	v1beta1 "sigs.k8s.io/cluster-api/api/v1beta1"
	errors "sigs.k8s.io/cluster-api/errors"
)

func init() {
	localSchemeBuilder.Register(RegisterConversions)
}

// RegisterConversions adds conversion functions to the given scheme.
// Public to allow building arbitrary schemes.
func RegisterConversions(s *runtime.Scheme) error {
	if err := s.AddGeneratedConversionFunc((*APIEndpoint)(nil), (*v1beta1.APIEndpoint)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_v1beta2_APIEndpoint_To_v1beta1_APIEndpoint(a.(*APIEndpoint), b.(*v1beta1.APIEndpoint), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*v1beta1.APIEndpoint)(nil), (*APIEndpoint)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_v1beta1_APIEndpoint_To_v1beta2_APIEndpoint(a.(*v1beta1.APIEndpoint), b.(*APIEndpoint), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*Cluster)(nil), (*v1beta1.Cluster)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_v1beta2_Cluster_To_v1beta1_Cluster(a.(*Cluster), b.(*v1beta1.Cluster), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*v1beta1.Cluster)(nil), (*Cluster)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_v1beta1_Cluster_To_v1beta2_Cluster(a.(*v1beta1.Cluster), b.(*Cluster), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*ClusterAvailabilityGate)(nil), (*v1beta1.ClusterAvailabilityGate)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_v1beta2_ClusterAvailabilityGate_To_v1beta1_ClusterAvailabilityGate(a.(*ClusterAvailabilityGate), b.(*v1beta1.ClusterAvailabilityGate), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*v1beta1.ClusterAvailabilityGate)(nil), (*ClusterAvailabilityGate)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_v1beta1_ClusterAvailabilityGate_To_v1beta2_ClusterAvailabilityGate(a.(*v1beta1.ClusterAvailabilityGate), b.(*ClusterAvailabilityGate), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*ClusterControlPlaneStatus)(nil), (*v1beta1.ClusterControlPlaneStatus)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_v1beta2_ClusterControlPlaneStatus_To_v1beta1_ClusterControlPlaneStatus(a.(*ClusterControlPlaneStatus), b.(*v1beta1.ClusterControlPlaneStatus), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*v1beta1.ClusterControlPlaneStatus)(nil), (*ClusterControlPlaneStatus)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_v1beta1_ClusterControlPlaneStatus_To_v1beta2_ClusterControlPlaneStatus(a.(*v1beta1.ClusterControlPlaneStatus), b.(*ClusterControlPlaneStatus), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*ClusterList)(nil), (*v1beta1.ClusterList)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_v1beta2_ClusterList_To_v1beta1_ClusterList(a.(*ClusterList), b.(*v1beta1.ClusterList), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*v1beta1.ClusterList)(nil), (*ClusterList)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_v1beta1_ClusterList_To_v1beta2_ClusterList(a.(*v1beta1.ClusterList), b.(*ClusterList), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*ClusterNetwork)(nil), (*v1beta1.ClusterNetwork)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_v1beta2_ClusterNetwork_To_v1beta1_ClusterNetwork(a.(*ClusterNetwork), b.(*v1beta1.ClusterNetwork), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*v1beta1.ClusterNetwork)(nil), (*ClusterNetwork)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_v1beta1_ClusterNetwork_To_v1beta2_ClusterNetwork(a.(*v1beta1.ClusterNetwork), b.(*ClusterNetwork), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*ClusterSpec)(nil), (*v1beta1.ClusterSpec)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_v1beta2_ClusterSpec_To_v1beta1_ClusterSpec(a.(*ClusterSpec), b.(*v1beta1.ClusterSpec), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*v1beta1.ClusterSpec)(nil), (*ClusterSpec)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_v1beta1_ClusterSpec_To_v1beta2_ClusterSpec(a.(*v1beta1.ClusterSpec), b.(*ClusterSpec), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*ClusterStatus)(nil), (*v1beta1.ClusterStatus)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_v1beta2_ClusterStatus_To_v1beta1_ClusterStatus(a.(*ClusterStatus), b.(*v1beta1.ClusterStatus), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*v1beta1.ClusterStatus)(nil), (*ClusterStatus)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_v1beta1_ClusterStatus_To_v1beta2_ClusterStatus(a.(*v1beta1.ClusterStatus), b.(*ClusterStatus), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*ClusterV1Beta2Status)(nil), (*v1beta1.ClusterV1Beta2Status)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_v1beta2_ClusterV1Beta2Status_To_v1beta1_ClusterV1Beta2Status(a.(*ClusterV1Beta2Status), b.(*v1beta1.ClusterV1Beta2Status), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*v1beta1.ClusterV1Beta2Status)(nil), (*ClusterV1Beta2Status)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_v1beta1_ClusterV1Beta2Status_To_v1beta2_ClusterV1Beta2Status(a.(*v1beta1.ClusterV1Beta2Status), b.(*ClusterV1Beta2Status), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*ClusterVariable)(nil), (*v1beta1.ClusterVariable)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_v1beta2_ClusterVariable_To_v1beta1_ClusterVariable(a.(*ClusterVariable), b.(*v1beta1.ClusterVariable), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*v1beta1.ClusterVariable)(nil), (*ClusterVariable)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_v1beta1_ClusterVariable_To_v1beta2_ClusterVariable(a.(*v1beta1.ClusterVariable), b.(*ClusterVariable), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*Condition)(nil), (*v1beta1.Condition)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_v1beta2_Condition_To_v1beta1_Condition(a.(*Condition), b.(*v1beta1.Condition), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*v1beta1.Condition)(nil), (*Condition)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_v1beta1_Condition_To_v1beta2_Condition(a.(*v1beta1.Condition), b.(*Condition), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*ControlPlaneTopology)(nil), (*v1beta1.ControlPlaneTopology)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_v1beta2_ControlPlaneTopology_To_v1beta1_ControlPlaneTopology(a.(*ControlPlaneTopology), b.(*v1beta1.ControlPlaneTopology), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*v1beta1.ControlPlaneTopology)(nil), (*ControlPlaneTopology)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_v1beta1_ControlPlaneTopology_To_v1beta2_ControlPlaneTopology(a.(*v1beta1.ControlPlaneTopology), b.(*ControlPlaneTopology), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*ControlPlaneVariables)(nil), (*v1beta1.ControlPlaneVariables)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_v1beta2_ControlPlaneVariables_To_v1beta1_ControlPlaneVariables(a.(*ControlPlaneVariables), b.(*v1beta1.ControlPlaneVariables), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*v1beta1.ControlPlaneVariables)(nil), (*ControlPlaneVariables)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_v1beta1_ControlPlaneVariables_To_v1beta2_ControlPlaneVariables(a.(*v1beta1.ControlPlaneVariables), b.(*ControlPlaneVariables), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*FailureDomainSpec)(nil), (*v1beta1.FailureDomainSpec)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_v1beta2_FailureDomainSpec_To_v1beta1_FailureDomainSpec(a.(*FailureDomainSpec), b.(*v1beta1.FailureDomainSpec), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*v1beta1.FailureDomainSpec)(nil), (*FailureDomainSpec)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_v1beta1_FailureDomainSpec_To_v1beta2_FailureDomainSpec(a.(*v1beta1.FailureDomainSpec), b.(*FailureDomainSpec), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*MachineDeploymentStrategy)(nil), (*v1beta1.MachineDeploymentStrategy)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_v1beta2_MachineDeploymentStrategy_To_v1beta1_MachineDeploymentStrategy(a.(*MachineDeploymentStrategy), b.(*v1beta1.MachineDeploymentStrategy), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*v1beta1.MachineDeploymentStrategy)(nil), (*MachineDeploymentStrategy)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_v1beta1_MachineDeploymentStrategy_To_v1beta2_MachineDeploymentStrategy(a.(*v1beta1.MachineDeploymentStrategy), b.(*MachineDeploymentStrategy), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*MachineDeploymentTopology)(nil), (*v1beta1.MachineDeploymentTopology)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_v1beta2_MachineDeploymentTopology_To_v1beta1_MachineDeploymentTopology(a.(*MachineDeploymentTopology), b.(*v1beta1.MachineDeploymentTopology), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*v1beta1.MachineDeploymentTopology)(nil), (*MachineDeploymentTopology)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_v1beta1_MachineDeploymentTopology_To_v1beta2_MachineDeploymentTopology(a.(*v1beta1.MachineDeploymentTopology), b.(*MachineDeploymentTopology), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*MachineDeploymentVariables)(nil), (*v1beta1.MachineDeploymentVariables)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_v1beta2_MachineDeploymentVariables_To_v1beta1_MachineDeploymentVariables(a.(*MachineDeploymentVariables), b.(*v1beta1.MachineDeploymentVariables), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*v1beta1.MachineDeploymentVariables)(nil), (*MachineDeploymentVariables)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_v1beta1_MachineDeploymentVariables_To_v1beta2_MachineDeploymentVariables(a.(*v1beta1.MachineDeploymentVariables), b.(*MachineDeploymentVariables), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*MachineHealthCheckClass)(nil), (*v1beta1.MachineHealthCheckClass)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_v1beta2_MachineHealthCheckClass_To_v1beta1_MachineHealthCheckClass(a.(*MachineHealthCheckClass), b.(*v1beta1.MachineHealthCheckClass), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*v1beta1.MachineHealthCheckClass)(nil), (*MachineHealthCheckClass)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_v1beta1_MachineHealthCheckClass_To_v1beta2_MachineHealthCheckClass(a.(*v1beta1.MachineHealthCheckClass), b.(*MachineHealthCheckClass), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*MachineHealthCheckTopology)(nil), (*v1beta1.MachineHealthCheckTopology)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_v1beta2_MachineHealthCheckTopology_To_v1beta1_MachineHealthCheckTopology(a.(*MachineHealthCheckTopology), b.(*v1beta1.MachineHealthCheckTopology), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*v1beta1.MachineHealthCheckTopology)(nil), (*MachineHealthCheckTopology)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_v1beta1_MachineHealthCheckTopology_To_v1beta2_MachineHealthCheckTopology(a.(*v1beta1.MachineHealthCheckTopology), b.(*MachineHealthCheckTopology), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*MachinePoolTopology)(nil), (*v1beta1.MachinePoolTopology)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_v1beta2_MachinePoolTopology_To_v1beta1_MachinePoolTopology(a.(*MachinePoolTopology), b.(*v1beta1.MachinePoolTopology), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*v1beta1.MachinePoolTopology)(nil), (*MachinePoolTopology)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_v1beta1_MachinePoolTopology_To_v1beta2_MachinePoolTopology(a.(*v1beta1.MachinePoolTopology), b.(*MachinePoolTopology), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*MachinePoolVariables)(nil), (*v1beta1.MachinePoolVariables)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_v1beta2_MachinePoolVariables_To_v1beta1_MachinePoolVariables(a.(*MachinePoolVariables), b.(*v1beta1.MachinePoolVariables), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*v1beta1.MachinePoolVariables)(nil), (*MachinePoolVariables)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_v1beta1_MachinePoolVariables_To_v1beta2_MachinePoolVariables(a.(*v1beta1.MachinePoolVariables), b.(*MachinePoolVariables), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*MachineReadinessGate)(nil), (*v1beta1.MachineReadinessGate)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_v1beta2_MachineReadinessGate_To_v1beta1_MachineReadinessGate(a.(*MachineReadinessGate), b.(*v1beta1.MachineReadinessGate), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*v1beta1.MachineReadinessGate)(nil), (*MachineReadinessGate)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_v1beta1_MachineReadinessGate_To_v1beta2_MachineReadinessGate(a.(*v1beta1.MachineReadinessGate), b.(*MachineReadinessGate), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*MachineRollingUpdateDeployment)(nil), (*v1beta1.MachineRollingUpdateDeployment)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_v1beta2_MachineRollingUpdateDeployment_To_v1beta1_MachineRollingUpdateDeployment(a.(*MachineRollingUpdateDeployment), b.(*v1beta1.MachineRollingUpdateDeployment), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*v1beta1.MachineRollingUpdateDeployment)(nil), (*MachineRollingUpdateDeployment)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_v1beta1_MachineRollingUpdateDeployment_To_v1beta2_MachineRollingUpdateDeployment(a.(*v1beta1.MachineRollingUpdateDeployment), b.(*MachineRollingUpdateDeployment), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*NetworkRanges)(nil), (*v1beta1.NetworkRanges)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_v1beta2_NetworkRanges_To_v1beta1_NetworkRanges(a.(*NetworkRanges), b.(*v1beta1.NetworkRanges), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*v1beta1.NetworkRanges)(nil), (*NetworkRanges)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_v1beta1_NetworkRanges_To_v1beta2_NetworkRanges(a.(*v1beta1.NetworkRanges), b.(*NetworkRanges), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*ObjectMeta)(nil), (*v1beta1.ObjectMeta)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_v1beta2_ObjectMeta_To_v1beta1_ObjectMeta(a.(*ObjectMeta), b.(*v1beta1.ObjectMeta), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*v1beta1.ObjectMeta)(nil), (*ObjectMeta)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_v1beta1_ObjectMeta_To_v1beta2_ObjectMeta(a.(*v1beta1.ObjectMeta), b.(*ObjectMeta), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*RemediationStrategy)(nil), (*v1beta1.RemediationStrategy)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_v1beta2_RemediationStrategy_To_v1beta1_RemediationStrategy(a.(*RemediationStrategy), b.(*v1beta1.RemediationStrategy), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*v1beta1.RemediationStrategy)(nil), (*RemediationStrategy)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_v1beta1_RemediationStrategy_To_v1beta2_RemediationStrategy(a.(*v1beta1.RemediationStrategy), b.(*RemediationStrategy), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*Topology)(nil), (*v1beta1.Topology)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_v1beta2_Topology_To_v1beta1_Topology(a.(*Topology), b.(*v1beta1.Topology), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*v1beta1.Topology)(nil), (*Topology)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_v1beta1_Topology_To_v1beta2_Topology(a.(*v1beta1.Topology), b.(*Topology), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*UnhealthyCondition)(nil), (*v1beta1.UnhealthyCondition)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_v1beta2_UnhealthyCondition_To_v1beta1_UnhealthyCondition(a.(*UnhealthyCondition), b.(*v1beta1.UnhealthyCondition), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*v1beta1.UnhealthyCondition)(nil), (*UnhealthyCondition)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_v1beta1_UnhealthyCondition_To_v1beta2_UnhealthyCondition(a.(*v1beta1.UnhealthyCondition), b.(*UnhealthyCondition), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*WorkersStatus)(nil), (*v1beta1.WorkersStatus)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_v1beta2_WorkersStatus_To_v1beta1_WorkersStatus(a.(*WorkersStatus), b.(*v1beta1.WorkersStatus), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*v1beta1.WorkersStatus)(nil), (*WorkersStatus)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_v1beta1_WorkersStatus_To_v1beta2_WorkersStatus(a.(*v1beta1.WorkersStatus), b.(*WorkersStatus), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*WorkersTopology)(nil), (*v1beta1.WorkersTopology)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_v1beta2_WorkersTopology_To_v1beta1_WorkersTopology(a.(*WorkersTopology), b.(*v1beta1.WorkersTopology), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*v1beta1.WorkersTopology)(nil), (*WorkersTopology)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_v1beta1_WorkersTopology_To_v1beta2_WorkersTopology(a.(*v1beta1.WorkersTopology), b.(*WorkersTopology), scope)
	}); err != nil {
		return err
	}
	return nil
}

func autoConvert_v1beta2_APIEndpoint_To_v1beta1_APIEndpoint(in *APIEndpoint, out *v1beta1.APIEndpoint, s conversion.Scope) error {
	out.Host = in.Host
	out.Port = in.Port
	return nil
}

// Convert_v1beta2_APIEndpoint_To_v1beta1_APIEndpoint is an autogenerated conversion function.
func Convert_v1beta2_APIEndpoint_To_v1beta1_APIEndpoint(in *APIEndpoint, out *v1beta1.APIEndpoint, s conversion.Scope) error {
	return autoConvert_v1beta2_APIEndpoint_To_v1beta1_APIEndpoint(in, out, s)
}

func autoConvert_v1beta1_APIEndpoint_To_v1beta2_APIEndpoint(in *v1beta1.APIEndpoint, out *APIEndpoint, s conversion.Scope) error {
	out.Host = in.Host
	out.Port = in.Port
	return nil
}

// Convert_v1beta1_APIEndpoint_To_v1beta2_APIEndpoint is an autogenerated conversion function.
func Convert_v1beta1_APIEndpoint_To_v1beta2_APIEndpoint(in *v1beta1.APIEndpoint, out *APIEndpoint, s conversion.Scope) error {
	return autoConvert_v1beta1_APIEndpoint_To_v1beta2_APIEndpoint(in, out, s)
}

func autoConvert_v1beta2_Cluster_To_v1beta1_Cluster(in *Cluster, out *v1beta1.Cluster, s conversion.Scope) error {
	out.ObjectMeta = in.ObjectMeta
	if err := Convert_v1beta2_ClusterSpec_To_v1beta1_ClusterSpec(&in.Spec, &out.Spec, s); err != nil {
		return err
	}
	if err := Convert_v1beta2_ClusterStatus_To_v1beta1_ClusterStatus(&in.Status, &out.Status, s); err != nil {
		return err
	}
	return nil
}

// Convert_v1beta2_Cluster_To_v1beta1_Cluster is an autogenerated conversion function.
func Convert_v1beta2_Cluster_To_v1beta1_Cluster(in *Cluster, out *v1beta1.Cluster, s conversion.Scope) error {
	return autoConvert_v1beta2_Cluster_To_v1beta1_Cluster(in, out, s)
}

func autoConvert_v1beta1_Cluster_To_v1beta2_Cluster(in *v1beta1.Cluster, out *Cluster, s conversion.Scope) error {
	out.ObjectMeta = in.ObjectMeta
	if err := Convert_v1beta1_ClusterSpec_To_v1beta2_ClusterSpec(&in.Spec, &out.Spec, s); err != nil {
		return err
	}
	if err := Convert_v1beta1_ClusterStatus_To_v1beta2_ClusterStatus(&in.Status, &out.Status, s); err != nil {
		return err
	}
	return nil
}

// Convert_v1beta1_Cluster_To_v1beta2_Cluster is an autogenerated conversion function.
func Convert_v1beta1_Cluster_To_v1beta2_Cluster(in *v1beta1.Cluster, out *Cluster, s conversion.Scope) error {
	return autoConvert_v1beta1_Cluster_To_v1beta2_Cluster(in, out, s)
}

func autoConvert_v1beta2_ClusterAvailabilityGate_To_v1beta1_ClusterAvailabilityGate(in *ClusterAvailabilityGate, out *v1beta1.ClusterAvailabilityGate, s conversion.Scope) error {
	out.ConditionType = in.ConditionType
	out.Polarity = v1beta1.ConditionPolarity(in.Polarity)
	return nil
}

// Convert_v1beta2_ClusterAvailabilityGate_To_v1beta1_ClusterAvailabilityGate is an autogenerated conversion function.
func Convert_v1beta2_ClusterAvailabilityGate_To_v1beta1_ClusterAvailabilityGate(in *ClusterAvailabilityGate, out *v1beta1.ClusterAvailabilityGate, s conversion.Scope) error {
	return autoConvert_v1beta2_ClusterAvailabilityGate_To_v1beta1_ClusterAvailabilityGate(in, out, s)
}

func autoConvert_v1beta1_ClusterAvailabilityGate_To_v1beta2_ClusterAvailabilityGate(in *v1beta1.ClusterAvailabilityGate, out *ClusterAvailabilityGate, s conversion.Scope) error {
	out.ConditionType = in.ConditionType
	out.Polarity = ConditionPolarity(in.Polarity)
	return nil
}

// Convert_v1beta1_ClusterAvailabilityGate_To_v1beta2_ClusterAvailabilityGate is an autogenerated conversion function.
func Convert_v1beta1_ClusterAvailabilityGate_To_v1beta2_ClusterAvailabilityGate(in *v1beta1.ClusterAvailabilityGate, out *ClusterAvailabilityGate, s conversion.Scope) error {
	return autoConvert_v1beta1_ClusterAvailabilityGate_To_v1beta2_ClusterAvailabilityGate(in, out, s)
}

func autoConvert_v1beta2_ClusterControlPlaneStatus_To_v1beta1_ClusterControlPlaneStatus(in *ClusterControlPlaneStatus, out *v1beta1.ClusterControlPlaneStatus, s conversion.Scope) error {
	out.DesiredReplicas = (*int32)(unsafe.Pointer(in.DesiredReplicas))
	out.Replicas = (*int32)(unsafe.Pointer(in.Replicas))
	out.UpToDateReplicas = (*int32)(unsafe.Pointer(in.UpToDateReplicas))
	out.ReadyReplicas = (*int32)(unsafe.Pointer(in.ReadyReplicas))
	out.AvailableReplicas = (*int32)(unsafe.Pointer(in.AvailableReplicas))
	return nil
}

// Convert_v1beta2_ClusterControlPlaneStatus_To_v1beta1_ClusterControlPlaneStatus is an autogenerated conversion function.
func Convert_v1beta2_ClusterControlPlaneStatus_To_v1beta1_ClusterControlPlaneStatus(in *ClusterControlPlaneStatus, out *v1beta1.ClusterControlPlaneStatus, s conversion.Scope) error {
	return autoConvert_v1beta2_ClusterControlPlaneStatus_To_v1beta1_ClusterControlPlaneStatus(in, out, s)
}

func autoConvert_v1beta1_ClusterControlPlaneStatus_To_v1beta2_ClusterControlPlaneStatus(in *v1beta1.ClusterControlPlaneStatus, out *ClusterControlPlaneStatus, s conversion.Scope) error {
	out.DesiredReplicas = (*int32)(unsafe.Pointer(in.DesiredReplicas))
	out.Replicas = (*int32)(unsafe.Pointer(in.Replicas))
	out.UpToDateReplicas = (*int32)(unsafe.Pointer(in.UpToDateReplicas))
	out.ReadyReplicas = (*int32)(unsafe.Pointer(in.ReadyReplicas))
	out.AvailableReplicas = (*int32)(unsafe.Pointer(in.AvailableReplicas))
	return nil
}

// Convert_v1beta1_ClusterControlPlaneStatus_To_v1beta2_ClusterControlPlaneStatus is an autogenerated conversion function.
func Convert_v1beta1_ClusterControlPlaneStatus_To_v1beta2_ClusterControlPlaneStatus(in *v1beta1.ClusterControlPlaneStatus, out *ClusterControlPlaneStatus, s conversion.Scope) error {
	return autoConvert_v1beta1_ClusterControlPlaneStatus_To_v1beta2_ClusterControlPlaneStatus(in, out, s)
}

func autoConvert_v1beta2_ClusterList_To_v1beta1_ClusterList(in *ClusterList, out *v1beta1.ClusterList, s conversion.Scope) error {
	out.ListMeta = in.ListMeta
	out.Items = *(*[]v1beta1.Cluster)(unsafe.Pointer(&in.Items))
	return nil
}

// Convert_v1beta2_ClusterList_To_v1beta1_ClusterList is an autogenerated conversion function.
func Convert_v1beta2_ClusterList_To_v1beta1_ClusterList(in *ClusterList, out *v1beta1.ClusterList, s conversion.Scope) error {
	return autoConvert_v1beta2_ClusterList_To_v1beta1_ClusterList(in, out, s)
}

func autoConvert_v1beta1_ClusterList_To_v1beta2_ClusterList(in *v1beta1.ClusterList, out *ClusterList, s conversion.Scope) error {
	out.ListMeta = in.ListMeta
	out.Items = *(*[]Cluster)(unsafe.Pointer(&in.Items))
	return nil
}

// Convert_v1beta1_ClusterList_To_v1beta2_ClusterList is an autogenerated conversion function.
func Convert_v1beta1_ClusterList_To_v1beta2_ClusterList(in *v1beta1.ClusterList, out *ClusterList, s conversion.Scope) error {
	return autoConvert_v1beta1_ClusterList_To_v1beta2_ClusterList(in, out, s)
}

func autoConvert_v1beta2_ClusterNetwork_To_v1beta1_ClusterNetwork(in *ClusterNetwork, out *v1beta1.ClusterNetwork, s conversion.Scope) error {
	out.APIServerPort = (*int32)(unsafe.Pointer(in.APIServerPort))
	out.Services = (*v1beta1.NetworkRanges)(unsafe.Pointer(in.Services))
	out.Pods = (*v1beta1.NetworkRanges)(unsafe.Pointer(in.Pods))
	out.ServiceDomain = in.ServiceDomain
	return nil
}

// Convert_v1beta2_ClusterNetwork_To_v1beta1_ClusterNetwork is an autogenerated conversion function.
func Convert_v1beta2_ClusterNetwork_To_v1beta1_ClusterNetwork(in *ClusterNetwork, out *v1beta1.ClusterNetwork, s conversion.Scope) error {
	return autoConvert_v1beta2_ClusterNetwork_To_v1beta1_ClusterNetwork(in, out, s)
}

func autoConvert_v1beta1_ClusterNetwork_To_v1beta2_ClusterNetwork(in *v1beta1.ClusterNetwork, out *ClusterNetwork, s conversion.Scope) error {
	out.APIServerPort = (*int32)(unsafe.Pointer(in.APIServerPort))
	out.Services = (*NetworkRanges)(unsafe.Pointer(in.Services))
	out.Pods = (*NetworkRanges)(unsafe.Pointer(in.Pods))
	out.ServiceDomain = in.ServiceDomain
	return nil
}

// Convert_v1beta1_ClusterNetwork_To_v1beta2_ClusterNetwork is an autogenerated conversion function.
func Convert_v1beta1_ClusterNetwork_To_v1beta2_ClusterNetwork(in *v1beta1.ClusterNetwork, out *ClusterNetwork, s conversion.Scope) error {
	return autoConvert_v1beta1_ClusterNetwork_To_v1beta2_ClusterNetwork(in, out, s)
}

func autoConvert_v1beta2_ClusterSpec_To_v1beta1_ClusterSpec(in *ClusterSpec, out *v1beta1.ClusterSpec, s conversion.Scope) error {
	out.Paused = in.Paused
	out.ClusterNetwork = (*v1beta1.ClusterNetwork)(unsafe.Pointer(in.ClusterNetwork))
	if err := Convert_v1beta2_APIEndpoint_To_v1beta1_APIEndpoint(&in.ControlPlaneEndpoint, &out.ControlPlaneEndpoint, s); err != nil {
		return err
	}
	out.ControlPlaneRef = (*v1.ObjectReference)(unsafe.Pointer(in.ControlPlaneRef))
	out.InfrastructureRef = (*v1.ObjectReference)(unsafe.Pointer(in.InfrastructureRef))
	out.Topology = (*v1beta1.Topology)(unsafe.Pointer(in.Topology))
	out.AvailabilityGates = *(*[]v1beta1.ClusterAvailabilityGate)(unsafe.Pointer(&in.AvailabilityGates))
	return nil
}

// Convert_v1beta2_ClusterSpec_To_v1beta1_ClusterSpec is an autogenerated conversion function.
func Convert_v1beta2_ClusterSpec_To_v1beta1_ClusterSpec(in *ClusterSpec, out *v1beta1.ClusterSpec, s conversion.Scope) error {
	return autoConvert_v1beta2_ClusterSpec_To_v1beta1_ClusterSpec(in, out, s)
}

func autoConvert_v1beta1_ClusterSpec_To_v1beta2_ClusterSpec(in *v1beta1.ClusterSpec, out *ClusterSpec, s conversion.Scope) error {
	out.Paused = in.Paused
	out.ClusterNetwork = (*ClusterNetwork)(unsafe.Pointer(in.ClusterNetwork))
	if err := Convert_v1beta1_APIEndpoint_To_v1beta2_APIEndpoint(&in.ControlPlaneEndpoint, &out.ControlPlaneEndpoint, s); err != nil {
		return err
	}
	out.ControlPlaneRef = (*v1.ObjectReference)(unsafe.Pointer(in.ControlPlaneRef))
	out.InfrastructureRef = (*v1.ObjectReference)(unsafe.Pointer(in.InfrastructureRef))
	out.Topology = (*Topology)(unsafe.Pointer(in.Topology))
	out.AvailabilityGates = *(*[]ClusterAvailabilityGate)(unsafe.Pointer(&in.AvailabilityGates))
	return nil
}

// Convert_v1beta1_ClusterSpec_To_v1beta2_ClusterSpec is an autogenerated conversion function.
func Convert_v1beta1_ClusterSpec_To_v1beta2_ClusterSpec(in *v1beta1.ClusterSpec, out *ClusterSpec, s conversion.Scope) error {
	return autoConvert_v1beta1_ClusterSpec_To_v1beta2_ClusterSpec(in, out, s)
}

func autoConvert_v1beta2_ClusterStatus_To_v1beta1_ClusterStatus(in *ClusterStatus, out *v1beta1.ClusterStatus, s conversion.Scope) error {
	out.FailureDomains = *(*v1beta1.FailureDomains)(unsafe.Pointer(&in.FailureDomains))
	out.FailureReason = (*errors.ClusterStatusError)(unsafe.Pointer(in.FailureReason))
	out.FailureMessage = (*string)(unsafe.Pointer(in.FailureMessage))
	out.Phase = in.Phase
	out.InfrastructureReady = in.InfrastructureReady
	out.ControlPlaneReady = in.ControlPlaneReady
	out.Conditions = *(*v1beta1.Conditions)(unsafe.Pointer(&in.Conditions))
	out.ObservedGeneration = in.ObservedGeneration
	out.V1Beta2 = (*v1beta1.ClusterV1Beta2Status)(unsafe.Pointer(in.V1Beta2))
	return nil
}

// Convert_v1beta2_ClusterStatus_To_v1beta1_ClusterStatus is an autogenerated conversion function.
func Convert_v1beta2_ClusterStatus_To_v1beta1_ClusterStatus(in *ClusterStatus, out *v1beta1.ClusterStatus, s conversion.Scope) error {
	return autoConvert_v1beta2_ClusterStatus_To_v1beta1_ClusterStatus(in, out, s)
}

func autoConvert_v1beta1_ClusterStatus_To_v1beta2_ClusterStatus(in *v1beta1.ClusterStatus, out *ClusterStatus, s conversion.Scope) error {
	out.FailureDomains = *(*FailureDomains)(unsafe.Pointer(&in.FailureDomains))
	out.FailureReason = (*errors.ClusterStatusError)(unsafe.Pointer(in.FailureReason))
	out.FailureMessage = (*string)(unsafe.Pointer(in.FailureMessage))
	out.Phase = in.Phase
	out.InfrastructureReady = in.InfrastructureReady
	out.ControlPlaneReady = in.ControlPlaneReady
	out.Conditions = *(*Conditions)(unsafe.Pointer(&in.Conditions))
	out.ObservedGeneration = in.ObservedGeneration
	out.V1Beta2 = (*ClusterV1Beta2Status)(unsafe.Pointer(in.V1Beta2))
	return nil
}

// Convert_v1beta1_ClusterStatus_To_v1beta2_ClusterStatus is an autogenerated conversion function.
func Convert_v1beta1_ClusterStatus_To_v1beta2_ClusterStatus(in *v1beta1.ClusterStatus, out *ClusterStatus, s conversion.Scope) error {
	return autoConvert_v1beta1_ClusterStatus_To_v1beta2_ClusterStatus(in, out, s)
}

func autoConvert_v1beta2_ClusterV1Beta2Status_To_v1beta1_ClusterV1Beta2Status(in *ClusterV1Beta2Status, out *v1beta1.ClusterV1Beta2Status, s conversion.Scope) error {
	out.Conditions = *(*[]metav1.Condition)(unsafe.Pointer(&in.Conditions))
	out.ControlPlane = (*v1beta1.ClusterControlPlaneStatus)(unsafe.Pointer(in.ControlPlane))
	out.Workers = (*v1beta1.WorkersStatus)(unsafe.Pointer(in.Workers))
	return nil
}

// Convert_v1beta2_ClusterV1Beta2Status_To_v1beta1_ClusterV1Beta2Status is an autogenerated conversion function.
func Convert_v1beta2_ClusterV1Beta2Status_To_v1beta1_ClusterV1Beta2Status(in *ClusterV1Beta2Status, out *v1beta1.ClusterV1Beta2Status, s conversion.Scope) error {
	return autoConvert_v1beta2_ClusterV1Beta2Status_To_v1beta1_ClusterV1Beta2Status(in, out, s)
}

func autoConvert_v1beta1_ClusterV1Beta2Status_To_v1beta2_ClusterV1Beta2Status(in *v1beta1.ClusterV1Beta2Status, out *ClusterV1Beta2Status, s conversion.Scope) error {
	out.Conditions = *(*[]metav1.Condition)(unsafe.Pointer(&in.Conditions))
	out.ControlPlane = (*ClusterControlPlaneStatus)(unsafe.Pointer(in.ControlPlane))
	out.Workers = (*WorkersStatus)(unsafe.Pointer(in.Workers))
	return nil
}

// Convert_v1beta1_ClusterV1Beta2Status_To_v1beta2_ClusterV1Beta2Status is an autogenerated conversion function.
func Convert_v1beta1_ClusterV1Beta2Status_To_v1beta2_ClusterV1Beta2Status(in *v1beta1.ClusterV1Beta2Status, out *ClusterV1Beta2Status, s conversion.Scope) error {
	return autoConvert_v1beta1_ClusterV1Beta2Status_To_v1beta2_ClusterV1Beta2Status(in, out, s)
}

func autoConvert_v1beta2_ClusterVariable_To_v1beta1_ClusterVariable(in *ClusterVariable, out *v1beta1.ClusterVariable, s conversion.Scope) error {
	out.Name = in.Name
	out.DefinitionFrom = in.DefinitionFrom
	out.Value = in.Value
	return nil
}

// Convert_v1beta2_ClusterVariable_To_v1beta1_ClusterVariable is an autogenerated conversion function.
func Convert_v1beta2_ClusterVariable_To_v1beta1_ClusterVariable(in *ClusterVariable, out *v1beta1.ClusterVariable, s conversion.Scope) error {
	return autoConvert_v1beta2_ClusterVariable_To_v1beta1_ClusterVariable(in, out, s)
}

func autoConvert_v1beta1_ClusterVariable_To_v1beta2_ClusterVariable(in *v1beta1.ClusterVariable, out *ClusterVariable, s conversion.Scope) error {
	out.Name = in.Name
	out.DefinitionFrom = in.DefinitionFrom
	out.Value = in.Value
	return nil
}

// Convert_v1beta1_ClusterVariable_To_v1beta2_ClusterVariable is an autogenerated conversion function.
func Convert_v1beta1_ClusterVariable_To_v1beta2_ClusterVariable(in *v1beta1.ClusterVariable, out *ClusterVariable, s conversion.Scope) error {
	return autoConvert_v1beta1_ClusterVariable_To_v1beta2_ClusterVariable(in, out, s)
}

func autoConvert_v1beta2_Condition_To_v1beta1_Condition(in *Condition, out *v1beta1.Condition, s conversion.Scope) error {
	out.Type = v1beta1.ConditionType(in.Type)
	out.Status = v1.ConditionStatus(in.Status)
	out.Severity = v1beta1.ConditionSeverity(in.Severity)
	out.LastTransitionTime = in.LastTransitionTime
	out.Reason = in.Reason
	out.Message = in.Message
	return nil
}

// Convert_v1beta2_Condition_To_v1beta1_Condition is an autogenerated conversion function.
func Convert_v1beta2_Condition_To_v1beta1_Condition(in *Condition, out *v1beta1.Condition, s conversion.Scope) error {
	return autoConvert_v1beta2_Condition_To_v1beta1_Condition(in, out, s)
}

func autoConvert_v1beta1_Condition_To_v1beta2_Condition(in *v1beta1.Condition, out *Condition, s conversion.Scope) error {
	out.Type = ConditionType(in.Type)
	out.Status = v1.ConditionStatus(in.Status)
	out.Severity = ConditionSeverity(in.Severity)
	out.LastTransitionTime = in.LastTransitionTime
	out.Reason = in.Reason
	out.Message = in.Message
	return nil
}

// Convert_v1beta1_Condition_To_v1beta2_Condition is an autogenerated conversion function.
func Convert_v1beta1_Condition_To_v1beta2_Condition(in *v1beta1.Condition, out *Condition, s conversion.Scope) error {
	return autoConvert_v1beta1_Condition_To_v1beta2_Condition(in, out, s)
}

func autoConvert_v1beta2_ControlPlaneTopology_To_v1beta1_ControlPlaneTopology(in *ControlPlaneTopology, out *v1beta1.ControlPlaneTopology, s conversion.Scope) error {
	if err := Convert_v1beta2_ObjectMeta_To_v1beta1_ObjectMeta(&in.Metadata, &out.Metadata, s); err != nil {
		return err
	}
	out.Replicas = (*int32)(unsafe.Pointer(in.Replicas))
	out.MachineHealthCheck = (*v1beta1.MachineHealthCheckTopology)(unsafe.Pointer(in.MachineHealthCheck))
	out.NodeDrainTimeout = (*metav1.Duration)(unsafe.Pointer(in.NodeDrainTimeout))
	out.NodeVolumeDetachTimeout = (*metav1.Duration)(unsafe.Pointer(in.NodeVolumeDetachTimeout))
	out.NodeDeletionTimeout = (*metav1.Duration)(unsafe.Pointer(in.NodeDeletionTimeout))
	out.ReadinessGates = *(*[]v1beta1.MachineReadinessGate)(unsafe.Pointer(&in.ReadinessGates))
	out.Variables = (*v1beta1.ControlPlaneVariables)(unsafe.Pointer(in.Variables))
	return nil
}

// Convert_v1beta2_ControlPlaneTopology_To_v1beta1_ControlPlaneTopology is an autogenerated conversion function.
func Convert_v1beta2_ControlPlaneTopology_To_v1beta1_ControlPlaneTopology(in *ControlPlaneTopology, out *v1beta1.ControlPlaneTopology, s conversion.Scope) error {
	return autoConvert_v1beta2_ControlPlaneTopology_To_v1beta1_ControlPlaneTopology(in, out, s)
}

func autoConvert_v1beta1_ControlPlaneTopology_To_v1beta2_ControlPlaneTopology(in *v1beta1.ControlPlaneTopology, out *ControlPlaneTopology, s conversion.Scope) error {
	if err := Convert_v1beta1_ObjectMeta_To_v1beta2_ObjectMeta(&in.Metadata, &out.Metadata, s); err != nil {
		return err
	}
	out.Replicas = (*int32)(unsafe.Pointer(in.Replicas))
	out.MachineHealthCheck = (*MachineHealthCheckTopology)(unsafe.Pointer(in.MachineHealthCheck))
	out.NodeDrainTimeout = (*metav1.Duration)(unsafe.Pointer(in.NodeDrainTimeout))
	out.NodeVolumeDetachTimeout = (*metav1.Duration)(unsafe.Pointer(in.NodeVolumeDetachTimeout))
	out.NodeDeletionTimeout = (*metav1.Duration)(unsafe.Pointer(in.NodeDeletionTimeout))
	out.ReadinessGates = *(*[]MachineReadinessGate)(unsafe.Pointer(&in.ReadinessGates))
	out.Variables = (*ControlPlaneVariables)(unsafe.Pointer(in.Variables))
	return nil
}

// Convert_v1beta1_ControlPlaneTopology_To_v1beta2_ControlPlaneTopology is an autogenerated conversion function.
func Convert_v1beta1_ControlPlaneTopology_To_v1beta2_ControlPlaneTopology(in *v1beta1.ControlPlaneTopology, out *ControlPlaneTopology, s conversion.Scope) error {
	return autoConvert_v1beta1_ControlPlaneTopology_To_v1beta2_ControlPlaneTopology(in, out, s)
}

func autoConvert_v1beta2_ControlPlaneVariables_To_v1beta1_ControlPlaneVariables(in *ControlPlaneVariables, out *v1beta1.ControlPlaneVariables, s conversion.Scope) error {
	out.Overrides = *(*[]v1beta1.ClusterVariable)(unsafe.Pointer(&in.Overrides))
	return nil
}

// Convert_v1beta2_ControlPlaneVariables_To_v1beta1_ControlPlaneVariables is an autogenerated conversion function.
func Convert_v1beta2_ControlPlaneVariables_To_v1beta1_ControlPlaneVariables(in *ControlPlaneVariables, out *v1beta1.ControlPlaneVariables, s conversion.Scope) error {
	return autoConvert_v1beta2_ControlPlaneVariables_To_v1beta1_ControlPlaneVariables(in, out, s)
}

func autoConvert_v1beta1_ControlPlaneVariables_To_v1beta2_ControlPlaneVariables(in *v1beta1.ControlPlaneVariables, out *ControlPlaneVariables, s conversion.Scope) error {
	out.Overrides = *(*[]ClusterVariable)(unsafe.Pointer(&in.Overrides))
	return nil
}

// Convert_v1beta1_ControlPlaneVariables_To_v1beta2_ControlPlaneVariables is an autogenerated conversion function.
func Convert_v1beta1_ControlPlaneVariables_To_v1beta2_ControlPlaneVariables(in *v1beta1.ControlPlaneVariables, out *ControlPlaneVariables, s conversion.Scope) error {
	return autoConvert_v1beta1_ControlPlaneVariables_To_v1beta2_ControlPlaneVariables(in, out, s)
}

func autoConvert_v1beta2_FailureDomainSpec_To_v1beta1_FailureDomainSpec(in *FailureDomainSpec, out *v1beta1.FailureDomainSpec, s conversion.Scope) error {
	out.ControlPlane = in.ControlPlane
	out.Attributes = *(*map[string]string)(unsafe.Pointer(&in.Attributes))
	return nil
}

// Convert_v1beta2_FailureDomainSpec_To_v1beta1_FailureDomainSpec is an autogenerated conversion function.
func Convert_v1beta2_FailureDomainSpec_To_v1beta1_FailureDomainSpec(in *FailureDomainSpec, out *v1beta1.FailureDomainSpec, s conversion.Scope) error {
	return autoConvert_v1beta2_FailureDomainSpec_To_v1beta1_FailureDomainSpec(in, out, s)
}

func autoConvert_v1beta1_FailureDomainSpec_To_v1beta2_FailureDomainSpec(in *v1beta1.FailureDomainSpec, out *FailureDomainSpec, s conversion.Scope) error {
	out.ControlPlane = in.ControlPlane
	out.Attributes = *(*map[string]string)(unsafe.Pointer(&in.Attributes))
	return nil
}

// Convert_v1beta1_FailureDomainSpec_To_v1beta2_FailureDomainSpec is an autogenerated conversion function.
func Convert_v1beta1_FailureDomainSpec_To_v1beta2_FailureDomainSpec(in *v1beta1.FailureDomainSpec, out *FailureDomainSpec, s conversion.Scope) error {
	return autoConvert_v1beta1_FailureDomainSpec_To_v1beta2_FailureDomainSpec(in, out, s)
}

func autoConvert_v1beta2_MachineDeploymentStrategy_To_v1beta1_MachineDeploymentStrategy(in *MachineDeploymentStrategy, out *v1beta1.MachineDeploymentStrategy, s conversion.Scope) error {
	out.Type = v1beta1.MachineDeploymentStrategyType(in.Type)
	out.RollingUpdate = (*v1beta1.MachineRollingUpdateDeployment)(unsafe.Pointer(in.RollingUpdate))
	out.Remediation = (*v1beta1.RemediationStrategy)(unsafe.Pointer(in.Remediation))
	return nil
}

// Convert_v1beta2_MachineDeploymentStrategy_To_v1beta1_MachineDeploymentStrategy is an autogenerated conversion function.
func Convert_v1beta2_MachineDeploymentStrategy_To_v1beta1_MachineDeploymentStrategy(in *MachineDeploymentStrategy, out *v1beta1.MachineDeploymentStrategy, s conversion.Scope) error {
	return autoConvert_v1beta2_MachineDeploymentStrategy_To_v1beta1_MachineDeploymentStrategy(in, out, s)
}

func autoConvert_v1beta1_MachineDeploymentStrategy_To_v1beta2_MachineDeploymentStrategy(in *v1beta1.MachineDeploymentStrategy, out *MachineDeploymentStrategy, s conversion.Scope) error {
	out.Type = MachineDeploymentStrategyType(in.Type)
	out.RollingUpdate = (*MachineRollingUpdateDeployment)(unsafe.Pointer(in.RollingUpdate))
	out.Remediation = (*RemediationStrategy)(unsafe.Pointer(in.Remediation))
	return nil
}

// Convert_v1beta1_MachineDeploymentStrategy_To_v1beta2_MachineDeploymentStrategy is an autogenerated conversion function.
func Convert_v1beta1_MachineDeploymentStrategy_To_v1beta2_MachineDeploymentStrategy(in *v1beta1.MachineDeploymentStrategy, out *MachineDeploymentStrategy, s conversion.Scope) error {
	return autoConvert_v1beta1_MachineDeploymentStrategy_To_v1beta2_MachineDeploymentStrategy(in, out, s)
}

func autoConvert_v1beta2_MachineDeploymentTopology_To_v1beta1_MachineDeploymentTopology(in *MachineDeploymentTopology, out *v1beta1.MachineDeploymentTopology, s conversion.Scope) error {
	if err := Convert_v1beta2_ObjectMeta_To_v1beta1_ObjectMeta(&in.Metadata, &out.Metadata, s); err != nil {
		return err
	}
	out.Class = in.Class
	out.Name = in.Name
	out.FailureDomain = (*string)(unsafe.Pointer(in.FailureDomain))
	out.Replicas = (*int32)(unsafe.Pointer(in.Replicas))
	out.MachineHealthCheck = (*v1beta1.MachineHealthCheckTopology)(unsafe.Pointer(in.MachineHealthCheck))
	out.NodeDrainTimeout = (*metav1.Duration)(unsafe.Pointer(in.NodeDrainTimeout))
	out.NodeVolumeDetachTimeout = (*metav1.Duration)(unsafe.Pointer(in.NodeVolumeDetachTimeout))
	out.NodeDeletionTimeout = (*metav1.Duration)(unsafe.Pointer(in.NodeDeletionTimeout))
	out.MinReadySeconds = (*int32)(unsafe.Pointer(in.MinReadySeconds))
	out.ReadinessGates = *(*[]v1beta1.MachineReadinessGate)(unsafe.Pointer(&in.ReadinessGates))
	out.Strategy = (*v1beta1.MachineDeploymentStrategy)(unsafe.Pointer(in.Strategy))
	out.Variables = (*v1beta1.MachineDeploymentVariables)(unsafe.Pointer(in.Variables))
	return nil
}

// Convert_v1beta2_MachineDeploymentTopology_To_v1beta1_MachineDeploymentTopology is an autogenerated conversion function.
func Convert_v1beta2_MachineDeploymentTopology_To_v1beta1_MachineDeploymentTopology(in *MachineDeploymentTopology, out *v1beta1.MachineDeploymentTopology, s conversion.Scope) error {
	return autoConvert_v1beta2_MachineDeploymentTopology_To_v1beta1_MachineDeploymentTopology(in, out, s)
}

func autoConvert_v1beta1_MachineDeploymentTopology_To_v1beta2_MachineDeploymentTopology(in *v1beta1.MachineDeploymentTopology, out *MachineDeploymentTopology, s conversion.Scope) error {
	if err := Convert_v1beta1_ObjectMeta_To_v1beta2_ObjectMeta(&in.Metadata, &out.Metadata, s); err != nil {
		return err
	}
	out.Class = in.Class
	out.Name = in.Name
	out.FailureDomain = (*string)(unsafe.Pointer(in.FailureDomain))
	out.Replicas = (*int32)(unsafe.Pointer(in.Replicas))
	out.MachineHealthCheck = (*MachineHealthCheckTopology)(unsafe.Pointer(in.MachineHealthCheck))
	out.NodeDrainTimeout = (*metav1.Duration)(unsafe.Pointer(in.NodeDrainTimeout))
	out.NodeVolumeDetachTimeout = (*metav1.Duration)(unsafe.Pointer(in.NodeVolumeDetachTimeout))
	out.NodeDeletionTimeout = (*metav1.Duration)(unsafe.Pointer(in.NodeDeletionTimeout))
	out.MinReadySeconds = (*int32)(unsafe.Pointer(in.MinReadySeconds))
	out.ReadinessGates = *(*[]MachineReadinessGate)(unsafe.Pointer(&in.ReadinessGates))
	out.Strategy = (*MachineDeploymentStrategy)(unsafe.Pointer(in.Strategy))
	out.Variables = (*MachineDeploymentVariables)(unsafe.Pointer(in.Variables))
	return nil
}

// Convert_v1beta1_MachineDeploymentTopology_To_v1beta2_MachineDeploymentTopology is an autogenerated conversion function.
func Convert_v1beta1_MachineDeploymentTopology_To_v1beta2_MachineDeploymentTopology(in *v1beta1.MachineDeploymentTopology, out *MachineDeploymentTopology, s conversion.Scope) error {
	return autoConvert_v1beta1_MachineDeploymentTopology_To_v1beta2_MachineDeploymentTopology(in, out, s)
}

func autoConvert_v1beta2_MachineDeploymentVariables_To_v1beta1_MachineDeploymentVariables(in *MachineDeploymentVariables, out *v1beta1.MachineDeploymentVariables, s conversion.Scope) error {
	out.Overrides = *(*[]v1beta1.ClusterVariable)(unsafe.Pointer(&in.Overrides))
	return nil
}

// Convert_v1beta2_MachineDeploymentVariables_To_v1beta1_MachineDeploymentVariables is an autogenerated conversion function.
func Convert_v1beta2_MachineDeploymentVariables_To_v1beta1_MachineDeploymentVariables(in *MachineDeploymentVariables, out *v1beta1.MachineDeploymentVariables, s conversion.Scope) error {
	return autoConvert_v1beta2_MachineDeploymentVariables_To_v1beta1_MachineDeploymentVariables(in, out, s)
}

func autoConvert_v1beta1_MachineDeploymentVariables_To_v1beta2_MachineDeploymentVariables(in *v1beta1.MachineDeploymentVariables, out *MachineDeploymentVariables, s conversion.Scope) error {
	out.Overrides = *(*[]ClusterVariable)(unsafe.Pointer(&in.Overrides))
	return nil
}

// Convert_v1beta1_MachineDeploymentVariables_To_v1beta2_MachineDeploymentVariables is an autogenerated conversion function.
func Convert_v1beta1_MachineDeploymentVariables_To_v1beta2_MachineDeploymentVariables(in *v1beta1.MachineDeploymentVariables, out *MachineDeploymentVariables, s conversion.Scope) error {
	return autoConvert_v1beta1_MachineDeploymentVariables_To_v1beta2_MachineDeploymentVariables(in, out, s)
}

func autoConvert_v1beta2_MachineHealthCheckClass_To_v1beta1_MachineHealthCheckClass(in *MachineHealthCheckClass, out *v1beta1.MachineHealthCheckClass, s conversion.Scope) error {
	out.UnhealthyConditions = *(*[]v1beta1.UnhealthyCondition)(unsafe.Pointer(&in.UnhealthyConditions))
	out.MaxUnhealthy = (*intstr.IntOrString)(unsafe.Pointer(in.MaxUnhealthy))
	out.UnhealthyRange = (*string)(unsafe.Pointer(in.UnhealthyRange))
	out.NodeStartupTimeout = (*metav1.Duration)(unsafe.Pointer(in.NodeStartupTimeout))
	out.RemediationTemplate = (*v1.ObjectReference)(unsafe.Pointer(in.RemediationTemplate))
	return nil
}

// Convert_v1beta2_MachineHealthCheckClass_To_v1beta1_MachineHealthCheckClass is an autogenerated conversion function.
func Convert_v1beta2_MachineHealthCheckClass_To_v1beta1_MachineHealthCheckClass(in *MachineHealthCheckClass, out *v1beta1.MachineHealthCheckClass, s conversion.Scope) error {
	return autoConvert_v1beta2_MachineHealthCheckClass_To_v1beta1_MachineHealthCheckClass(in, out, s)
}

func autoConvert_v1beta1_MachineHealthCheckClass_To_v1beta2_MachineHealthCheckClass(in *v1beta1.MachineHealthCheckClass, out *MachineHealthCheckClass, s conversion.Scope) error {
	out.UnhealthyConditions = *(*[]UnhealthyCondition)(unsafe.Pointer(&in.UnhealthyConditions))
	out.MaxUnhealthy = (*intstr.IntOrString)(unsafe.Pointer(in.MaxUnhealthy))
	out.UnhealthyRange = (*string)(unsafe.Pointer(in.UnhealthyRange))
	out.NodeStartupTimeout = (*metav1.Duration)(unsafe.Pointer(in.NodeStartupTimeout))
	out.RemediationTemplate = (*v1.ObjectReference)(unsafe.Pointer(in.RemediationTemplate))
	return nil
}

// Convert_v1beta1_MachineHealthCheckClass_To_v1beta2_MachineHealthCheckClass is an autogenerated conversion function.
func Convert_v1beta1_MachineHealthCheckClass_To_v1beta2_MachineHealthCheckClass(in *v1beta1.MachineHealthCheckClass, out *MachineHealthCheckClass, s conversion.Scope) error {
	return autoConvert_v1beta1_MachineHealthCheckClass_To_v1beta2_MachineHealthCheckClass(in, out, s)
}

func autoConvert_v1beta2_MachineHealthCheckTopology_To_v1beta1_MachineHealthCheckTopology(in *MachineHealthCheckTopology, out *v1beta1.MachineHealthCheckTopology, s conversion.Scope) error {
	out.Enable = (*bool)(unsafe.Pointer(in.Enable))
	if err := Convert_v1beta2_MachineHealthCheckClass_To_v1beta1_MachineHealthCheckClass(&in.MachineHealthCheckClass, &out.MachineHealthCheckClass, s); err != nil {
		return err
	}
	return nil
}

// Convert_v1beta2_MachineHealthCheckTopology_To_v1beta1_MachineHealthCheckTopology is an autogenerated conversion function.
func Convert_v1beta2_MachineHealthCheckTopology_To_v1beta1_MachineHealthCheckTopology(in *MachineHealthCheckTopology, out *v1beta1.MachineHealthCheckTopology, s conversion.Scope) error {
	return autoConvert_v1beta2_MachineHealthCheckTopology_To_v1beta1_MachineHealthCheckTopology(in, out, s)
}

func autoConvert_v1beta1_MachineHealthCheckTopology_To_v1beta2_MachineHealthCheckTopology(in *v1beta1.MachineHealthCheckTopology, out *MachineHealthCheckTopology, s conversion.Scope) error {
	out.Enable = (*bool)(unsafe.Pointer(in.Enable))
	if err := Convert_v1beta1_MachineHealthCheckClass_To_v1beta2_MachineHealthCheckClass(&in.MachineHealthCheckClass, &out.MachineHealthCheckClass, s); err != nil {
		return err
	}
	return nil
}

// Convert_v1beta1_MachineHealthCheckTopology_To_v1beta2_MachineHealthCheckTopology is an autogenerated conversion function.
func Convert_v1beta1_MachineHealthCheckTopology_To_v1beta2_MachineHealthCheckTopology(in *v1beta1.MachineHealthCheckTopology, out *MachineHealthCheckTopology, s conversion.Scope) error {
	return autoConvert_v1beta1_MachineHealthCheckTopology_To_v1beta2_MachineHealthCheckTopology(in, out, s)
}

func autoConvert_v1beta2_MachinePoolTopology_To_v1beta1_MachinePoolTopology(in *MachinePoolTopology, out *v1beta1.MachinePoolTopology, s conversion.Scope) error {
	if err := Convert_v1beta2_ObjectMeta_To_v1beta1_ObjectMeta(&in.Metadata, &out.Metadata, s); err != nil {
		return err
	}
	out.Class = in.Class
	out.Name = in.Name
	out.FailureDomains = *(*[]string)(unsafe.Pointer(&in.FailureDomains))
	out.NodeDrainTimeout = (*metav1.Duration)(unsafe.Pointer(in.NodeDrainTimeout))
	out.NodeVolumeDetachTimeout = (*metav1.Duration)(unsafe.Pointer(in.NodeVolumeDetachTimeout))
	out.NodeDeletionTimeout = (*metav1.Duration)(unsafe.Pointer(in.NodeDeletionTimeout))
	out.MinReadySeconds = (*int32)(unsafe.Pointer(in.MinReadySeconds))
	out.Replicas = (*int32)(unsafe.Pointer(in.Replicas))
	out.Variables = (*v1beta1.MachinePoolVariables)(unsafe.Pointer(in.Variables))
	return nil
}

// Convert_v1beta2_MachinePoolTopology_To_v1beta1_MachinePoolTopology is an autogenerated conversion function.
func Convert_v1beta2_MachinePoolTopology_To_v1beta1_MachinePoolTopology(in *MachinePoolTopology, out *v1beta1.MachinePoolTopology, s conversion.Scope) error {
	return autoConvert_v1beta2_MachinePoolTopology_To_v1beta1_MachinePoolTopology(in, out, s)
}

func autoConvert_v1beta1_MachinePoolTopology_To_v1beta2_MachinePoolTopology(in *v1beta1.MachinePoolTopology, out *MachinePoolTopology, s conversion.Scope) error {
	if err := Convert_v1beta1_ObjectMeta_To_v1beta2_ObjectMeta(&in.Metadata, &out.Metadata, s); err != nil {
		return err
	}
	out.Class = in.Class
	out.Name = in.Name
	out.FailureDomains = *(*[]string)(unsafe.Pointer(&in.FailureDomains))
	out.NodeDrainTimeout = (*metav1.Duration)(unsafe.Pointer(in.NodeDrainTimeout))
	out.NodeVolumeDetachTimeout = (*metav1.Duration)(unsafe.Pointer(in.NodeVolumeDetachTimeout))
	out.NodeDeletionTimeout = (*metav1.Duration)(unsafe.Pointer(in.NodeDeletionTimeout))
	out.MinReadySeconds = (*int32)(unsafe.Pointer(in.MinReadySeconds))
	out.Replicas = (*int32)(unsafe.Pointer(in.Replicas))
	out.Variables = (*MachinePoolVariables)(unsafe.Pointer(in.Variables))
	return nil
}

// Convert_v1beta1_MachinePoolTopology_To_v1beta2_MachinePoolTopology is an autogenerated conversion function.
func Convert_v1beta1_MachinePoolTopology_To_v1beta2_MachinePoolTopology(in *v1beta1.MachinePoolTopology, out *MachinePoolTopology, s conversion.Scope) error {
	return autoConvert_v1beta1_MachinePoolTopology_To_v1beta2_MachinePoolTopology(in, out, s)
}

func autoConvert_v1beta2_MachinePoolVariables_To_v1beta1_MachinePoolVariables(in *MachinePoolVariables, out *v1beta1.MachinePoolVariables, s conversion.Scope) error {
	out.Overrides = *(*[]v1beta1.ClusterVariable)(unsafe.Pointer(&in.Overrides))
	return nil
}

// Convert_v1beta2_MachinePoolVariables_To_v1beta1_MachinePoolVariables is an autogenerated conversion function.
func Convert_v1beta2_MachinePoolVariables_To_v1beta1_MachinePoolVariables(in *MachinePoolVariables, out *v1beta1.MachinePoolVariables, s conversion.Scope) error {
	return autoConvert_v1beta2_MachinePoolVariables_To_v1beta1_MachinePoolVariables(in, out, s)
}

func autoConvert_v1beta1_MachinePoolVariables_To_v1beta2_MachinePoolVariables(in *v1beta1.MachinePoolVariables, out *MachinePoolVariables, s conversion.Scope) error {
	out.Overrides = *(*[]ClusterVariable)(unsafe.Pointer(&in.Overrides))
	return nil
}

// Convert_v1beta1_MachinePoolVariables_To_v1beta2_MachinePoolVariables is an autogenerated conversion function.
func Convert_v1beta1_MachinePoolVariables_To_v1beta2_MachinePoolVariables(in *v1beta1.MachinePoolVariables, out *MachinePoolVariables, s conversion.Scope) error {
	return autoConvert_v1beta1_MachinePoolVariables_To_v1beta2_MachinePoolVariables(in, out, s)
}

func autoConvert_v1beta2_MachineReadinessGate_To_v1beta1_MachineReadinessGate(in *MachineReadinessGate, out *v1beta1.MachineReadinessGate, s conversion.Scope) error {
	out.ConditionType = in.ConditionType
	out.Polarity = v1beta1.ConditionPolarity(in.Polarity)
	return nil
}

// Convert_v1beta2_MachineReadinessGate_To_v1beta1_MachineReadinessGate is an autogenerated conversion function.
func Convert_v1beta2_MachineReadinessGate_To_v1beta1_MachineReadinessGate(in *MachineReadinessGate, out *v1beta1.MachineReadinessGate, s conversion.Scope) error {
	return autoConvert_v1beta2_MachineReadinessGate_To_v1beta1_MachineReadinessGate(in, out, s)
}

func autoConvert_v1beta1_MachineReadinessGate_To_v1beta2_MachineReadinessGate(in *v1beta1.MachineReadinessGate, out *MachineReadinessGate, s conversion.Scope) error {
	out.ConditionType = in.ConditionType
	out.Polarity = ConditionPolarity(in.Polarity)
	return nil
}

// Convert_v1beta1_MachineReadinessGate_To_v1beta2_MachineReadinessGate is an autogenerated conversion function.
func Convert_v1beta1_MachineReadinessGate_To_v1beta2_MachineReadinessGate(in *v1beta1.MachineReadinessGate, out *MachineReadinessGate, s conversion.Scope) error {
	return autoConvert_v1beta1_MachineReadinessGate_To_v1beta2_MachineReadinessGate(in, out, s)
}

func autoConvert_v1beta2_MachineRollingUpdateDeployment_To_v1beta1_MachineRollingUpdateDeployment(in *MachineRollingUpdateDeployment, out *v1beta1.MachineRollingUpdateDeployment, s conversion.Scope) error {
	out.MaxUnavailable = (*intstr.IntOrString)(unsafe.Pointer(in.MaxUnavailable))
	out.MaxSurge = (*intstr.IntOrString)(unsafe.Pointer(in.MaxSurge))
	out.DeletePolicy = (*string)(unsafe.Pointer(in.DeletePolicy))
	return nil
}

// Convert_v1beta2_MachineRollingUpdateDeployment_To_v1beta1_MachineRollingUpdateDeployment is an autogenerated conversion function.
func Convert_v1beta2_MachineRollingUpdateDeployment_To_v1beta1_MachineRollingUpdateDeployment(in *MachineRollingUpdateDeployment, out *v1beta1.MachineRollingUpdateDeployment, s conversion.Scope) error {
	return autoConvert_v1beta2_MachineRollingUpdateDeployment_To_v1beta1_MachineRollingUpdateDeployment(in, out, s)
}

func autoConvert_v1beta1_MachineRollingUpdateDeployment_To_v1beta2_MachineRollingUpdateDeployment(in *v1beta1.MachineRollingUpdateDeployment, out *MachineRollingUpdateDeployment, s conversion.Scope) error {
	out.MaxUnavailable = (*intstr.IntOrString)(unsafe.Pointer(in.MaxUnavailable))
	out.MaxSurge = (*intstr.IntOrString)(unsafe.Pointer(in.MaxSurge))
	out.DeletePolicy = (*string)(unsafe.Pointer(in.DeletePolicy))
	return nil
}

// Convert_v1beta1_MachineRollingUpdateDeployment_To_v1beta2_MachineRollingUpdateDeployment is an autogenerated conversion function.
func Convert_v1beta1_MachineRollingUpdateDeployment_To_v1beta2_MachineRollingUpdateDeployment(in *v1beta1.MachineRollingUpdateDeployment, out *MachineRollingUpdateDeployment, s conversion.Scope) error {
	return autoConvert_v1beta1_MachineRollingUpdateDeployment_To_v1beta2_MachineRollingUpdateDeployment(in, out, s)
}

func autoConvert_v1beta2_NetworkRanges_To_v1beta1_NetworkRanges(in *NetworkRanges, out *v1beta1.NetworkRanges, s conversion.Scope) error {
	out.CIDRBlocks = *(*[]string)(unsafe.Pointer(&in.CIDRBlocks))
	return nil
}

// Convert_v1beta2_NetworkRanges_To_v1beta1_NetworkRanges is an autogenerated conversion function.
func Convert_v1beta2_NetworkRanges_To_v1beta1_NetworkRanges(in *NetworkRanges, out *v1beta1.NetworkRanges, s conversion.Scope) error {
	return autoConvert_v1beta2_NetworkRanges_To_v1beta1_NetworkRanges(in, out, s)
}

func autoConvert_v1beta1_NetworkRanges_To_v1beta2_NetworkRanges(in *v1beta1.NetworkRanges, out *NetworkRanges, s conversion.Scope) error {
	out.CIDRBlocks = *(*[]string)(unsafe.Pointer(&in.CIDRBlocks))
	return nil
}

// Convert_v1beta1_NetworkRanges_To_v1beta2_NetworkRanges is an autogenerated conversion function.
func Convert_v1beta1_NetworkRanges_To_v1beta2_NetworkRanges(in *v1beta1.NetworkRanges, out *NetworkRanges, s conversion.Scope) error {
	return autoConvert_v1beta1_NetworkRanges_To_v1beta2_NetworkRanges(in, out, s)
}

func autoConvert_v1beta2_ObjectMeta_To_v1beta1_ObjectMeta(in *ObjectMeta, out *v1beta1.ObjectMeta, s conversion.Scope) error {
	out.Labels = *(*map[string]string)(unsafe.Pointer(&in.Labels))
	out.Annotations = *(*map[string]string)(unsafe.Pointer(&in.Annotations))
	return nil
}

// Convert_v1beta2_ObjectMeta_To_v1beta1_ObjectMeta is an autogenerated conversion function.
func Convert_v1beta2_ObjectMeta_To_v1beta1_ObjectMeta(in *ObjectMeta, out *v1beta1.ObjectMeta, s conversion.Scope) error {
	return autoConvert_v1beta2_ObjectMeta_To_v1beta1_ObjectMeta(in, out, s)
}

func autoConvert_v1beta1_ObjectMeta_To_v1beta2_ObjectMeta(in *v1beta1.ObjectMeta, out *ObjectMeta, s conversion.Scope) error {
	out.Labels = *(*map[string]string)(unsafe.Pointer(&in.Labels))
	out.Annotations = *(*map[string]string)(unsafe.Pointer(&in.Annotations))
	return nil
}

// Convert_v1beta1_ObjectMeta_To_v1beta2_ObjectMeta is an autogenerated conversion function.
func Convert_v1beta1_ObjectMeta_To_v1beta2_ObjectMeta(in *v1beta1.ObjectMeta, out *ObjectMeta, s conversion.Scope) error {
	return autoConvert_v1beta1_ObjectMeta_To_v1beta2_ObjectMeta(in, out, s)
}

func autoConvert_v1beta2_RemediationStrategy_To_v1beta1_RemediationStrategy(in *RemediationStrategy, out *v1beta1.RemediationStrategy, s conversion.Scope) error {
	out.MaxInFlight = (*intstr.IntOrString)(unsafe.Pointer(in.MaxInFlight))
	return nil
}

// Convert_v1beta2_RemediationStrategy_To_v1beta1_RemediationStrategy is an autogenerated conversion function.
func Convert_v1beta2_RemediationStrategy_To_v1beta1_RemediationStrategy(in *RemediationStrategy, out *v1beta1.RemediationStrategy, s conversion.Scope) error {
	return autoConvert_v1beta2_RemediationStrategy_To_v1beta1_RemediationStrategy(in, out, s)
}

func autoConvert_v1beta1_RemediationStrategy_To_v1beta2_RemediationStrategy(in *v1beta1.RemediationStrategy, out *RemediationStrategy, s conversion.Scope) error {
	out.MaxInFlight = (*intstr.IntOrString)(unsafe.Pointer(in.MaxInFlight))
	return nil
}

// Convert_v1beta1_RemediationStrategy_To_v1beta2_RemediationStrategy is an autogenerated conversion function.
func Convert_v1beta1_RemediationStrategy_To_v1beta2_RemediationStrategy(in *v1beta1.RemediationStrategy, out *RemediationStrategy, s conversion.Scope) error {
	return autoConvert_v1beta1_RemediationStrategy_To_v1beta2_RemediationStrategy(in, out, s)
}

func autoConvert_v1beta2_Topology_To_v1beta1_Topology(in *Topology, out *v1beta1.Topology, s conversion.Scope) error {
	out.Class = in.Class
	out.ClassNamespace = in.ClassNamespace
	out.Version = in.Version
	out.RolloutAfter = (*metav1.Time)(unsafe.Pointer(in.RolloutAfter))
	if err := Convert_v1beta2_ControlPlaneTopology_To_v1beta1_ControlPlaneTopology(&in.ControlPlane, &out.ControlPlane, s); err != nil {
		return err
	}
	out.Workers = (*v1beta1.WorkersTopology)(unsafe.Pointer(in.Workers))
	out.Variables = *(*[]v1beta1.ClusterVariable)(unsafe.Pointer(&in.Variables))
	return nil
}

// Convert_v1beta2_Topology_To_v1beta1_Topology is an autogenerated conversion function.
func Convert_v1beta2_Topology_To_v1beta1_Topology(in *Topology, out *v1beta1.Topology, s conversion.Scope) error {
	return autoConvert_v1beta2_Topology_To_v1beta1_Topology(in, out, s)
}

func autoConvert_v1beta1_Topology_To_v1beta2_Topology(in *v1beta1.Topology, out *Topology, s conversion.Scope) error {
	out.Class = in.Class
	out.ClassNamespace = in.ClassNamespace
	out.Version = in.Version
	out.RolloutAfter = (*metav1.Time)(unsafe.Pointer(in.RolloutAfter))
	if err := Convert_v1beta1_ControlPlaneTopology_To_v1beta2_ControlPlaneTopology(&in.ControlPlane, &out.ControlPlane, s); err != nil {
		return err
	}
	out.Workers = (*WorkersTopology)(unsafe.Pointer(in.Workers))
	out.Variables = *(*[]ClusterVariable)(unsafe.Pointer(&in.Variables))
	return nil
}

// Convert_v1beta1_Topology_To_v1beta2_Topology is an autogenerated conversion function.
func Convert_v1beta1_Topology_To_v1beta2_Topology(in *v1beta1.Topology, out *Topology, s conversion.Scope) error {
	return autoConvert_v1beta1_Topology_To_v1beta2_Topology(in, out, s)
}

func autoConvert_v1beta2_UnhealthyCondition_To_v1beta1_UnhealthyCondition(in *UnhealthyCondition, out *v1beta1.UnhealthyCondition, s conversion.Scope) error {
	out.Type = v1.NodeConditionType(in.Type)
	out.Status = v1.ConditionStatus(in.Status)
	out.Timeout = in.Timeout
	return nil
}

// Convert_v1beta2_UnhealthyCondition_To_v1beta1_UnhealthyCondition is an autogenerated conversion function.
func Convert_v1beta2_UnhealthyCondition_To_v1beta1_UnhealthyCondition(in *UnhealthyCondition, out *v1beta1.UnhealthyCondition, s conversion.Scope) error {
	return autoConvert_v1beta2_UnhealthyCondition_To_v1beta1_UnhealthyCondition(in, out, s)
}

func autoConvert_v1beta1_UnhealthyCondition_To_v1beta2_UnhealthyCondition(in *v1beta1.UnhealthyCondition, out *UnhealthyCondition, s conversion.Scope) error {
	out.Type = v1.NodeConditionType(in.Type)
	out.Status = v1.ConditionStatus(in.Status)
	out.Timeout = in.Timeout
	return nil
}

// Convert_v1beta1_UnhealthyCondition_To_v1beta2_UnhealthyCondition is an autogenerated conversion function.
func Convert_v1beta1_UnhealthyCondition_To_v1beta2_UnhealthyCondition(in *v1beta1.UnhealthyCondition, out *UnhealthyCondition, s conversion.Scope) error {
	return autoConvert_v1beta1_UnhealthyCondition_To_v1beta2_UnhealthyCondition(in, out, s)
}

func autoConvert_v1beta2_WorkersStatus_To_v1beta1_WorkersStatus(in *WorkersStatus, out *v1beta1.WorkersStatus, s conversion.Scope) error {
	out.DesiredReplicas = (*int32)(unsafe.Pointer(in.DesiredReplicas))
	out.Replicas = (*int32)(unsafe.Pointer(in.Replicas))
	out.UpToDateReplicas = (*int32)(unsafe.Pointer(in.UpToDateReplicas))
	out.ReadyReplicas = (*int32)(unsafe.Pointer(in.ReadyReplicas))
	out.AvailableReplicas = (*int32)(unsafe.Pointer(in.AvailableReplicas))
	return nil
}

// Convert_v1beta2_WorkersStatus_To_v1beta1_WorkersStatus is an autogenerated conversion function.
func Convert_v1beta2_WorkersStatus_To_v1beta1_WorkersStatus(in *WorkersStatus, out *v1beta1.WorkersStatus, s conversion.Scope) error {
	return autoConvert_v1beta2_WorkersStatus_To_v1beta1_WorkersStatus(in, out, s)
}

func autoConvert_v1beta1_WorkersStatus_To_v1beta2_WorkersStatus(in *v1beta1.WorkersStatus, out *WorkersStatus, s conversion.Scope) error {
	out.DesiredReplicas = (*int32)(unsafe.Pointer(in.DesiredReplicas))
	out.Replicas = (*int32)(unsafe.Pointer(in.Replicas))
	out.UpToDateReplicas = (*int32)(unsafe.Pointer(in.UpToDateReplicas))
	out.ReadyReplicas = (*int32)(unsafe.Pointer(in.ReadyReplicas))
	out.AvailableReplicas = (*int32)(unsafe.Pointer(in.AvailableReplicas))
	return nil
}

// Convert_v1beta1_WorkersStatus_To_v1beta2_WorkersStatus is an autogenerated conversion function.
func Convert_v1beta1_WorkersStatus_To_v1beta2_WorkersStatus(in *v1beta1.WorkersStatus, out *WorkersStatus, s conversion.Scope) error {
	return autoConvert_v1beta1_WorkersStatus_To_v1beta2_WorkersStatus(in, out, s)
}

func autoConvert_v1beta2_WorkersTopology_To_v1beta1_WorkersTopology(in *WorkersTopology, out *v1beta1.WorkersTopology, s conversion.Scope) error {
	out.MachineDeployments = *(*[]v1beta1.MachineDeploymentTopology)(unsafe.Pointer(&in.MachineDeployments))
	out.MachinePools = *(*[]v1beta1.MachinePoolTopology)(unsafe.Pointer(&in.MachinePools))
	return nil
}

// Convert_v1beta2_WorkersTopology_To_v1beta1_WorkersTopology is an autogenerated conversion function.
func Convert_v1beta2_WorkersTopology_To_v1beta1_WorkersTopology(in *WorkersTopology, out *v1beta1.WorkersTopology, s conversion.Scope) error {
	return autoConvert_v1beta2_WorkersTopology_To_v1beta1_WorkersTopology(in, out, s)
}

func autoConvert_v1beta1_WorkersTopology_To_v1beta2_WorkersTopology(in *v1beta1.WorkersTopology, out *WorkersTopology, s conversion.Scope) error {
	out.MachineDeployments = *(*[]MachineDeploymentTopology)(unsafe.Pointer(&in.MachineDeployments))
	out.MachinePools = *(*[]MachinePoolTopology)(unsafe.Pointer(&in.MachinePools))
	return nil
}

// Convert_v1beta1_WorkersTopology_To_v1beta2_WorkersTopology is an autogenerated conversion function.
func Convert_v1beta1_WorkersTopology_To_v1beta2_WorkersTopology(in *v1beta1.WorkersTopology, out *WorkersTopology, s conversion.Scope) error {
	return autoConvert_v1beta1_WorkersTopology_To_v1beta2_WorkersTopology(in, out, s)
}
