# Please see the documentation for all configuration options:
# https://docs.github.com/github/administering-a-repository/configuration-options-for-dependency-updates
version: 2
updates:
# GitHub Actions
- package-ecosystem: "github-actions"
  directory: "/"
  schedule:
      interval: "weekly"
  groups:
    all: # Bump all actions in a single PR.
      patterns: [ "*" ]
  commit-message:
      prefix: ":seedling:"
  labels:
    - "area/ci"
    - "ok-to-test"

# Go modules
- package-ecosystem: "gomod"
  directories:
  - "/"
  - "/test"
  - "/hack/tools"
  schedule:
    interval: "weekly"
    day: "wednesday"
    time: "08:33"
  ## group all dependencies with a k8s.io prefix into a single PR.
  groups:
    patch: # Bump all patch versions in a single PR (patch bumps rarely should lead to issues).
      patterns: [ "*" ]
      update-types: [ "patch" ]
  ignore:
    # Ignore controller-runtime as its upgraded manually.
    - dependency-name: "sigs.k8s.io/controller-runtime"
      update-types: [ "version-update:semver-major", "version-update:semver-minor" ]
    # Ignore k8s and its transitives modules as they are upgraded manually together with controller-runtime.
    - dependency-name: "k8s.io/*"
      update-types: [ "version-update:semver-major", "version-update:semver-minor" ]
    - dependency-name: "go.etcd.io/*"
      update-types: [ "version-update:semver-major", "version-update:semver-minor" ]
    - dependency-name: "google.golang.org/grpc"
      update-types: [ "version-update:semver-major", "version-update:semver-minor" ]
    # Bumping the kustomize API independently can break compatibility with client-go as they share k8s.io/kube-openapi as a dependency.
    - dependency-name: "sigs.k8s.io/kustomize/api"
      update-types: [ "version-update:semver-major", "version-update:semver-minor" ]
  commit-message:
    prefix: ":seedling:"
  labels:
    - "area/dependency"
    - "ok-to-test"
