// +build !ignore_autogenerated

/*
Copyright The Kubernetes Authors.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by controller-gen. DO NOT EDIT.

package variables

import (
	"k8s.io/apiextensions-apiserver/pkg/apis/apiextensions/v1"
)

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *PatchDefinitionClass) DeepCopyInto(out *PatchDefinitionClass) {
	*out = *in
	in.Target.DeepCopyInto(&out.Target)
	if in.JSONPatches != nil {
		in, out := &in.JSONPatches, &out.JSONPatches
		*out = make([]PatchDefinitionJSONPatchClass, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new PatchDefinitionClass.
func (in *PatchDefinitionClass) DeepCopy() *PatchDefinitionClass {
	if in == nil {
		return nil
	}
	out := new(PatchDefinitionClass)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *PatchDefinitionJSONPatchClass) DeepCopyInto(out *PatchDefinitionJSONPatchClass) {
	*out = *in
	if in.Value != nil {
		in, out := &in.Value, &out.Value
		*out = new(v1.JSON)
		(*in).DeepCopyInto(*out)
	}
	if in.ValueFrom != nil {
		in, out := &in.ValueFrom, &out.ValueFrom
		*out = new(PatchDefinitionJSONPatchValueClass)
		(*in).DeepCopyInto(*out)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new PatchDefinitionJSONPatchClass.
func (in *PatchDefinitionJSONPatchClass) DeepCopy() *PatchDefinitionJSONPatchClass {
	if in == nil {
		return nil
	}
	out := new(PatchDefinitionJSONPatchClass)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *PatchDefinitionJSONPatchValueClass) DeepCopyInto(out *PatchDefinitionJSONPatchValueClass) {
	*out = *in
	if in.Variable != nil {
		in, out := &in.Variable, &out.Variable
		*out = new(string)
		**out = **in
	}
	if in.Template != nil {
		in, out := &in.Template, &out.Template
		*out = new(string)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new PatchDefinitionJSONPatchValueClass.
func (in *PatchDefinitionJSONPatchValueClass) DeepCopy() *PatchDefinitionJSONPatchValueClass {
	if in == nil {
		return nil
	}
	out := new(PatchDefinitionJSONPatchValueClass)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *PatchDefinitionTargetClass) DeepCopyInto(out *PatchDefinitionTargetClass) {
	*out = *in
	if in.Selector != nil {
		in, out := &in.Selector, &out.Selector
		*out = new(PatchDefinitionTargetSelectorClass)
		(*in).DeepCopyInto(*out)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new PatchDefinitionTargetClass.
func (in *PatchDefinitionTargetClass) DeepCopy() *PatchDefinitionTargetClass {
	if in == nil {
		return nil
	}
	out := new(PatchDefinitionTargetClass)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *PatchDefinitionTargetSelectorClass) DeepCopyInto(out *PatchDefinitionTargetSelectorClass) {
	*out = *in
	if in.MatchResources != nil {
		in, out := &in.MatchResources, &out.MatchResources
		*out = new(PatchDefinitionTargetSelectorResourcesClass)
		(*in).DeepCopyInto(*out)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new PatchDefinitionTargetSelectorClass.
func (in *PatchDefinitionTargetSelectorClass) DeepCopy() *PatchDefinitionTargetSelectorClass {
	if in == nil {
		return nil
	}
	out := new(PatchDefinitionTargetSelectorClass)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *PatchDefinitionTargetSelectorResourcesClass) DeepCopyInto(out *PatchDefinitionTargetSelectorResourcesClass) {
	*out = *in
	if in.ControlPlane != nil {
		in, out := &in.ControlPlane, &out.ControlPlane
		*out = new(bool)
		**out = **in
	}
	if in.MachineDeploymentClass != nil {
		in, out := &in.MachineDeploymentClass, &out.MachineDeploymentClass
		*out = new(PatchDefinitionTargetSelectorResourcesMachineDeploymentClass)
		(*in).DeepCopyInto(*out)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new PatchDefinitionTargetSelectorResourcesClass.
func (in *PatchDefinitionTargetSelectorResourcesClass) DeepCopy() *PatchDefinitionTargetSelectorResourcesClass {
	if in == nil {
		return nil
	}
	out := new(PatchDefinitionTargetSelectorResourcesClass)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *PatchDefinitionTargetSelectorResourcesMachineDeploymentClass) DeepCopyInto(out *PatchDefinitionTargetSelectorResourcesMachineDeploymentClass) {
	*out = *in
	if in.Names != nil {
		in, out := &in.Names, &out.Names
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new PatchDefinitionTargetSelectorResourcesMachineDeploymentClass.
func (in *PatchDefinitionTargetSelectorResourcesMachineDeploymentClass) DeepCopy() *PatchDefinitionTargetSelectorResourcesMachineDeploymentClass {
	if in == nil {
		return nil
	}
	out := new(PatchDefinitionTargetSelectorResourcesMachineDeploymentClass)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *VariableDefinitionClass) DeepCopyInto(out *VariableDefinitionClass) {
	*out = *in
	in.Schema.DeepCopyInto(&out.Schema)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new VariableDefinitionClass.
func (in *VariableDefinitionClass) DeepCopy() *VariableDefinitionClass {
	if in == nil {
		return nil
	}
	out := new(VariableDefinitionClass)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *VariableDefinitionSchemaClass) DeepCopyInto(out *VariableDefinitionSchemaClass) {
	*out = *in
	in.OpenAPIV3Schema.DeepCopyInto(&out.OpenAPIV3Schema)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new VariableDefinitionSchemaClass.
func (in *VariableDefinitionSchemaClass) DeepCopy() *VariableDefinitionSchemaClass {
	if in == nil {
		return nil
	}
	out := new(VariableDefinitionSchemaClass)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *VariableTopology) DeepCopyInto(out *VariableTopology) {
	*out = *in
	in.Value.DeepCopyInto(&out.Value)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new VariableTopology.
func (in *VariableTopology) DeepCopy() *VariableTopology {
	if in == nil {
		return nil
	}
	out := new(VariableTopology)
	in.DeepCopyInto(out)
	return out
}
