//go:build !ignore_autogenerated_runtime
// +build !ignore_autogenerated_runtime

/*
Copyright The Kubernetes Authors.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by conversion-gen. DO NOT EDIT.

package v1alpha1

import (
	unsafe "unsafe"

	conversion "k8s.io/apimachinery/pkg/conversion"
	runtime "k8s.io/apimachinery/pkg/runtime"
	types "k8s.io/apimachinery/pkg/types"
	v1alpha4 "sigs.k8s.io/cluster-api/api/v1alpha4"
	v1beta1 "sigs.k8s.io/cluster-api/api/v1beta1"
	v1alpha2 "sigs.k8s.io/cluster-api/exp/runtime/hooks/api/v1alpha2"
)

func init() {
	localSchemeBuilder.Register(RegisterConversions)
}

// RegisterConversions adds conversion functions to the given scheme.
// Public to allow building arbitrary schemes.
func RegisterConversions(s *runtime.Scheme) error {
	if err := s.AddGeneratedConversionFunc((*AfterClusterUpgradeRequest)(nil), (*v1alpha2.AfterClusterUpgradeRequest)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_v1alpha1_AfterClusterUpgradeRequest_To_v1alpha2_AfterClusterUpgradeRequest(a.(*AfterClusterUpgradeRequest), b.(*v1alpha2.AfterClusterUpgradeRequest), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*v1alpha2.AfterClusterUpgradeRequest)(nil), (*AfterClusterUpgradeRequest)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_v1alpha2_AfterClusterUpgradeRequest_To_v1alpha1_AfterClusterUpgradeRequest(a.(*v1alpha2.AfterClusterUpgradeRequest), b.(*AfterClusterUpgradeRequest), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*AfterClusterUpgradeResponse)(nil), (*v1alpha2.AfterClusterUpgradeResponse)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_v1alpha1_AfterClusterUpgradeResponse_To_v1alpha2_AfterClusterUpgradeResponse(a.(*AfterClusterUpgradeResponse), b.(*v1alpha2.AfterClusterUpgradeResponse), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*v1alpha2.AfterClusterUpgradeResponse)(nil), (*AfterClusterUpgradeResponse)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_v1alpha2_AfterClusterUpgradeResponse_To_v1alpha1_AfterClusterUpgradeResponse(a.(*v1alpha2.AfterClusterUpgradeResponse), b.(*AfterClusterUpgradeResponse), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*AfterControlPlaneInitializedRequest)(nil), (*v1alpha2.AfterControlPlaneInitializedRequest)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_v1alpha1_AfterControlPlaneInitializedRequest_To_v1alpha2_AfterControlPlaneInitializedRequest(a.(*AfterControlPlaneInitializedRequest), b.(*v1alpha2.AfterControlPlaneInitializedRequest), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*v1alpha2.AfterControlPlaneInitializedRequest)(nil), (*AfterControlPlaneInitializedRequest)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_v1alpha2_AfterControlPlaneInitializedRequest_To_v1alpha1_AfterControlPlaneInitializedRequest(a.(*v1alpha2.AfterControlPlaneInitializedRequest), b.(*AfterControlPlaneInitializedRequest), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*AfterControlPlaneInitializedResponse)(nil), (*v1alpha2.AfterControlPlaneInitializedResponse)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_v1alpha1_AfterControlPlaneInitializedResponse_To_v1alpha2_AfterControlPlaneInitializedResponse(a.(*AfterControlPlaneInitializedResponse), b.(*v1alpha2.AfterControlPlaneInitializedResponse), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*v1alpha2.AfterControlPlaneInitializedResponse)(nil), (*AfterControlPlaneInitializedResponse)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_v1alpha2_AfterControlPlaneInitializedResponse_To_v1alpha1_AfterControlPlaneInitializedResponse(a.(*v1alpha2.AfterControlPlaneInitializedResponse), b.(*AfterControlPlaneInitializedResponse), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*AfterControlPlaneUpgradeRequest)(nil), (*v1alpha2.AfterControlPlaneUpgradeRequest)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_v1alpha1_AfterControlPlaneUpgradeRequest_To_v1alpha2_AfterControlPlaneUpgradeRequest(a.(*AfterControlPlaneUpgradeRequest), b.(*v1alpha2.AfterControlPlaneUpgradeRequest), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*v1alpha2.AfterControlPlaneUpgradeRequest)(nil), (*AfterControlPlaneUpgradeRequest)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_v1alpha2_AfterControlPlaneUpgradeRequest_To_v1alpha1_AfterControlPlaneUpgradeRequest(a.(*v1alpha2.AfterControlPlaneUpgradeRequest), b.(*AfterControlPlaneUpgradeRequest), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*AfterControlPlaneUpgradeResponse)(nil), (*v1alpha2.AfterControlPlaneUpgradeResponse)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_v1alpha1_AfterControlPlaneUpgradeResponse_To_v1alpha2_AfterControlPlaneUpgradeResponse(a.(*AfterControlPlaneUpgradeResponse), b.(*v1alpha2.AfterControlPlaneUpgradeResponse), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*v1alpha2.AfterControlPlaneUpgradeResponse)(nil), (*AfterControlPlaneUpgradeResponse)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_v1alpha2_AfterControlPlaneUpgradeResponse_To_v1alpha1_AfterControlPlaneUpgradeResponse(a.(*v1alpha2.AfterControlPlaneUpgradeResponse), b.(*AfterControlPlaneUpgradeResponse), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*BeforeClusterCreateRequest)(nil), (*v1alpha2.BeforeClusterCreateRequest)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_v1alpha1_BeforeClusterCreateRequest_To_v1alpha2_BeforeClusterCreateRequest(a.(*BeforeClusterCreateRequest), b.(*v1alpha2.BeforeClusterCreateRequest), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*v1alpha2.BeforeClusterCreateRequest)(nil), (*BeforeClusterCreateRequest)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_v1alpha2_BeforeClusterCreateRequest_To_v1alpha1_BeforeClusterCreateRequest(a.(*v1alpha2.BeforeClusterCreateRequest), b.(*BeforeClusterCreateRequest), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*BeforeClusterCreateResponse)(nil), (*v1alpha2.BeforeClusterCreateResponse)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_v1alpha1_BeforeClusterCreateResponse_To_v1alpha2_BeforeClusterCreateResponse(a.(*BeforeClusterCreateResponse), b.(*v1alpha2.BeforeClusterCreateResponse), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*v1alpha2.BeforeClusterCreateResponse)(nil), (*BeforeClusterCreateResponse)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_v1alpha2_BeforeClusterCreateResponse_To_v1alpha1_BeforeClusterCreateResponse(a.(*v1alpha2.BeforeClusterCreateResponse), b.(*BeforeClusterCreateResponse), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*BeforeClusterDeleteRequest)(nil), (*v1alpha2.BeforeClusterDeleteRequest)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_v1alpha1_BeforeClusterDeleteRequest_To_v1alpha2_BeforeClusterDeleteRequest(a.(*BeforeClusterDeleteRequest), b.(*v1alpha2.BeforeClusterDeleteRequest), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*v1alpha2.BeforeClusterDeleteRequest)(nil), (*BeforeClusterDeleteRequest)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_v1alpha2_BeforeClusterDeleteRequest_To_v1alpha1_BeforeClusterDeleteRequest(a.(*v1alpha2.BeforeClusterDeleteRequest), b.(*BeforeClusterDeleteRequest), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*BeforeClusterDeleteResponse)(nil), (*v1alpha2.BeforeClusterDeleteResponse)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_v1alpha1_BeforeClusterDeleteResponse_To_v1alpha2_BeforeClusterDeleteResponse(a.(*BeforeClusterDeleteResponse), b.(*v1alpha2.BeforeClusterDeleteResponse), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*v1alpha2.BeforeClusterDeleteResponse)(nil), (*BeforeClusterDeleteResponse)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_v1alpha2_BeforeClusterDeleteResponse_To_v1alpha1_BeforeClusterDeleteResponse(a.(*v1alpha2.BeforeClusterDeleteResponse), b.(*BeforeClusterDeleteResponse), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*BeforeClusterUpgradeRequest)(nil), (*v1alpha2.BeforeClusterUpgradeRequest)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_v1alpha1_BeforeClusterUpgradeRequest_To_v1alpha2_BeforeClusterUpgradeRequest(a.(*BeforeClusterUpgradeRequest), b.(*v1alpha2.BeforeClusterUpgradeRequest), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*v1alpha2.BeforeClusterUpgradeRequest)(nil), (*BeforeClusterUpgradeRequest)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_v1alpha2_BeforeClusterUpgradeRequest_To_v1alpha1_BeforeClusterUpgradeRequest(a.(*v1alpha2.BeforeClusterUpgradeRequest), b.(*BeforeClusterUpgradeRequest), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*BeforeClusterUpgradeResponse)(nil), (*v1alpha2.BeforeClusterUpgradeResponse)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_v1alpha1_BeforeClusterUpgradeResponse_To_v1alpha2_BeforeClusterUpgradeResponse(a.(*BeforeClusterUpgradeResponse), b.(*v1alpha2.BeforeClusterUpgradeResponse), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*v1alpha2.BeforeClusterUpgradeResponse)(nil), (*BeforeClusterUpgradeResponse)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_v1alpha2_BeforeClusterUpgradeResponse_To_v1alpha1_BeforeClusterUpgradeResponse(a.(*v1alpha2.BeforeClusterUpgradeResponse), b.(*BeforeClusterUpgradeResponse), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*CommonResponse)(nil), (*v1alpha2.CommonResponse)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_v1alpha1_CommonResponse_To_v1alpha2_CommonResponse(a.(*CommonResponse), b.(*v1alpha2.CommonResponse), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*v1alpha2.CommonResponse)(nil), (*CommonResponse)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_v1alpha2_CommonResponse_To_v1alpha1_CommonResponse(a.(*v1alpha2.CommonResponse), b.(*CommonResponse), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*CommonRetryResponse)(nil), (*v1alpha2.CommonRetryResponse)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_v1alpha1_CommonRetryResponse_To_v1alpha2_CommonRetryResponse(a.(*CommonRetryResponse), b.(*v1alpha2.CommonRetryResponse), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*v1alpha2.CommonRetryResponse)(nil), (*CommonRetryResponse)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_v1alpha2_CommonRetryResponse_To_v1alpha1_CommonRetryResponse(a.(*v1alpha2.CommonRetryResponse), b.(*CommonRetryResponse), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*DiscoveryRequest)(nil), (*v1alpha2.DiscoveryRequest)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_v1alpha1_DiscoveryRequest_To_v1alpha2_DiscoveryRequest(a.(*DiscoveryRequest), b.(*v1alpha2.DiscoveryRequest), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*v1alpha2.DiscoveryRequest)(nil), (*DiscoveryRequest)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_v1alpha2_DiscoveryRequest_To_v1alpha1_DiscoveryRequest(a.(*v1alpha2.DiscoveryRequest), b.(*DiscoveryRequest), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*DiscoveryResponse)(nil), (*v1alpha2.DiscoveryResponse)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_v1alpha1_DiscoveryResponse_To_v1alpha2_DiscoveryResponse(a.(*DiscoveryResponse), b.(*v1alpha2.DiscoveryResponse), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*v1alpha2.DiscoveryResponse)(nil), (*DiscoveryResponse)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_v1alpha2_DiscoveryResponse_To_v1alpha1_DiscoveryResponse(a.(*v1alpha2.DiscoveryResponse), b.(*DiscoveryResponse), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*ExtensionHandler)(nil), (*v1alpha2.ExtensionHandler)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_v1alpha1_ExtensionHandler_To_v1alpha2_ExtensionHandler(a.(*ExtensionHandler), b.(*v1alpha2.ExtensionHandler), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*v1alpha2.ExtensionHandler)(nil), (*ExtensionHandler)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_v1alpha2_ExtensionHandler_To_v1alpha1_ExtensionHandler(a.(*v1alpha2.ExtensionHandler), b.(*ExtensionHandler), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*GeneratePatchesRequest)(nil), (*v1alpha2.GeneratePatchesRequest)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_v1alpha1_GeneratePatchesRequest_To_v1alpha2_GeneratePatchesRequest(a.(*GeneratePatchesRequest), b.(*v1alpha2.GeneratePatchesRequest), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*v1alpha2.GeneratePatchesRequest)(nil), (*GeneratePatchesRequest)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_v1alpha2_GeneratePatchesRequest_To_v1alpha1_GeneratePatchesRequest(a.(*v1alpha2.GeneratePatchesRequest), b.(*GeneratePatchesRequest), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*GeneratePatchesRequestItem)(nil), (*v1alpha2.GeneratePatchesRequestItem)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_v1alpha1_GeneratePatchesRequestItem_To_v1alpha2_GeneratePatchesRequestItem(a.(*GeneratePatchesRequestItem), b.(*v1alpha2.GeneratePatchesRequestItem), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*v1alpha2.GeneratePatchesRequestItem)(nil), (*GeneratePatchesRequestItem)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_v1alpha2_GeneratePatchesRequestItem_To_v1alpha1_GeneratePatchesRequestItem(a.(*v1alpha2.GeneratePatchesRequestItem), b.(*GeneratePatchesRequestItem), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*GeneratePatchesResponse)(nil), (*v1alpha2.GeneratePatchesResponse)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_v1alpha1_GeneratePatchesResponse_To_v1alpha2_GeneratePatchesResponse(a.(*GeneratePatchesResponse), b.(*v1alpha2.GeneratePatchesResponse), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*v1alpha2.GeneratePatchesResponse)(nil), (*GeneratePatchesResponse)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_v1alpha2_GeneratePatchesResponse_To_v1alpha1_GeneratePatchesResponse(a.(*v1alpha2.GeneratePatchesResponse), b.(*GeneratePatchesResponse), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*GeneratePatchesResponseItem)(nil), (*v1alpha2.GeneratePatchesResponseItem)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_v1alpha1_GeneratePatchesResponseItem_To_v1alpha2_GeneratePatchesResponseItem(a.(*GeneratePatchesResponseItem), b.(*v1alpha2.GeneratePatchesResponseItem), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*v1alpha2.GeneratePatchesResponseItem)(nil), (*GeneratePatchesResponseItem)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_v1alpha2_GeneratePatchesResponseItem_To_v1alpha1_GeneratePatchesResponseItem(a.(*v1alpha2.GeneratePatchesResponseItem), b.(*GeneratePatchesResponseItem), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*GroupVersionHook)(nil), (*v1alpha2.GroupVersionHook)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_v1alpha1_GroupVersionHook_To_v1alpha2_GroupVersionHook(a.(*GroupVersionHook), b.(*v1alpha2.GroupVersionHook), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*v1alpha2.GroupVersionHook)(nil), (*GroupVersionHook)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_v1alpha2_GroupVersionHook_To_v1alpha1_GroupVersionHook(a.(*v1alpha2.GroupVersionHook), b.(*GroupVersionHook), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*HolderReference)(nil), (*v1alpha2.HolderReference)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_v1alpha1_HolderReference_To_v1alpha2_HolderReference(a.(*HolderReference), b.(*v1alpha2.HolderReference), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*v1alpha2.HolderReference)(nil), (*HolderReference)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_v1alpha2_HolderReference_To_v1alpha1_HolderReference(a.(*v1alpha2.HolderReference), b.(*HolderReference), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*ValidateTopologyRequest)(nil), (*v1alpha2.ValidateTopologyRequest)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_v1alpha1_ValidateTopologyRequest_To_v1alpha2_ValidateTopologyRequest(a.(*ValidateTopologyRequest), b.(*v1alpha2.ValidateTopologyRequest), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*v1alpha2.ValidateTopologyRequest)(nil), (*ValidateTopologyRequest)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_v1alpha2_ValidateTopologyRequest_To_v1alpha1_ValidateTopologyRequest(a.(*v1alpha2.ValidateTopologyRequest), b.(*ValidateTopologyRequest), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*ValidateTopologyRequestItem)(nil), (*v1alpha2.ValidateTopologyRequestItem)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_v1alpha1_ValidateTopologyRequestItem_To_v1alpha2_ValidateTopologyRequestItem(a.(*ValidateTopologyRequestItem), b.(*v1alpha2.ValidateTopologyRequestItem), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*v1alpha2.ValidateTopologyRequestItem)(nil), (*ValidateTopologyRequestItem)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_v1alpha2_ValidateTopologyRequestItem_To_v1alpha1_ValidateTopologyRequestItem(a.(*v1alpha2.ValidateTopologyRequestItem), b.(*ValidateTopologyRequestItem), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*ValidateTopologyResponse)(nil), (*v1alpha2.ValidateTopologyResponse)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_v1alpha1_ValidateTopologyResponse_To_v1alpha2_ValidateTopologyResponse(a.(*ValidateTopologyResponse), b.(*v1alpha2.ValidateTopologyResponse), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*v1alpha2.ValidateTopologyResponse)(nil), (*ValidateTopologyResponse)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_v1alpha2_ValidateTopologyResponse_To_v1alpha1_ValidateTopologyResponse(a.(*v1alpha2.ValidateTopologyResponse), b.(*ValidateTopologyResponse), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*Variable)(nil), (*v1alpha2.Variable)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_v1alpha1_Variable_To_v1alpha2_Variable(a.(*Variable), b.(*v1alpha2.Variable), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*v1alpha2.Variable)(nil), (*Variable)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_v1alpha2_Variable_To_v1alpha1_Variable(a.(*v1alpha2.Variable), b.(*Variable), scope)
	}); err != nil {
		return err
	}
	if err := s.AddConversionFunc((*v1alpha4.Cluster)(nil), (*v1beta1.Cluster)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_v1alpha4_Cluster_To_v1beta1_Cluster(a.(*v1alpha4.Cluster), b.(*v1beta1.Cluster), scope)
	}); err != nil {
		return err
	}
	if err := s.AddConversionFunc((*v1beta1.Cluster)(nil), (*v1alpha4.Cluster)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_v1beta1_Cluster_To_v1alpha4_Cluster(a.(*v1beta1.Cluster), b.(*v1alpha4.Cluster), scope)
	}); err != nil {
		return err
	}
	return nil
}

func autoConvert_v1alpha1_AfterClusterUpgradeRequest_To_v1alpha2_AfterClusterUpgradeRequest(in *AfterClusterUpgradeRequest, out *v1alpha2.AfterClusterUpgradeRequest, s conversion.Scope) error {
	if err := Convert_v1alpha4_Cluster_To_v1beta1_Cluster(&in.Cluster, &out.Cluster, s); err != nil {
		return err
	}
	out.KubernetesVersion = in.KubernetesVersion
	return nil
}

// Convert_v1alpha1_AfterClusterUpgradeRequest_To_v1alpha2_AfterClusterUpgradeRequest is an autogenerated conversion function.
func Convert_v1alpha1_AfterClusterUpgradeRequest_To_v1alpha2_AfterClusterUpgradeRequest(in *AfterClusterUpgradeRequest, out *v1alpha2.AfterClusterUpgradeRequest, s conversion.Scope) error {
	return autoConvert_v1alpha1_AfterClusterUpgradeRequest_To_v1alpha2_AfterClusterUpgradeRequest(in, out, s)
}

func autoConvert_v1alpha2_AfterClusterUpgradeRequest_To_v1alpha1_AfterClusterUpgradeRequest(in *v1alpha2.AfterClusterUpgradeRequest, out *AfterClusterUpgradeRequest, s conversion.Scope) error {
	if err := Convert_v1beta1_Cluster_To_v1alpha4_Cluster(&in.Cluster, &out.Cluster, s); err != nil {
		return err
	}
	out.KubernetesVersion = in.KubernetesVersion
	return nil
}

// Convert_v1alpha2_AfterClusterUpgradeRequest_To_v1alpha1_AfterClusterUpgradeRequest is an autogenerated conversion function.
func Convert_v1alpha2_AfterClusterUpgradeRequest_To_v1alpha1_AfterClusterUpgradeRequest(in *v1alpha2.AfterClusterUpgradeRequest, out *AfterClusterUpgradeRequest, s conversion.Scope) error {
	return autoConvert_v1alpha2_AfterClusterUpgradeRequest_To_v1alpha1_AfterClusterUpgradeRequest(in, out, s)
}

func autoConvert_v1alpha1_AfterClusterUpgradeResponse_To_v1alpha2_AfterClusterUpgradeResponse(in *AfterClusterUpgradeResponse, out *v1alpha2.AfterClusterUpgradeResponse, s conversion.Scope) error {
	if err := Convert_v1alpha1_CommonResponse_To_v1alpha2_CommonResponse(&in.CommonResponse, &out.CommonResponse, s); err != nil {
		return err
	}
	return nil
}

// Convert_v1alpha1_AfterClusterUpgradeResponse_To_v1alpha2_AfterClusterUpgradeResponse is an autogenerated conversion function.
func Convert_v1alpha1_AfterClusterUpgradeResponse_To_v1alpha2_AfterClusterUpgradeResponse(in *AfterClusterUpgradeResponse, out *v1alpha2.AfterClusterUpgradeResponse, s conversion.Scope) error {
	return autoConvert_v1alpha1_AfterClusterUpgradeResponse_To_v1alpha2_AfterClusterUpgradeResponse(in, out, s)
}

func autoConvert_v1alpha2_AfterClusterUpgradeResponse_To_v1alpha1_AfterClusterUpgradeResponse(in *v1alpha2.AfterClusterUpgradeResponse, out *AfterClusterUpgradeResponse, s conversion.Scope) error {
	if err := Convert_v1alpha2_CommonResponse_To_v1alpha1_CommonResponse(&in.CommonResponse, &out.CommonResponse, s); err != nil {
		return err
	}
	return nil
}

// Convert_v1alpha2_AfterClusterUpgradeResponse_To_v1alpha1_AfterClusterUpgradeResponse is an autogenerated conversion function.
func Convert_v1alpha2_AfterClusterUpgradeResponse_To_v1alpha1_AfterClusterUpgradeResponse(in *v1alpha2.AfterClusterUpgradeResponse, out *AfterClusterUpgradeResponse, s conversion.Scope) error {
	return autoConvert_v1alpha2_AfterClusterUpgradeResponse_To_v1alpha1_AfterClusterUpgradeResponse(in, out, s)
}

func autoConvert_v1alpha1_AfterControlPlaneInitializedRequest_To_v1alpha2_AfterControlPlaneInitializedRequest(in *AfterControlPlaneInitializedRequest, out *v1alpha2.AfterControlPlaneInitializedRequest, s conversion.Scope) error {
	if err := Convert_v1alpha4_Cluster_To_v1beta1_Cluster(&in.Cluster, &out.Cluster, s); err != nil {
		return err
	}
	return nil
}

// Convert_v1alpha1_AfterControlPlaneInitializedRequest_To_v1alpha2_AfterControlPlaneInitializedRequest is an autogenerated conversion function.
func Convert_v1alpha1_AfterControlPlaneInitializedRequest_To_v1alpha2_AfterControlPlaneInitializedRequest(in *AfterControlPlaneInitializedRequest, out *v1alpha2.AfterControlPlaneInitializedRequest, s conversion.Scope) error {
	return autoConvert_v1alpha1_AfterControlPlaneInitializedRequest_To_v1alpha2_AfterControlPlaneInitializedRequest(in, out, s)
}

func autoConvert_v1alpha2_AfterControlPlaneInitializedRequest_To_v1alpha1_AfterControlPlaneInitializedRequest(in *v1alpha2.AfterControlPlaneInitializedRequest, out *AfterControlPlaneInitializedRequest, s conversion.Scope) error {
	if err := Convert_v1beta1_Cluster_To_v1alpha4_Cluster(&in.Cluster, &out.Cluster, s); err != nil {
		return err
	}
	return nil
}

// Convert_v1alpha2_AfterControlPlaneInitializedRequest_To_v1alpha1_AfterControlPlaneInitializedRequest is an autogenerated conversion function.
func Convert_v1alpha2_AfterControlPlaneInitializedRequest_To_v1alpha1_AfterControlPlaneInitializedRequest(in *v1alpha2.AfterControlPlaneInitializedRequest, out *AfterControlPlaneInitializedRequest, s conversion.Scope) error {
	return autoConvert_v1alpha2_AfterControlPlaneInitializedRequest_To_v1alpha1_AfterControlPlaneInitializedRequest(in, out, s)
}

func autoConvert_v1alpha1_AfterControlPlaneInitializedResponse_To_v1alpha2_AfterControlPlaneInitializedResponse(in *AfterControlPlaneInitializedResponse, out *v1alpha2.AfterControlPlaneInitializedResponse, s conversion.Scope) error {
	if err := Convert_v1alpha1_CommonResponse_To_v1alpha2_CommonResponse(&in.CommonResponse, &out.CommonResponse, s); err != nil {
		return err
	}
	return nil
}

// Convert_v1alpha1_AfterControlPlaneInitializedResponse_To_v1alpha2_AfterControlPlaneInitializedResponse is an autogenerated conversion function.
func Convert_v1alpha1_AfterControlPlaneInitializedResponse_To_v1alpha2_AfterControlPlaneInitializedResponse(in *AfterControlPlaneInitializedResponse, out *v1alpha2.AfterControlPlaneInitializedResponse, s conversion.Scope) error {
	return autoConvert_v1alpha1_AfterControlPlaneInitializedResponse_To_v1alpha2_AfterControlPlaneInitializedResponse(in, out, s)
}

func autoConvert_v1alpha2_AfterControlPlaneInitializedResponse_To_v1alpha1_AfterControlPlaneInitializedResponse(in *v1alpha2.AfterControlPlaneInitializedResponse, out *AfterControlPlaneInitializedResponse, s conversion.Scope) error {
	if err := Convert_v1alpha2_CommonResponse_To_v1alpha1_CommonResponse(&in.CommonResponse, &out.CommonResponse, s); err != nil {
		return err
	}
	return nil
}

// Convert_v1alpha2_AfterControlPlaneInitializedResponse_To_v1alpha1_AfterControlPlaneInitializedResponse is an autogenerated conversion function.
func Convert_v1alpha2_AfterControlPlaneInitializedResponse_To_v1alpha1_AfterControlPlaneInitializedResponse(in *v1alpha2.AfterControlPlaneInitializedResponse, out *AfterControlPlaneInitializedResponse, s conversion.Scope) error {
	return autoConvert_v1alpha2_AfterControlPlaneInitializedResponse_To_v1alpha1_AfterControlPlaneInitializedResponse(in, out, s)
}

func autoConvert_v1alpha1_AfterControlPlaneUpgradeRequest_To_v1alpha2_AfterControlPlaneUpgradeRequest(in *AfterControlPlaneUpgradeRequest, out *v1alpha2.AfterControlPlaneUpgradeRequest, s conversion.Scope) error {
	if err := Convert_v1alpha4_Cluster_To_v1beta1_Cluster(&in.Cluster, &out.Cluster, s); err != nil {
		return err
	}
	out.KubernetesVersion = in.KubernetesVersion
	return nil
}

// Convert_v1alpha1_AfterControlPlaneUpgradeRequest_To_v1alpha2_AfterControlPlaneUpgradeRequest is an autogenerated conversion function.
func Convert_v1alpha1_AfterControlPlaneUpgradeRequest_To_v1alpha2_AfterControlPlaneUpgradeRequest(in *AfterControlPlaneUpgradeRequest, out *v1alpha2.AfterControlPlaneUpgradeRequest, s conversion.Scope) error {
	return autoConvert_v1alpha1_AfterControlPlaneUpgradeRequest_To_v1alpha2_AfterControlPlaneUpgradeRequest(in, out, s)
}

func autoConvert_v1alpha2_AfterControlPlaneUpgradeRequest_To_v1alpha1_AfterControlPlaneUpgradeRequest(in *v1alpha2.AfterControlPlaneUpgradeRequest, out *AfterControlPlaneUpgradeRequest, s conversion.Scope) error {
	if err := Convert_v1beta1_Cluster_To_v1alpha4_Cluster(&in.Cluster, &out.Cluster, s); err != nil {
		return err
	}
	out.KubernetesVersion = in.KubernetesVersion
	return nil
}

// Convert_v1alpha2_AfterControlPlaneUpgradeRequest_To_v1alpha1_AfterControlPlaneUpgradeRequest is an autogenerated conversion function.
func Convert_v1alpha2_AfterControlPlaneUpgradeRequest_To_v1alpha1_AfterControlPlaneUpgradeRequest(in *v1alpha2.AfterControlPlaneUpgradeRequest, out *AfterControlPlaneUpgradeRequest, s conversion.Scope) error {
	return autoConvert_v1alpha2_AfterControlPlaneUpgradeRequest_To_v1alpha1_AfterControlPlaneUpgradeRequest(in, out, s)
}

func autoConvert_v1alpha1_AfterControlPlaneUpgradeResponse_To_v1alpha2_AfterControlPlaneUpgradeResponse(in *AfterControlPlaneUpgradeResponse, out *v1alpha2.AfterControlPlaneUpgradeResponse, s conversion.Scope) error {
	if err := Convert_v1alpha1_CommonRetryResponse_To_v1alpha2_CommonRetryResponse(&in.CommonRetryResponse, &out.CommonRetryResponse, s); err != nil {
		return err
	}
	return nil
}

// Convert_v1alpha1_AfterControlPlaneUpgradeResponse_To_v1alpha2_AfterControlPlaneUpgradeResponse is an autogenerated conversion function.
func Convert_v1alpha1_AfterControlPlaneUpgradeResponse_To_v1alpha2_AfterControlPlaneUpgradeResponse(in *AfterControlPlaneUpgradeResponse, out *v1alpha2.AfterControlPlaneUpgradeResponse, s conversion.Scope) error {
	return autoConvert_v1alpha1_AfterControlPlaneUpgradeResponse_To_v1alpha2_AfterControlPlaneUpgradeResponse(in, out, s)
}

func autoConvert_v1alpha2_AfterControlPlaneUpgradeResponse_To_v1alpha1_AfterControlPlaneUpgradeResponse(in *v1alpha2.AfterControlPlaneUpgradeResponse, out *AfterControlPlaneUpgradeResponse, s conversion.Scope) error {
	if err := Convert_v1alpha2_CommonRetryResponse_To_v1alpha1_CommonRetryResponse(&in.CommonRetryResponse, &out.CommonRetryResponse, s); err != nil {
		return err
	}
	return nil
}

// Convert_v1alpha2_AfterControlPlaneUpgradeResponse_To_v1alpha1_AfterControlPlaneUpgradeResponse is an autogenerated conversion function.
func Convert_v1alpha2_AfterControlPlaneUpgradeResponse_To_v1alpha1_AfterControlPlaneUpgradeResponse(in *v1alpha2.AfterControlPlaneUpgradeResponse, out *AfterControlPlaneUpgradeResponse, s conversion.Scope) error {
	return autoConvert_v1alpha2_AfterControlPlaneUpgradeResponse_To_v1alpha1_AfterControlPlaneUpgradeResponse(in, out, s)
}

func autoConvert_v1alpha1_BeforeClusterCreateRequest_To_v1alpha2_BeforeClusterCreateRequest(in *BeforeClusterCreateRequest, out *v1alpha2.BeforeClusterCreateRequest, s conversion.Scope) error {
	if err := Convert_v1alpha4_Cluster_To_v1beta1_Cluster(&in.Cluster, &out.Cluster, s); err != nil {
		return err
	}
	return nil
}

// Convert_v1alpha1_BeforeClusterCreateRequest_To_v1alpha2_BeforeClusterCreateRequest is an autogenerated conversion function.
func Convert_v1alpha1_BeforeClusterCreateRequest_To_v1alpha2_BeforeClusterCreateRequest(in *BeforeClusterCreateRequest, out *v1alpha2.BeforeClusterCreateRequest, s conversion.Scope) error {
	return autoConvert_v1alpha1_BeforeClusterCreateRequest_To_v1alpha2_BeforeClusterCreateRequest(in, out, s)
}

func autoConvert_v1alpha2_BeforeClusterCreateRequest_To_v1alpha1_BeforeClusterCreateRequest(in *v1alpha2.BeforeClusterCreateRequest, out *BeforeClusterCreateRequest, s conversion.Scope) error {
	if err := Convert_v1beta1_Cluster_To_v1alpha4_Cluster(&in.Cluster, &out.Cluster, s); err != nil {
		return err
	}
	return nil
}

// Convert_v1alpha2_BeforeClusterCreateRequest_To_v1alpha1_BeforeClusterCreateRequest is an autogenerated conversion function.
func Convert_v1alpha2_BeforeClusterCreateRequest_To_v1alpha1_BeforeClusterCreateRequest(in *v1alpha2.BeforeClusterCreateRequest, out *BeforeClusterCreateRequest, s conversion.Scope) error {
	return autoConvert_v1alpha2_BeforeClusterCreateRequest_To_v1alpha1_BeforeClusterCreateRequest(in, out, s)
}

func autoConvert_v1alpha1_BeforeClusterCreateResponse_To_v1alpha2_BeforeClusterCreateResponse(in *BeforeClusterCreateResponse, out *v1alpha2.BeforeClusterCreateResponse, s conversion.Scope) error {
	if err := Convert_v1alpha1_CommonRetryResponse_To_v1alpha2_CommonRetryResponse(&in.CommonRetryResponse, &out.CommonRetryResponse, s); err != nil {
		return err
	}
	return nil
}

// Convert_v1alpha1_BeforeClusterCreateResponse_To_v1alpha2_BeforeClusterCreateResponse is an autogenerated conversion function.
func Convert_v1alpha1_BeforeClusterCreateResponse_To_v1alpha2_BeforeClusterCreateResponse(in *BeforeClusterCreateResponse, out *v1alpha2.BeforeClusterCreateResponse, s conversion.Scope) error {
	return autoConvert_v1alpha1_BeforeClusterCreateResponse_To_v1alpha2_BeforeClusterCreateResponse(in, out, s)
}

func autoConvert_v1alpha2_BeforeClusterCreateResponse_To_v1alpha1_BeforeClusterCreateResponse(in *v1alpha2.BeforeClusterCreateResponse, out *BeforeClusterCreateResponse, s conversion.Scope) error {
	if err := Convert_v1alpha2_CommonRetryResponse_To_v1alpha1_CommonRetryResponse(&in.CommonRetryResponse, &out.CommonRetryResponse, s); err != nil {
		return err
	}
	return nil
}

// Convert_v1alpha2_BeforeClusterCreateResponse_To_v1alpha1_BeforeClusterCreateResponse is an autogenerated conversion function.
func Convert_v1alpha2_BeforeClusterCreateResponse_To_v1alpha1_BeforeClusterCreateResponse(in *v1alpha2.BeforeClusterCreateResponse, out *BeforeClusterCreateResponse, s conversion.Scope) error {
	return autoConvert_v1alpha2_BeforeClusterCreateResponse_To_v1alpha1_BeforeClusterCreateResponse(in, out, s)
}

func autoConvert_v1alpha1_BeforeClusterDeleteRequest_To_v1alpha2_BeforeClusterDeleteRequest(in *BeforeClusterDeleteRequest, out *v1alpha2.BeforeClusterDeleteRequest, s conversion.Scope) error {
	if err := Convert_v1alpha4_Cluster_To_v1beta1_Cluster(&in.Cluster, &out.Cluster, s); err != nil {
		return err
	}
	return nil
}

// Convert_v1alpha1_BeforeClusterDeleteRequest_To_v1alpha2_BeforeClusterDeleteRequest is an autogenerated conversion function.
func Convert_v1alpha1_BeforeClusterDeleteRequest_To_v1alpha2_BeforeClusterDeleteRequest(in *BeforeClusterDeleteRequest, out *v1alpha2.BeforeClusterDeleteRequest, s conversion.Scope) error {
	return autoConvert_v1alpha1_BeforeClusterDeleteRequest_To_v1alpha2_BeforeClusterDeleteRequest(in, out, s)
}

func autoConvert_v1alpha2_BeforeClusterDeleteRequest_To_v1alpha1_BeforeClusterDeleteRequest(in *v1alpha2.BeforeClusterDeleteRequest, out *BeforeClusterDeleteRequest, s conversion.Scope) error {
	if err := Convert_v1beta1_Cluster_To_v1alpha4_Cluster(&in.Cluster, &out.Cluster, s); err != nil {
		return err
	}
	return nil
}

// Convert_v1alpha2_BeforeClusterDeleteRequest_To_v1alpha1_BeforeClusterDeleteRequest is an autogenerated conversion function.
func Convert_v1alpha2_BeforeClusterDeleteRequest_To_v1alpha1_BeforeClusterDeleteRequest(in *v1alpha2.BeforeClusterDeleteRequest, out *BeforeClusterDeleteRequest, s conversion.Scope) error {
	return autoConvert_v1alpha2_BeforeClusterDeleteRequest_To_v1alpha1_BeforeClusterDeleteRequest(in, out, s)
}

func autoConvert_v1alpha1_BeforeClusterDeleteResponse_To_v1alpha2_BeforeClusterDeleteResponse(in *BeforeClusterDeleteResponse, out *v1alpha2.BeforeClusterDeleteResponse, s conversion.Scope) error {
	if err := Convert_v1alpha1_CommonRetryResponse_To_v1alpha2_CommonRetryResponse(&in.CommonRetryResponse, &out.CommonRetryResponse, s); err != nil {
		return err
	}
	return nil
}

// Convert_v1alpha1_BeforeClusterDeleteResponse_To_v1alpha2_BeforeClusterDeleteResponse is an autogenerated conversion function.
func Convert_v1alpha1_BeforeClusterDeleteResponse_To_v1alpha2_BeforeClusterDeleteResponse(in *BeforeClusterDeleteResponse, out *v1alpha2.BeforeClusterDeleteResponse, s conversion.Scope) error {
	return autoConvert_v1alpha1_BeforeClusterDeleteResponse_To_v1alpha2_BeforeClusterDeleteResponse(in, out, s)
}

func autoConvert_v1alpha2_BeforeClusterDeleteResponse_To_v1alpha1_BeforeClusterDeleteResponse(in *v1alpha2.BeforeClusterDeleteResponse, out *BeforeClusterDeleteResponse, s conversion.Scope) error {
	if err := Convert_v1alpha2_CommonRetryResponse_To_v1alpha1_CommonRetryResponse(&in.CommonRetryResponse, &out.CommonRetryResponse, s); err != nil {
		return err
	}
	return nil
}

// Convert_v1alpha2_BeforeClusterDeleteResponse_To_v1alpha1_BeforeClusterDeleteResponse is an autogenerated conversion function.
func Convert_v1alpha2_BeforeClusterDeleteResponse_To_v1alpha1_BeforeClusterDeleteResponse(in *v1alpha2.BeforeClusterDeleteResponse, out *BeforeClusterDeleteResponse, s conversion.Scope) error {
	return autoConvert_v1alpha2_BeforeClusterDeleteResponse_To_v1alpha1_BeforeClusterDeleteResponse(in, out, s)
}

func autoConvert_v1alpha1_BeforeClusterUpgradeRequest_To_v1alpha2_BeforeClusterUpgradeRequest(in *BeforeClusterUpgradeRequest, out *v1alpha2.BeforeClusterUpgradeRequest, s conversion.Scope) error {
	if err := Convert_v1alpha4_Cluster_To_v1beta1_Cluster(&in.Cluster, &out.Cluster, s); err != nil {
		return err
	}
	out.FromKubernetesVersion = in.FromKubernetesVersion
	out.ToKubernetesVersion = in.ToKubernetesVersion
	return nil
}

// Convert_v1alpha1_BeforeClusterUpgradeRequest_To_v1alpha2_BeforeClusterUpgradeRequest is an autogenerated conversion function.
func Convert_v1alpha1_BeforeClusterUpgradeRequest_To_v1alpha2_BeforeClusterUpgradeRequest(in *BeforeClusterUpgradeRequest, out *v1alpha2.BeforeClusterUpgradeRequest, s conversion.Scope) error {
	return autoConvert_v1alpha1_BeforeClusterUpgradeRequest_To_v1alpha2_BeforeClusterUpgradeRequest(in, out, s)
}

func autoConvert_v1alpha2_BeforeClusterUpgradeRequest_To_v1alpha1_BeforeClusterUpgradeRequest(in *v1alpha2.BeforeClusterUpgradeRequest, out *BeforeClusterUpgradeRequest, s conversion.Scope) error {
	if err := Convert_v1beta1_Cluster_To_v1alpha4_Cluster(&in.Cluster, &out.Cluster, s); err != nil {
		return err
	}
	out.FromKubernetesVersion = in.FromKubernetesVersion
	out.ToKubernetesVersion = in.ToKubernetesVersion
	return nil
}

// Convert_v1alpha2_BeforeClusterUpgradeRequest_To_v1alpha1_BeforeClusterUpgradeRequest is an autogenerated conversion function.
func Convert_v1alpha2_BeforeClusterUpgradeRequest_To_v1alpha1_BeforeClusterUpgradeRequest(in *v1alpha2.BeforeClusterUpgradeRequest, out *BeforeClusterUpgradeRequest, s conversion.Scope) error {
	return autoConvert_v1alpha2_BeforeClusterUpgradeRequest_To_v1alpha1_BeforeClusterUpgradeRequest(in, out, s)
}

func autoConvert_v1alpha1_BeforeClusterUpgradeResponse_To_v1alpha2_BeforeClusterUpgradeResponse(in *BeforeClusterUpgradeResponse, out *v1alpha2.BeforeClusterUpgradeResponse, s conversion.Scope) error {
	if err := Convert_v1alpha1_CommonRetryResponse_To_v1alpha2_CommonRetryResponse(&in.CommonRetryResponse, &out.CommonRetryResponse, s); err != nil {
		return err
	}
	return nil
}

// Convert_v1alpha1_BeforeClusterUpgradeResponse_To_v1alpha2_BeforeClusterUpgradeResponse is an autogenerated conversion function.
func Convert_v1alpha1_BeforeClusterUpgradeResponse_To_v1alpha2_BeforeClusterUpgradeResponse(in *BeforeClusterUpgradeResponse, out *v1alpha2.BeforeClusterUpgradeResponse, s conversion.Scope) error {
	return autoConvert_v1alpha1_BeforeClusterUpgradeResponse_To_v1alpha2_BeforeClusterUpgradeResponse(in, out, s)
}

func autoConvert_v1alpha2_BeforeClusterUpgradeResponse_To_v1alpha1_BeforeClusterUpgradeResponse(in *v1alpha2.BeforeClusterUpgradeResponse, out *BeforeClusterUpgradeResponse, s conversion.Scope) error {
	if err := Convert_v1alpha2_CommonRetryResponse_To_v1alpha1_CommonRetryResponse(&in.CommonRetryResponse, &out.CommonRetryResponse, s); err != nil {
		return err
	}
	return nil
}

// Convert_v1alpha2_BeforeClusterUpgradeResponse_To_v1alpha1_BeforeClusterUpgradeResponse is an autogenerated conversion function.
func Convert_v1alpha2_BeforeClusterUpgradeResponse_To_v1alpha1_BeforeClusterUpgradeResponse(in *v1alpha2.BeforeClusterUpgradeResponse, out *BeforeClusterUpgradeResponse, s conversion.Scope) error {
	return autoConvert_v1alpha2_BeforeClusterUpgradeResponse_To_v1alpha1_BeforeClusterUpgradeResponse(in, out, s)
}

func autoConvert_v1alpha1_CommonResponse_To_v1alpha2_CommonResponse(in *CommonResponse, out *v1alpha2.CommonResponse, s conversion.Scope) error {
	out.Status = v1alpha2.ResponseStatus(in.Status)
	out.Message = in.Message
	return nil
}

// Convert_v1alpha1_CommonResponse_To_v1alpha2_CommonResponse is an autogenerated conversion function.
func Convert_v1alpha1_CommonResponse_To_v1alpha2_CommonResponse(in *CommonResponse, out *v1alpha2.CommonResponse, s conversion.Scope) error {
	return autoConvert_v1alpha1_CommonResponse_To_v1alpha2_CommonResponse(in, out, s)
}

func autoConvert_v1alpha2_CommonResponse_To_v1alpha1_CommonResponse(in *v1alpha2.CommonResponse, out *CommonResponse, s conversion.Scope) error {
	out.Status = ResponseStatus(in.Status)
	out.Message = in.Message
	return nil
}

// Convert_v1alpha2_CommonResponse_To_v1alpha1_CommonResponse is an autogenerated conversion function.
func Convert_v1alpha2_CommonResponse_To_v1alpha1_CommonResponse(in *v1alpha2.CommonResponse, out *CommonResponse, s conversion.Scope) error {
	return autoConvert_v1alpha2_CommonResponse_To_v1alpha1_CommonResponse(in, out, s)
}

func autoConvert_v1alpha1_CommonRetryResponse_To_v1alpha2_CommonRetryResponse(in *CommonRetryResponse, out *v1alpha2.CommonRetryResponse, s conversion.Scope) error {
	if err := Convert_v1alpha1_CommonResponse_To_v1alpha2_CommonResponse(&in.CommonResponse, &out.CommonResponse, s); err != nil {
		return err
	}
	out.RetryAfterSeconds = in.RetryAfterSeconds
	return nil
}

// Convert_v1alpha1_CommonRetryResponse_To_v1alpha2_CommonRetryResponse is an autogenerated conversion function.
func Convert_v1alpha1_CommonRetryResponse_To_v1alpha2_CommonRetryResponse(in *CommonRetryResponse, out *v1alpha2.CommonRetryResponse, s conversion.Scope) error {
	return autoConvert_v1alpha1_CommonRetryResponse_To_v1alpha2_CommonRetryResponse(in, out, s)
}

func autoConvert_v1alpha2_CommonRetryResponse_To_v1alpha1_CommonRetryResponse(in *v1alpha2.CommonRetryResponse, out *CommonRetryResponse, s conversion.Scope) error {
	if err := Convert_v1alpha2_CommonResponse_To_v1alpha1_CommonResponse(&in.CommonResponse, &out.CommonResponse, s); err != nil {
		return err
	}
	out.RetryAfterSeconds = in.RetryAfterSeconds
	return nil
}

// Convert_v1alpha2_CommonRetryResponse_To_v1alpha1_CommonRetryResponse is an autogenerated conversion function.
func Convert_v1alpha2_CommonRetryResponse_To_v1alpha1_CommonRetryResponse(in *v1alpha2.CommonRetryResponse, out *CommonRetryResponse, s conversion.Scope) error {
	return autoConvert_v1alpha2_CommonRetryResponse_To_v1alpha1_CommonRetryResponse(in, out, s)
}

func autoConvert_v1alpha1_DiscoveryRequest_To_v1alpha2_DiscoveryRequest(in *DiscoveryRequest, out *v1alpha2.DiscoveryRequest, s conversion.Scope) error {
	return nil
}

// Convert_v1alpha1_DiscoveryRequest_To_v1alpha2_DiscoveryRequest is an autogenerated conversion function.
func Convert_v1alpha1_DiscoveryRequest_To_v1alpha2_DiscoveryRequest(in *DiscoveryRequest, out *v1alpha2.DiscoveryRequest, s conversion.Scope) error {
	return autoConvert_v1alpha1_DiscoveryRequest_To_v1alpha2_DiscoveryRequest(in, out, s)
}

func autoConvert_v1alpha2_DiscoveryRequest_To_v1alpha1_DiscoveryRequest(in *v1alpha2.DiscoveryRequest, out *DiscoveryRequest, s conversion.Scope) error {
	return nil
}

// Convert_v1alpha2_DiscoveryRequest_To_v1alpha1_DiscoveryRequest is an autogenerated conversion function.
func Convert_v1alpha2_DiscoveryRequest_To_v1alpha1_DiscoveryRequest(in *v1alpha2.DiscoveryRequest, out *DiscoveryRequest, s conversion.Scope) error {
	return autoConvert_v1alpha2_DiscoveryRequest_To_v1alpha1_DiscoveryRequest(in, out, s)
}

func autoConvert_v1alpha1_DiscoveryResponse_To_v1alpha2_DiscoveryResponse(in *DiscoveryResponse, out *v1alpha2.DiscoveryResponse, s conversion.Scope) error {
	if err := Convert_v1alpha1_CommonResponse_To_v1alpha2_CommonResponse(&in.CommonResponse, &out.CommonResponse, s); err != nil {
		return err
	}
	out.Handlers = *(*[]v1alpha2.ExtensionHandler)(unsafe.Pointer(&in.Handlers))
	return nil
}

// Convert_v1alpha1_DiscoveryResponse_To_v1alpha2_DiscoveryResponse is an autogenerated conversion function.
func Convert_v1alpha1_DiscoveryResponse_To_v1alpha2_DiscoveryResponse(in *DiscoveryResponse, out *v1alpha2.DiscoveryResponse, s conversion.Scope) error {
	return autoConvert_v1alpha1_DiscoveryResponse_To_v1alpha2_DiscoveryResponse(in, out, s)
}

func autoConvert_v1alpha2_DiscoveryResponse_To_v1alpha1_DiscoveryResponse(in *v1alpha2.DiscoveryResponse, out *DiscoveryResponse, s conversion.Scope) error {
	if err := Convert_v1alpha2_CommonResponse_To_v1alpha1_CommonResponse(&in.CommonResponse, &out.CommonResponse, s); err != nil {
		return err
	}
	out.Handlers = *(*[]ExtensionHandler)(unsafe.Pointer(&in.Handlers))
	return nil
}

// Convert_v1alpha2_DiscoveryResponse_To_v1alpha1_DiscoveryResponse is an autogenerated conversion function.
func Convert_v1alpha2_DiscoveryResponse_To_v1alpha1_DiscoveryResponse(in *v1alpha2.DiscoveryResponse, out *DiscoveryResponse, s conversion.Scope) error {
	return autoConvert_v1alpha2_DiscoveryResponse_To_v1alpha1_DiscoveryResponse(in, out, s)
}

func autoConvert_v1alpha1_ExtensionHandler_To_v1alpha2_ExtensionHandler(in *ExtensionHandler, out *v1alpha2.ExtensionHandler, s conversion.Scope) error {
	out.Name = in.Name
	if err := Convert_v1alpha1_GroupVersionHook_To_v1alpha2_GroupVersionHook(&in.RequestHook, &out.RequestHook, s); err != nil {
		return err
	}
	out.TimeoutSeconds = (*int32)(unsafe.Pointer(in.TimeoutSeconds))
	out.FailurePolicy = (*v1alpha2.FailurePolicy)(unsafe.Pointer(in.FailurePolicy))
	return nil
}

// Convert_v1alpha1_ExtensionHandler_To_v1alpha2_ExtensionHandler is an autogenerated conversion function.
func Convert_v1alpha1_ExtensionHandler_To_v1alpha2_ExtensionHandler(in *ExtensionHandler, out *v1alpha2.ExtensionHandler, s conversion.Scope) error {
	return autoConvert_v1alpha1_ExtensionHandler_To_v1alpha2_ExtensionHandler(in, out, s)
}

func autoConvert_v1alpha2_ExtensionHandler_To_v1alpha1_ExtensionHandler(in *v1alpha2.ExtensionHandler, out *ExtensionHandler, s conversion.Scope) error {
	out.Name = in.Name
	if err := Convert_v1alpha2_GroupVersionHook_To_v1alpha1_GroupVersionHook(&in.RequestHook, &out.RequestHook, s); err != nil {
		return err
	}
	out.TimeoutSeconds = (*int32)(unsafe.Pointer(in.TimeoutSeconds))
	out.FailurePolicy = (*FailurePolicy)(unsafe.Pointer(in.FailurePolicy))
	return nil
}

// Convert_v1alpha2_ExtensionHandler_To_v1alpha1_ExtensionHandler is an autogenerated conversion function.
func Convert_v1alpha2_ExtensionHandler_To_v1alpha1_ExtensionHandler(in *v1alpha2.ExtensionHandler, out *ExtensionHandler, s conversion.Scope) error {
	return autoConvert_v1alpha2_ExtensionHandler_To_v1alpha1_ExtensionHandler(in, out, s)
}

func autoConvert_v1alpha1_GeneratePatchesRequest_To_v1alpha2_GeneratePatchesRequest(in *GeneratePatchesRequest, out *v1alpha2.GeneratePatchesRequest, s conversion.Scope) error {
	out.Variables = *(*[]v1alpha2.Variable)(unsafe.Pointer(&in.Variables))
	out.Items = *(*[]v1alpha2.GeneratePatchesRequestItem)(unsafe.Pointer(&in.Items))
	return nil
}

// Convert_v1alpha1_GeneratePatchesRequest_To_v1alpha2_GeneratePatchesRequest is an autogenerated conversion function.
func Convert_v1alpha1_GeneratePatchesRequest_To_v1alpha2_GeneratePatchesRequest(in *GeneratePatchesRequest, out *v1alpha2.GeneratePatchesRequest, s conversion.Scope) error {
	return autoConvert_v1alpha1_GeneratePatchesRequest_To_v1alpha2_GeneratePatchesRequest(in, out, s)
}

func autoConvert_v1alpha2_GeneratePatchesRequest_To_v1alpha1_GeneratePatchesRequest(in *v1alpha2.GeneratePatchesRequest, out *GeneratePatchesRequest, s conversion.Scope) error {
	out.Variables = *(*[]Variable)(unsafe.Pointer(&in.Variables))
	out.Items = *(*[]GeneratePatchesRequestItem)(unsafe.Pointer(&in.Items))
	return nil
}

// Convert_v1alpha2_GeneratePatchesRequest_To_v1alpha1_GeneratePatchesRequest is an autogenerated conversion function.
func Convert_v1alpha2_GeneratePatchesRequest_To_v1alpha1_GeneratePatchesRequest(in *v1alpha2.GeneratePatchesRequest, out *GeneratePatchesRequest, s conversion.Scope) error {
	return autoConvert_v1alpha2_GeneratePatchesRequest_To_v1alpha1_GeneratePatchesRequest(in, out, s)
}

func autoConvert_v1alpha1_GeneratePatchesRequestItem_To_v1alpha2_GeneratePatchesRequestItem(in *GeneratePatchesRequestItem, out *v1alpha2.GeneratePatchesRequestItem, s conversion.Scope) error {
	out.UID = types.UID(in.UID)
	if err := Convert_v1alpha1_HolderReference_To_v1alpha2_HolderReference(&in.HolderReference, &out.HolderReference, s); err != nil {
		return err
	}
	out.Object = in.Object
	out.Variables = *(*[]v1alpha2.Variable)(unsafe.Pointer(&in.Variables))
	return nil
}

// Convert_v1alpha1_GeneratePatchesRequestItem_To_v1alpha2_GeneratePatchesRequestItem is an autogenerated conversion function.
func Convert_v1alpha1_GeneratePatchesRequestItem_To_v1alpha2_GeneratePatchesRequestItem(in *GeneratePatchesRequestItem, out *v1alpha2.GeneratePatchesRequestItem, s conversion.Scope) error {
	return autoConvert_v1alpha1_GeneratePatchesRequestItem_To_v1alpha2_GeneratePatchesRequestItem(in, out, s)
}

func autoConvert_v1alpha2_GeneratePatchesRequestItem_To_v1alpha1_GeneratePatchesRequestItem(in *v1alpha2.GeneratePatchesRequestItem, out *GeneratePatchesRequestItem, s conversion.Scope) error {
	out.UID = types.UID(in.UID)
	if err := Convert_v1alpha2_HolderReference_To_v1alpha1_HolderReference(&in.HolderReference, &out.HolderReference, s); err != nil {
		return err
	}
	out.Object = in.Object
	out.Variables = *(*[]Variable)(unsafe.Pointer(&in.Variables))
	return nil
}

// Convert_v1alpha2_GeneratePatchesRequestItem_To_v1alpha1_GeneratePatchesRequestItem is an autogenerated conversion function.
func Convert_v1alpha2_GeneratePatchesRequestItem_To_v1alpha1_GeneratePatchesRequestItem(in *v1alpha2.GeneratePatchesRequestItem, out *GeneratePatchesRequestItem, s conversion.Scope) error {
	return autoConvert_v1alpha2_GeneratePatchesRequestItem_To_v1alpha1_GeneratePatchesRequestItem(in, out, s)
}

func autoConvert_v1alpha1_GeneratePatchesResponse_To_v1alpha2_GeneratePatchesResponse(in *GeneratePatchesResponse, out *v1alpha2.GeneratePatchesResponse, s conversion.Scope) error {
	if err := Convert_v1alpha1_CommonResponse_To_v1alpha2_CommonResponse(&in.CommonResponse, &out.CommonResponse, s); err != nil {
		return err
	}
	out.Items = *(*[]v1alpha2.GeneratePatchesResponseItem)(unsafe.Pointer(&in.Items))
	return nil
}

// Convert_v1alpha1_GeneratePatchesResponse_To_v1alpha2_GeneratePatchesResponse is an autogenerated conversion function.
func Convert_v1alpha1_GeneratePatchesResponse_To_v1alpha2_GeneratePatchesResponse(in *GeneratePatchesResponse, out *v1alpha2.GeneratePatchesResponse, s conversion.Scope) error {
	return autoConvert_v1alpha1_GeneratePatchesResponse_To_v1alpha2_GeneratePatchesResponse(in, out, s)
}

func autoConvert_v1alpha2_GeneratePatchesResponse_To_v1alpha1_GeneratePatchesResponse(in *v1alpha2.GeneratePatchesResponse, out *GeneratePatchesResponse, s conversion.Scope) error {
	if err := Convert_v1alpha2_CommonResponse_To_v1alpha1_CommonResponse(&in.CommonResponse, &out.CommonResponse, s); err != nil {
		return err
	}
	out.Items = *(*[]GeneratePatchesResponseItem)(unsafe.Pointer(&in.Items))
	return nil
}

// Convert_v1alpha2_GeneratePatchesResponse_To_v1alpha1_GeneratePatchesResponse is an autogenerated conversion function.
func Convert_v1alpha2_GeneratePatchesResponse_To_v1alpha1_GeneratePatchesResponse(in *v1alpha2.GeneratePatchesResponse, out *GeneratePatchesResponse, s conversion.Scope) error {
	return autoConvert_v1alpha2_GeneratePatchesResponse_To_v1alpha1_GeneratePatchesResponse(in, out, s)
}

func autoConvert_v1alpha1_GeneratePatchesResponseItem_To_v1alpha2_GeneratePatchesResponseItem(in *GeneratePatchesResponseItem, out *v1alpha2.GeneratePatchesResponseItem, s conversion.Scope) error {
	out.UID = types.UID(in.UID)
	out.PatchType = v1alpha2.PatchType(in.PatchType)
	out.Patch = *(*[]byte)(unsafe.Pointer(&in.Patch))
	return nil
}

// Convert_v1alpha1_GeneratePatchesResponseItem_To_v1alpha2_GeneratePatchesResponseItem is an autogenerated conversion function.
func Convert_v1alpha1_GeneratePatchesResponseItem_To_v1alpha2_GeneratePatchesResponseItem(in *GeneratePatchesResponseItem, out *v1alpha2.GeneratePatchesResponseItem, s conversion.Scope) error {
	return autoConvert_v1alpha1_GeneratePatchesResponseItem_To_v1alpha2_GeneratePatchesResponseItem(in, out, s)
}

func autoConvert_v1alpha2_GeneratePatchesResponseItem_To_v1alpha1_GeneratePatchesResponseItem(in *v1alpha2.GeneratePatchesResponseItem, out *GeneratePatchesResponseItem, s conversion.Scope) error {
	out.UID = types.UID(in.UID)
	out.PatchType = PatchType(in.PatchType)
	out.Patch = *(*[]byte)(unsafe.Pointer(&in.Patch))
	return nil
}

// Convert_v1alpha2_GeneratePatchesResponseItem_To_v1alpha1_GeneratePatchesResponseItem is an autogenerated conversion function.
func Convert_v1alpha2_GeneratePatchesResponseItem_To_v1alpha1_GeneratePatchesResponseItem(in *v1alpha2.GeneratePatchesResponseItem, out *GeneratePatchesResponseItem, s conversion.Scope) error {
	return autoConvert_v1alpha2_GeneratePatchesResponseItem_To_v1alpha1_GeneratePatchesResponseItem(in, out, s)
}

func autoConvert_v1alpha1_GroupVersionHook_To_v1alpha2_GroupVersionHook(in *GroupVersionHook, out *v1alpha2.GroupVersionHook, s conversion.Scope) error {
	out.APIVersion = in.APIVersion
	out.Hook = in.Hook
	return nil
}

// Convert_v1alpha1_GroupVersionHook_To_v1alpha2_GroupVersionHook is an autogenerated conversion function.
func Convert_v1alpha1_GroupVersionHook_To_v1alpha2_GroupVersionHook(in *GroupVersionHook, out *v1alpha2.GroupVersionHook, s conversion.Scope) error {
	return autoConvert_v1alpha1_GroupVersionHook_To_v1alpha2_GroupVersionHook(in, out, s)
}

func autoConvert_v1alpha2_GroupVersionHook_To_v1alpha1_GroupVersionHook(in *v1alpha2.GroupVersionHook, out *GroupVersionHook, s conversion.Scope) error {
	out.APIVersion = in.APIVersion
	out.Hook = in.Hook
	return nil
}

// Convert_v1alpha2_GroupVersionHook_To_v1alpha1_GroupVersionHook is an autogenerated conversion function.
func Convert_v1alpha2_GroupVersionHook_To_v1alpha1_GroupVersionHook(in *v1alpha2.GroupVersionHook, out *GroupVersionHook, s conversion.Scope) error {
	return autoConvert_v1alpha2_GroupVersionHook_To_v1alpha1_GroupVersionHook(in, out, s)
}

func autoConvert_v1alpha1_HolderReference_To_v1alpha2_HolderReference(in *HolderReference, out *v1alpha2.HolderReference, s conversion.Scope) error {
	out.APIVersion = in.APIVersion
	out.Kind = in.Kind
	out.Namespace = in.Namespace
	out.Name = in.Name
	out.FieldPath = in.FieldPath
	return nil
}

// Convert_v1alpha1_HolderReference_To_v1alpha2_HolderReference is an autogenerated conversion function.
func Convert_v1alpha1_HolderReference_To_v1alpha2_HolderReference(in *HolderReference, out *v1alpha2.HolderReference, s conversion.Scope) error {
	return autoConvert_v1alpha1_HolderReference_To_v1alpha2_HolderReference(in, out, s)
}

func autoConvert_v1alpha2_HolderReference_To_v1alpha1_HolderReference(in *v1alpha2.HolderReference, out *HolderReference, s conversion.Scope) error {
	out.APIVersion = in.APIVersion
	out.Kind = in.Kind
	out.Namespace = in.Namespace
	out.Name = in.Name
	out.FieldPath = in.FieldPath
	return nil
}

// Convert_v1alpha2_HolderReference_To_v1alpha1_HolderReference is an autogenerated conversion function.
func Convert_v1alpha2_HolderReference_To_v1alpha1_HolderReference(in *v1alpha2.HolderReference, out *HolderReference, s conversion.Scope) error {
	return autoConvert_v1alpha2_HolderReference_To_v1alpha1_HolderReference(in, out, s)
}

func autoConvert_v1alpha1_ValidateTopologyRequest_To_v1alpha2_ValidateTopologyRequest(in *ValidateTopologyRequest, out *v1alpha2.ValidateTopologyRequest, s conversion.Scope) error {
	out.Variables = *(*[]v1alpha2.Variable)(unsafe.Pointer(&in.Variables))
	out.Items = *(*[]*v1alpha2.ValidateTopologyRequestItem)(unsafe.Pointer(&in.Items))
	return nil
}

// Convert_v1alpha1_ValidateTopologyRequest_To_v1alpha2_ValidateTopologyRequest is an autogenerated conversion function.
func Convert_v1alpha1_ValidateTopologyRequest_To_v1alpha2_ValidateTopologyRequest(in *ValidateTopologyRequest, out *v1alpha2.ValidateTopologyRequest, s conversion.Scope) error {
	return autoConvert_v1alpha1_ValidateTopologyRequest_To_v1alpha2_ValidateTopologyRequest(in, out, s)
}

func autoConvert_v1alpha2_ValidateTopologyRequest_To_v1alpha1_ValidateTopologyRequest(in *v1alpha2.ValidateTopologyRequest, out *ValidateTopologyRequest, s conversion.Scope) error {
	out.Variables = *(*[]Variable)(unsafe.Pointer(&in.Variables))
	out.Items = *(*[]*ValidateTopologyRequestItem)(unsafe.Pointer(&in.Items))
	return nil
}

// Convert_v1alpha2_ValidateTopologyRequest_To_v1alpha1_ValidateTopologyRequest is an autogenerated conversion function.
func Convert_v1alpha2_ValidateTopologyRequest_To_v1alpha1_ValidateTopologyRequest(in *v1alpha2.ValidateTopologyRequest, out *ValidateTopologyRequest, s conversion.Scope) error {
	return autoConvert_v1alpha2_ValidateTopologyRequest_To_v1alpha1_ValidateTopologyRequest(in, out, s)
}

func autoConvert_v1alpha1_ValidateTopologyRequestItem_To_v1alpha2_ValidateTopologyRequestItem(in *ValidateTopologyRequestItem, out *v1alpha2.ValidateTopologyRequestItem, s conversion.Scope) error {
	if err := Convert_v1alpha1_HolderReference_To_v1alpha2_HolderReference(&in.HolderReference, &out.HolderReference, s); err != nil {
		return err
	}
	out.Object = in.Object
	out.Variables = *(*[]v1alpha2.Variable)(unsafe.Pointer(&in.Variables))
	return nil
}

// Convert_v1alpha1_ValidateTopologyRequestItem_To_v1alpha2_ValidateTopologyRequestItem is an autogenerated conversion function.
func Convert_v1alpha1_ValidateTopologyRequestItem_To_v1alpha2_ValidateTopologyRequestItem(in *ValidateTopologyRequestItem, out *v1alpha2.ValidateTopologyRequestItem, s conversion.Scope) error {
	return autoConvert_v1alpha1_ValidateTopologyRequestItem_To_v1alpha2_ValidateTopologyRequestItem(in, out, s)
}

func autoConvert_v1alpha2_ValidateTopologyRequestItem_To_v1alpha1_ValidateTopologyRequestItem(in *v1alpha2.ValidateTopologyRequestItem, out *ValidateTopologyRequestItem, s conversion.Scope) error {
	if err := Convert_v1alpha2_HolderReference_To_v1alpha1_HolderReference(&in.HolderReference, &out.HolderReference, s); err != nil {
		return err
	}
	out.Object = in.Object
	out.Variables = *(*[]Variable)(unsafe.Pointer(&in.Variables))
	return nil
}

// Convert_v1alpha2_ValidateTopologyRequestItem_To_v1alpha1_ValidateTopologyRequestItem is an autogenerated conversion function.
func Convert_v1alpha2_ValidateTopologyRequestItem_To_v1alpha1_ValidateTopologyRequestItem(in *v1alpha2.ValidateTopologyRequestItem, out *ValidateTopologyRequestItem, s conversion.Scope) error {
	return autoConvert_v1alpha2_ValidateTopologyRequestItem_To_v1alpha1_ValidateTopologyRequestItem(in, out, s)
}

func autoConvert_v1alpha1_ValidateTopologyResponse_To_v1alpha2_ValidateTopologyResponse(in *ValidateTopologyResponse, out *v1alpha2.ValidateTopologyResponse, s conversion.Scope) error {
	if err := Convert_v1alpha1_CommonResponse_To_v1alpha2_CommonResponse(&in.CommonResponse, &out.CommonResponse, s); err != nil {
		return err
	}
	return nil
}

// Convert_v1alpha1_ValidateTopologyResponse_To_v1alpha2_ValidateTopologyResponse is an autogenerated conversion function.
func Convert_v1alpha1_ValidateTopologyResponse_To_v1alpha2_ValidateTopologyResponse(in *ValidateTopologyResponse, out *v1alpha2.ValidateTopologyResponse, s conversion.Scope) error {
	return autoConvert_v1alpha1_ValidateTopologyResponse_To_v1alpha2_ValidateTopologyResponse(in, out, s)
}

func autoConvert_v1alpha2_ValidateTopologyResponse_To_v1alpha1_ValidateTopologyResponse(in *v1alpha2.ValidateTopologyResponse, out *ValidateTopologyResponse, s conversion.Scope) error {
	if err := Convert_v1alpha2_CommonResponse_To_v1alpha1_CommonResponse(&in.CommonResponse, &out.CommonResponse, s); err != nil {
		return err
	}
	return nil
}

// Convert_v1alpha2_ValidateTopologyResponse_To_v1alpha1_ValidateTopologyResponse is an autogenerated conversion function.
func Convert_v1alpha2_ValidateTopologyResponse_To_v1alpha1_ValidateTopologyResponse(in *v1alpha2.ValidateTopologyResponse, out *ValidateTopologyResponse, s conversion.Scope) error {
	return autoConvert_v1alpha2_ValidateTopologyResponse_To_v1alpha1_ValidateTopologyResponse(in, out, s)
}

func autoConvert_v1alpha1_Variable_To_v1alpha2_Variable(in *Variable, out *v1alpha2.Variable, s conversion.Scope) error {
	out.Name = in.Name
	out.Value = in.Value
	return nil
}

// Convert_v1alpha1_Variable_To_v1alpha2_Variable is an autogenerated conversion function.
func Convert_v1alpha1_Variable_To_v1alpha2_Variable(in *Variable, out *v1alpha2.Variable, s conversion.Scope) error {
	return autoConvert_v1alpha1_Variable_To_v1alpha2_Variable(in, out, s)
}

func autoConvert_v1alpha2_Variable_To_v1alpha1_Variable(in *v1alpha2.Variable, out *Variable, s conversion.Scope) error {
	out.Name = in.Name
	out.Value = in.Value
	return nil
}

// Convert_v1alpha2_Variable_To_v1alpha1_Variable is an autogenerated conversion function.
func Convert_v1alpha2_Variable_To_v1alpha1_Variable(in *v1alpha2.Variable, out *Variable, s conversion.Scope) error {
	return autoConvert_v1alpha2_Variable_To_v1alpha1_Variable(in, out, s)
}
