// Code generated by controller-gen-v0.20.1-0. DO NOT EDIT.

package v1beta2

// APIEndpointApplyConfiguration represents a declarative configuration of the APIEndpoint type for use
// with apply.
//
// APIEndpoint represents a reachable Kubernetes API endpoint.
type APIEndpointApplyConfiguration struct {
	// host is the hostname on which the API server is serving.
	Host *string `json:"host,omitempty"`
	// port is the port on which the API server is serving.
	Port *int32 `json:"port,omitempty"`
}

// APIEndpointApplyConfiguration constructs a declarative configuration of the APIEndpoint type for use with
// apply.
func APIEndpoint() *APIEndpointApplyConfiguration {
	return &APIEndpointApplyConfiguration{}
}

// WithHost sets the Host field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the Host field is set to the value of the last call.
func (b *APIEndpointApplyConfiguration) WithHost(value string) *APIEndpointApplyConfiguration {
	b.Host = &value
	return b
}

// WithPort sets the Port field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the Port field is set to the value of the last call.
func (b *APIEndpointApplyConfiguration) WithPort(value int32) *APIEndpointApplyConfiguration {
	b.Port = &value
	return b
}
