// Code generated by controller-gen-v0.20.1-0. DO NOT EDIT.

package v1beta2

// BootstrapApplyConfiguration represents a declarative configuration of the Bootstrap type for use
// with apply.
//
// Bootstrap encapsulates fields to configure the Machine’s bootstrapping mechanism.
type BootstrapApplyConfiguration struct {
	// configRef is a reference to a bootstrap provider-specific resource
	// that holds configuration details. The reference is optional to
	// allow users/operators to specify Bootstrap.DataSecretName without
	// the need of a controller.
	ConfigRef *ContractVersionedObjectReferenceApplyConfiguration `json:"configRef,omitempty"`
	// dataSecretName is the name of the secret that stores the bootstrap data script.
	// If nil, the Machine should remain in the Pending state.
	DataSecretName *string `json:"dataSecretName,omitempty"`
}

// BootstrapApplyConfiguration constructs a declarative configuration of the Bootstrap type for use with
// apply.
func Bootstrap() *BootstrapApplyConfiguration {
	return &BootstrapApplyConfiguration{}
}

// WithConfigRef sets the ConfigRef field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the ConfigRef field is set to the value of the last call.
func (b *BootstrapApplyConfiguration) WithConfigRef(value *ContractVersionedObjectReferenceApplyConfiguration) *BootstrapApplyConfiguration {
	b.ConfigRef = value
	return b
}

// WithDataSecretName sets the DataSecretName field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the DataSecretName field is set to the value of the last call.
func (b *BootstrapApplyConfiguration) WithDataSecretName(value string) *BootstrapApplyConfiguration {
	b.DataSecretName = &value
	return b
}
