// Code generated by controller-gen-v0.20.1-0. DO NOT EDIT.

package v1beta2

import (
	v1 "k8s.io/apiextensions-apiserver/pkg/apis/apiextensions/v1"
)

// ClusterVariableApplyConfiguration represents a declarative configuration of the ClusterVariable type for use
// with apply.
//
// ClusterVariable can be used to customize the Cluster through patches. Each ClusterVariable is associated with a
// Variable definition in the ClusterClass `status` variables.
type ClusterVariableApplyConfiguration struct {
	// name of the variable.
	Name *string `json:"name,omitempty"`
	// value of the variable.
	// Note: the value will be validated against the schema of the corresponding ClusterClassVariable
	// from the ClusterClass.
	// Note: We have to use apiextensionsv1.JSON instead of a custom JSON type, because controller-tools has a
	// hard-coded schema for apiextensionsv1.JSON which cannot be produced by another type via controller-tools,
	// i.e. it is not possible to have no type field.
	// Ref: https://github.com/kubernetes-sigs/controller-tools/blob/d0e03a142d0ecdd5491593e941ee1d6b5d91dba6/pkg/crd/known_types.go#L106-L111
	Value *v1.JSON `json:"value,omitempty"`
}

// ClusterVariableApplyConfiguration constructs a declarative configuration of the ClusterVariable type for use with
// apply.
func ClusterVariable() *ClusterVariableApplyConfiguration {
	return &ClusterVariableApplyConfiguration{}
}

// WithName sets the Name field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the Name field is set to the value of the last call.
func (b *ClusterVariableApplyConfiguration) WithName(value string) *ClusterVariableApplyConfiguration {
	b.Name = &value
	return b
}

// WithValue sets the Value field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the Value field is set to the value of the last call.
func (b *ClusterVariableApplyConfiguration) WithValue(value v1.JSON) *ClusterVariableApplyConfiguration {
	b.Value = &value
	return b
}
