// Code generated by controller-gen-v0.20.1-0. DO NOT EDIT.

package v1beta2

// ClusterNetworkApplyConfiguration represents a declarative configuration of the ClusterNetwork type for use
// with apply.
//
// ClusterNetwork specifies the different networking
// parameters for a cluster.
type ClusterNetworkApplyConfiguration struct {
	// apiServerPort specifies the port the API Server should bind to.
	// Defaults to 6443.
	APIServerPort *int32 `json:"apiServerPort,omitempty"`
	// services is the network ranges from which service VIPs are allocated.
	Services *NetworkRangesApplyConfiguration `json:"services,omitempty"`
	// pods is the network ranges from which Pod networks are allocated.
	Pods *NetworkRangesApplyConfiguration `json:"pods,omitempty"`
	// serviceDomain is the domain name for services.
	ServiceDomain *string `json:"serviceDomain,omitempty"`
}

// ClusterNetworkApplyConfiguration constructs a declarative configuration of the ClusterNetwork type for use with
// apply.
func ClusterNetwork() *ClusterNetworkApplyConfiguration {
	return &ClusterNetworkApplyConfiguration{}
}

// WithAPIServerPort sets the APIServerPort field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the APIServerPort field is set to the value of the last call.
func (b *ClusterNetworkApplyConfiguration) WithAPIServerPort(value int32) *ClusterNetworkApplyConfiguration {
	b.APIServerPort = &value
	return b
}

// WithServices sets the Services field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the Services field is set to the value of the last call.
func (b *ClusterNetworkApplyConfiguration) WithServices(value *NetworkRangesApplyConfiguration) *ClusterNetworkApplyConfiguration {
	b.Services = value
	return b
}

// WithPods sets the Pods field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the Pods field is set to the value of the last call.
func (b *ClusterNetworkApplyConfiguration) WithPods(value *NetworkRangesApplyConfiguration) *ClusterNetworkApplyConfiguration {
	b.Pods = value
	return b
}

// WithServiceDomain sets the ServiceDomain field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the ServiceDomain field is set to the value of the last call.
func (b *ClusterNetworkApplyConfiguration) WithServiceDomain(value string) *ClusterNetworkApplyConfiguration {
	b.ServiceDomain = &value
	return b
}
