// Code generated by controller-gen-v0.20.1-0. DO NOT EDIT.

package v1beta2

// ClusterClassStatusVariableApplyConfiguration represents a declarative configuration of the ClusterClassStatusVariable type for use
// with apply.
//
// ClusterClassStatusVariable defines a variable which appears in the status of a ClusterClass.
type ClusterClassStatusVariableApplyConfiguration struct {
	// name is the name of the variable.
	Name *string `json:"name,omitempty"`
	// definitionsConflict specifies whether or not there are conflicting definitions for a single variable name.
	DefinitionsConflict *bool `json:"definitionsConflict,omitempty"`
	// definitions is a list of definitions for a variable.
	Definitions []ClusterClassStatusVariableDefinitionApplyConfiguration `json:"definitions,omitempty"`
}

// ClusterClassStatusVariableApplyConfiguration constructs a declarative configuration of the ClusterClassStatusVariable type for use with
// apply.
func ClusterClassStatusVariable() *ClusterClassStatusVariableApplyConfiguration {
	return &ClusterClassStatusVariableApplyConfiguration{}
}

// WithName sets the Name field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the Name field is set to the value of the last call.
func (b *ClusterClassStatusVariableApplyConfiguration) WithName(value string) *ClusterClassStatusVariableApplyConfiguration {
	b.Name = &value
	return b
}

// WithDefinitionsConflict sets the DefinitionsConflict field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the DefinitionsConflict field is set to the value of the last call.
func (b *ClusterClassStatusVariableApplyConfiguration) WithDefinitionsConflict(value bool) *ClusterClassStatusVariableApplyConfiguration {
	b.DefinitionsConflict = &value
	return b
}

// WithDefinitions adds the given value to the Definitions field in the declarative configuration
// and returns the receiver, so that objects can be build by chaining "With" function invocations.
// If called multiple times, values provided by each call will be appended to the Definitions field.
func (b *ClusterClassStatusVariableApplyConfiguration) WithDefinitions(values ...*ClusterClassStatusVariableDefinitionApplyConfiguration) *ClusterClassStatusVariableApplyConfiguration {
	for i := range values {
		if values[i] == nil {
			panic("nil value passed to WithDefinitions")
		}
		b.Definitions = append(b.Definitions, *values[i])
	}
	return b
}
