// Code generated by controller-gen-v0.20.1-0. DO NOT EDIT.

package v1beta2

// ClusterClassStatusVariableDefinitionApplyConfiguration represents a declarative configuration of the ClusterClassStatusVariableDefinition type for use
// with apply.
//
// ClusterClassStatusVariableDefinition defines a variable which appears in the status of a ClusterClass.
type ClusterClassStatusVariableDefinitionApplyConfiguration struct {
	// from specifies the origin of the variable definition.
	// This will be `inline` for variables defined in the ClusterClass or the name of a patch defined in the ClusterClass
	// for variables discovered from a DiscoverVariables runtime extensions.
	From *string `json:"from,omitempty"`
	// required specifies if the variable is required.
	// Note: this applies to the variable as a whole and thus the
	// top-level object defined in the schema. If nested fields are
	// required, this will be specified inside the schema.
	Required *bool `json:"required,omitempty"`
	// deprecatedV1Beta1Metadata is the metadata of a variable.
	// It can be used to add additional data for higher level tools to
	// a ClusterClassVariable.
	//
	// Deprecated: This field is deprecated and will be removed when support for v1beta1 will be dropped. Please use XMetadata in JSONSchemaProps instead.
	DeprecatedV1Beta1Metadata *ClusterClassVariableMetadataApplyConfiguration `json:"deprecatedV1Beta1Metadata,omitempty"`
	// schema defines the schema of the variable.
	Schema *VariableSchemaApplyConfiguration `json:"schema,omitempty"`
}

// ClusterClassStatusVariableDefinitionApplyConfiguration constructs a declarative configuration of the ClusterClassStatusVariableDefinition type for use with
// apply.
func ClusterClassStatusVariableDefinition() *ClusterClassStatusVariableDefinitionApplyConfiguration {
	return &ClusterClassStatusVariableDefinitionApplyConfiguration{}
}

// WithFrom sets the From field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the From field is set to the value of the last call.
func (b *ClusterClassStatusVariableDefinitionApplyConfiguration) WithFrom(value string) *ClusterClassStatusVariableDefinitionApplyConfiguration {
	b.From = &value
	return b
}

// WithRequired sets the Required field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the Required field is set to the value of the last call.
func (b *ClusterClassStatusVariableDefinitionApplyConfiguration) WithRequired(value bool) *ClusterClassStatusVariableDefinitionApplyConfiguration {
	b.Required = &value
	return b
}

// WithDeprecatedV1Beta1Metadata sets the DeprecatedV1Beta1Metadata field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the DeprecatedV1Beta1Metadata field is set to the value of the last call.
func (b *ClusterClassStatusVariableDefinitionApplyConfiguration) WithDeprecatedV1Beta1Metadata(value *ClusterClassVariableMetadataApplyConfiguration) *ClusterClassStatusVariableDefinitionApplyConfiguration {
	b.DeprecatedV1Beta1Metadata = value
	return b
}

// WithSchema sets the Schema field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the Schema field is set to the value of the last call.
func (b *ClusterClassStatusVariableDefinitionApplyConfiguration) WithSchema(value *VariableSchemaApplyConfiguration) *ClusterClassStatusVariableDefinitionApplyConfiguration {
	b.Schema = value
	return b
}
