// Code generated by controller-gen-v0.20.1-0. DO NOT EDIT.

package v1beta2

// ClusterControlPlaneStatusApplyConfiguration represents a declarative configuration of the ClusterControlPlaneStatus type for use
// with apply.
//
// ClusterControlPlaneStatus groups all the observations about control plane current state.
type ClusterControlPlaneStatusApplyConfiguration struct {
	// desiredReplicas is the total number of desired control plane machines in this cluster.
	DesiredReplicas *int32 `json:"desiredReplicas,omitempty"`
	// replicas is the total number of control plane machines in this cluster.
	// NOTE: replicas also includes machines still being provisioned or being deleted.
	Replicas *int32 `json:"replicas,omitempty"`
	// upToDateReplicas is the number of up-to-date control plane machines in this cluster. A machine is considered up-to-date when Machine's UpToDate condition is true.
	UpToDateReplicas *int32 `json:"upToDateReplicas,omitempty"`
	// readyReplicas is the total number of ready control plane machines in this cluster. A machine is considered ready when Machine's Ready condition is true.
	ReadyReplicas *int32 `json:"readyReplicas,omitempty"`
	// availableReplicas is the total number of available control plane machines in this cluster. A machine is considered available when Machine's Available condition is true.
	AvailableReplicas *int32 `json:"availableReplicas,omitempty"`
}

// ClusterControlPlaneStatusApplyConfiguration constructs a declarative configuration of the ClusterControlPlaneStatus type for use with
// apply.
func ClusterControlPlaneStatus() *ClusterControlPlaneStatusApplyConfiguration {
	return &ClusterControlPlaneStatusApplyConfiguration{}
}

// WithDesiredReplicas sets the DesiredReplicas field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the DesiredReplicas field is set to the value of the last call.
func (b *ClusterControlPlaneStatusApplyConfiguration) WithDesiredReplicas(value int32) *ClusterControlPlaneStatusApplyConfiguration {
	b.DesiredReplicas = &value
	return b
}

// WithReplicas sets the Replicas field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the Replicas field is set to the value of the last call.
func (b *ClusterControlPlaneStatusApplyConfiguration) WithReplicas(value int32) *ClusterControlPlaneStatusApplyConfiguration {
	b.Replicas = &value
	return b
}

// WithUpToDateReplicas sets the UpToDateReplicas field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the UpToDateReplicas field is set to the value of the last call.
func (b *ClusterControlPlaneStatusApplyConfiguration) WithUpToDateReplicas(value int32) *ClusterControlPlaneStatusApplyConfiguration {
	b.UpToDateReplicas = &value
	return b
}

// WithReadyReplicas sets the ReadyReplicas field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the ReadyReplicas field is set to the value of the last call.
func (b *ClusterControlPlaneStatusApplyConfiguration) WithReadyReplicas(value int32) *ClusterControlPlaneStatusApplyConfiguration {
	b.ReadyReplicas = &value
	return b
}

// WithAvailableReplicas sets the AvailableReplicas field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the AvailableReplicas field is set to the value of the last call.
func (b *ClusterControlPlaneStatusApplyConfiguration) WithAvailableReplicas(value int32) *ClusterControlPlaneStatusApplyConfiguration {
	b.AvailableReplicas = &value
	return b
}
