// Code generated by controller-gen-v0.20.1-0. DO NOT EDIT.

package v1beta2

// ClusterClassVariableApplyConfiguration represents a declarative configuration of the ClusterClassVariable type for use
// with apply.
//
// ClusterClassVariable defines a variable which can
// be configured in the Cluster topology and used in patches.
type ClusterClassVariableApplyConfiguration struct {
	// name of the variable.
	Name *string `json:"name,omitempty"`
	// required specifies if the variable is required.
	// Note: this applies to the variable as a whole and thus the
	// top-level object defined in the schema. If nested fields are
	// required, this will be specified inside the schema.
	Required *bool `json:"required,omitempty"`
	// deprecatedV1Beta1Metadata is the metadata of a variable.
	// It can be used to add additional data for higher level tools to
	// a ClusterClassVariable.
	//
	// Deprecated: This field is deprecated and will be removed when support for v1beta1 will be dropped. Please use XMetadata in JSONSchemaProps instead.
	DeprecatedV1Beta1Metadata *ClusterClassVariableMetadataApplyConfiguration `json:"deprecatedV1Beta1Metadata,omitempty"`
	// schema defines the schema of the variable.
	Schema *VariableSchemaApplyConfiguration `json:"schema,omitempty"`
}

// ClusterClassVariableApplyConfiguration constructs a declarative configuration of the ClusterClassVariable type for use with
// apply.
func ClusterClassVariable() *ClusterClassVariableApplyConfiguration {
	return &ClusterClassVariableApplyConfiguration{}
}

// WithName sets the Name field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the Name field is set to the value of the last call.
func (b *ClusterClassVariableApplyConfiguration) WithName(value string) *ClusterClassVariableApplyConfiguration {
	b.Name = &value
	return b
}

// WithRequired sets the Required field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the Required field is set to the value of the last call.
func (b *ClusterClassVariableApplyConfiguration) WithRequired(value bool) *ClusterClassVariableApplyConfiguration {
	b.Required = &value
	return b
}

// WithDeprecatedV1Beta1Metadata sets the DeprecatedV1Beta1Metadata field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the DeprecatedV1Beta1Metadata field is set to the value of the last call.
func (b *ClusterClassVariableApplyConfiguration) WithDeprecatedV1Beta1Metadata(value *ClusterClassVariableMetadataApplyConfiguration) *ClusterClassVariableApplyConfiguration {
	b.DeprecatedV1Beta1Metadata = value
	return b
}

// WithSchema sets the Schema field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the Schema field is set to the value of the last call.
func (b *ClusterClassVariableApplyConfiguration) WithSchema(value *VariableSchemaApplyConfiguration) *ClusterClassVariableApplyConfiguration {
	b.Schema = value
	return b
}
