// Code generated by controller-gen-v0.20.1-0. DO NOT EDIT.

package v1beta2

// ClusterClassPatchApplyConfiguration represents a declarative configuration of the ClusterClassPatch type for use
// with apply.
//
// ClusterClassPatch defines a patch which is applied to customize the referenced templates.
type ClusterClassPatchApplyConfiguration struct {
	// name of the patch.
	Name *string `json:"name,omitempty"`
	// description is a human-readable description of this patch.
	Description *string `json:"description,omitempty"`
	// enabledIf is a Go template to be used to calculate if a patch should be enabled.
	// It can reference variables defined in .spec.variables and builtin variables.
	// The patch will be enabled if the template evaluates to `true`, otherwise it will
	// be disabled.
	// If EnabledIf is not set, the patch will be enabled per default.
	EnabledIf *string `json:"enabledIf,omitempty"`
	// definitions define inline patches.
	// Note: Patches will be applied in the order of the array.
	// Note: Exactly one of Definitions or External must be set.
	Definitions []PatchDefinitionApplyConfiguration `json:"definitions,omitempty"`
	// external defines an external patch.
	// Note: Exactly one of Definitions or External must be set.
	External *ExternalPatchDefinitionApplyConfiguration `json:"external,omitempty"`
}

// ClusterClassPatchApplyConfiguration constructs a declarative configuration of the ClusterClassPatch type for use with
// apply.
func ClusterClassPatch() *ClusterClassPatchApplyConfiguration {
	return &ClusterClassPatchApplyConfiguration{}
}

// WithName sets the Name field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the Name field is set to the value of the last call.
func (b *ClusterClassPatchApplyConfiguration) WithName(value string) *ClusterClassPatchApplyConfiguration {
	b.Name = &value
	return b
}

// WithDescription sets the Description field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the Description field is set to the value of the last call.
func (b *ClusterClassPatchApplyConfiguration) WithDescription(value string) *ClusterClassPatchApplyConfiguration {
	b.Description = &value
	return b
}

// WithEnabledIf sets the EnabledIf field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the EnabledIf field is set to the value of the last call.
func (b *ClusterClassPatchApplyConfiguration) WithEnabledIf(value string) *ClusterClassPatchApplyConfiguration {
	b.EnabledIf = &value
	return b
}

// WithDefinitions adds the given value to the Definitions field in the declarative configuration
// and returns the receiver, so that objects can be build by chaining "With" function invocations.
// If called multiple times, values provided by each call will be appended to the Definitions field.
func (b *ClusterClassPatchApplyConfiguration) WithDefinitions(values ...*PatchDefinitionApplyConfiguration) *ClusterClassPatchApplyConfiguration {
	for i := range values {
		if values[i] == nil {
			panic("nil value passed to WithDefinitions")
		}
		b.Definitions = append(b.Definitions, *values[i])
	}
	return b
}

// WithExternal sets the External field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the External field is set to the value of the last call.
func (b *ClusterClassPatchApplyConfiguration) WithExternal(value *ExternalPatchDefinitionApplyConfiguration) *ClusterClassPatchApplyConfiguration {
	b.External = value
	return b
}
