// Code generated by controller-gen-v0.20.1-0. DO NOT EDIT.

package v1beta2

import (
	v1 "k8s.io/client-go/applyconfigurations/meta/v1"
)

// ClusterClassStatusApplyConfiguration represents a declarative configuration of the ClusterClassStatus type for use
// with apply.
//
// ClusterClassStatus defines the observed state of the ClusterClass.
type ClusterClassStatusApplyConfiguration struct {
	// conditions represents the observations of a ClusterClass's current state.
	// Known condition types are VariablesReady, RefVersionsUpToDate, Paused.
	Conditions []v1.ConditionApplyConfiguration `json:"conditions,omitempty"`
	// variables is a list of ClusterClassStatusVariable that are defined for the ClusterClass.
	Variables []ClusterClassStatusVariableApplyConfiguration `json:"variables,omitempty"`
	// observedGeneration is the latest generation observed by the controller.
	ObservedGeneration *int64 `json:"observedGeneration,omitempty"`
	// deprecated groups all the status fields that are deprecated and will be removed when all the nested field are removed.
	Deprecated *ClusterClassDeprecatedStatusApplyConfiguration `json:"deprecated,omitempty"`
}

// ClusterClassStatusApplyConfiguration constructs a declarative configuration of the ClusterClassStatus type for use with
// apply.
func ClusterClassStatus() *ClusterClassStatusApplyConfiguration {
	return &ClusterClassStatusApplyConfiguration{}
}

// WithConditions adds the given value to the Conditions field in the declarative configuration
// and returns the receiver, so that objects can be build by chaining "With" function invocations.
// If called multiple times, values provided by each call will be appended to the Conditions field.
func (b *ClusterClassStatusApplyConfiguration) WithConditions(values ...*v1.ConditionApplyConfiguration) *ClusterClassStatusApplyConfiguration {
	for i := range values {
		if values[i] == nil {
			panic("nil value passed to WithConditions")
		}
		b.Conditions = append(b.Conditions, *values[i])
	}
	return b
}

// WithVariables adds the given value to the Variables field in the declarative configuration
// and returns the receiver, so that objects can be build by chaining "With" function invocations.
// If called multiple times, values provided by each call will be appended to the Variables field.
func (b *ClusterClassStatusApplyConfiguration) WithVariables(values ...*ClusterClassStatusVariableApplyConfiguration) *ClusterClassStatusApplyConfiguration {
	for i := range values {
		if values[i] == nil {
			panic("nil value passed to WithVariables")
		}
		b.Variables = append(b.Variables, *values[i])
	}
	return b
}

// WithObservedGeneration sets the ObservedGeneration field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the ObservedGeneration field is set to the value of the last call.
func (b *ClusterClassStatusApplyConfiguration) WithObservedGeneration(value int64) *ClusterClassStatusApplyConfiguration {
	b.ObservedGeneration = &value
	return b
}

// WithDeprecated sets the Deprecated field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the Deprecated field is set to the value of the last call.
func (b *ClusterClassStatusApplyConfiguration) WithDeprecated(value *ClusterClassDeprecatedStatusApplyConfiguration) *ClusterClassStatusApplyConfiguration {
	b.Deprecated = value
	return b
}
