// Code generated by controller-gen-v0.20.1-0. DO NOT EDIT.

package v1beta2

// ClusterDeprecatedStatusApplyConfiguration represents a declarative configuration of the ClusterDeprecatedStatus type for use
// with apply.
//
// ClusterDeprecatedStatus groups all the status fields that are deprecated and will be removed in a future version.
// See https://github.com/kubernetes-sigs/cluster-api/blob/main/docs/proposals/20240916-improve-status-in-CAPI-resources.md for more context.
type ClusterDeprecatedStatusApplyConfiguration struct {
	// v1beta1 groups all the status fields that are deprecated and will be removed when support for v1beta1 will be dropped.
	V1Beta1 *ClusterV1Beta1DeprecatedStatusApplyConfiguration `json:"v1beta1,omitempty"`
}

// ClusterDeprecatedStatusApplyConfiguration constructs a declarative configuration of the ClusterDeprecatedStatus type for use with
// apply.
func ClusterDeprecatedStatus() *ClusterDeprecatedStatusApplyConfiguration {
	return &ClusterDeprecatedStatusApplyConfiguration{}
}

// WithV1Beta1 sets the V1Beta1 field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the V1Beta1 field is set to the value of the last call.
func (b *ClusterDeprecatedStatusApplyConfiguration) WithV1Beta1(value *ClusterV1Beta1DeprecatedStatusApplyConfiguration) *ClusterDeprecatedStatusApplyConfiguration {
	b.V1Beta1 = value
	return b
}
