// Code generated by controller-gen-v0.20.1-0. DO NOT EDIT.

package v1beta2

// ClusterClassUpgradeExternalApplyConfiguration represents a declarative configuration of the ClusterClassUpgradeExternal type for use
// with apply.
//
// ClusterClassUpgradeExternal defines external runtime extensions for upgrade operations.
type ClusterClassUpgradeExternalApplyConfiguration struct {
	// generateUpgradePlanExtension references an extension which is called to generate upgrade plan.
	GenerateUpgradePlanExtension *string `json:"generateUpgradePlanExtension,omitempty"`
}

// ClusterClassUpgradeExternalApplyConfiguration constructs a declarative configuration of the ClusterClassUpgradeExternal type for use with
// apply.
func ClusterClassUpgradeExternal() *ClusterClassUpgradeExternalApplyConfiguration {
	return &ClusterClassUpgradeExternalApplyConfiguration{}
}

// WithGenerateUpgradePlanExtension sets the GenerateUpgradePlanExtension field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the GenerateUpgradePlanExtension field is set to the value of the last call.
func (b *ClusterClassUpgradeExternalApplyConfiguration) WithGenerateUpgradePlanExtension(value string) *ClusterClassUpgradeExternalApplyConfiguration {
	b.GenerateUpgradePlanExtension = &value
	return b
}
