// Code generated by controller-gen-v0.20.1-0. DO NOT EDIT.

package v1beta2

// ClusterClassUpgradeApplyConfiguration represents a declarative configuration of the ClusterClassUpgrade type for use
// with apply.
//
// ClusterClassUpgrade defines the upgrade configuration for clusters using the ClusterClass.
type ClusterClassUpgradeApplyConfiguration struct {
	// external defines external runtime extensions for upgrade operations.
	External *ClusterClassUpgradeExternalApplyConfiguration `json:"external,omitempty"`
}

// ClusterClassUpgradeApplyConfiguration constructs a declarative configuration of the ClusterClassUpgrade type for use with
// apply.
func ClusterClassUpgrade() *ClusterClassUpgradeApplyConfiguration {
	return &ClusterClassUpgradeApplyConfiguration{}
}

// WithExternal sets the External field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the External field is set to the value of the last call.
func (b *ClusterClassUpgradeApplyConfiguration) WithExternal(value *ClusterClassUpgradeExternalApplyConfiguration) *ClusterClassUpgradeApplyConfiguration {
	b.External = value
	return b
}
