// Code generated by controller-gen-v0.20.1-0. DO NOT EDIT.

package v1beta2

import (
	corev1beta2 "sigs.k8s.io/cluster-api/api/core/v1beta2"
)

// ClusterAvailabilityGateApplyConfiguration represents a declarative configuration of the ClusterAvailabilityGate type for use
// with apply.
//
// ClusterAvailabilityGate contains the type of a Cluster condition to be used as availability gate.
type ClusterAvailabilityGateApplyConfiguration struct {
	// conditionType refers to a condition with matching type in the Cluster's condition list.
	// If the conditions doesn't exist, it will be treated as unknown.
	// Note: Both Cluster API conditions or conditions added by 3rd party controllers can be used as availability gates.
	ConditionType *string `json:"conditionType,omitempty"`
	// polarity of the conditionType specified in this availabilityGate.
	// Valid values are Positive, Negative and omitted.
	// When omitted, the default behaviour will be Positive.
	// A positive polarity means that the condition should report a true status under normal conditions.
	// A negative polarity means that the condition should report a false status under normal conditions.
	Polarity *corev1beta2.ConditionPolarity `json:"polarity,omitempty"`
}

// ClusterAvailabilityGateApplyConfiguration constructs a declarative configuration of the ClusterAvailabilityGate type for use with
// apply.
func ClusterAvailabilityGate() *ClusterAvailabilityGateApplyConfiguration {
	return &ClusterAvailabilityGateApplyConfiguration{}
}

// WithConditionType sets the ConditionType field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the ConditionType field is set to the value of the last call.
func (b *ClusterAvailabilityGateApplyConfiguration) WithConditionType(value string) *ClusterAvailabilityGateApplyConfiguration {
	b.ConditionType = &value
	return b
}

// WithPolarity sets the Polarity field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the Polarity field is set to the value of the last call.
func (b *ClusterAvailabilityGateApplyConfiguration) WithPolarity(value corev1beta2.ConditionPolarity) *ClusterAvailabilityGateApplyConfiguration {
	b.Polarity = &value
	return b
}
