// Code generated by controller-gen-v0.20.1-0. DO NOT EDIT.

package v1beta2

// ClusterClassRefApplyConfiguration represents a declarative configuration of the ClusterClassRef type for use
// with apply.
//
// ClusterClassRef is the ref to the ClusterClass that should be used for the topology.
type ClusterClassRefApplyConfiguration struct {
	// name is the name of the ClusterClass that should be used for the topology.
	// name must be a valid ClusterClass name and because of that be at most 253 characters in length
	// and it must consist only of lower case alphanumeric characters, hyphens (-) and periods (.), and must start
	// and end with an alphanumeric character.
	Name *string `json:"name,omitempty"`
	// namespace is the namespace of the ClusterClass that should be used for the topology.
	// If namespace is empty or not set, it is defaulted to the namespace of the Cluster object.
	// namespace must be a valid namespace name and because of that be at most 63 characters in length
	// and it must consist only of lower case alphanumeric characters or hyphens (-), and must start
	// and end with an alphanumeric character.
	Namespace *string `json:"namespace,omitempty"`
}

// ClusterClassRefApplyConfiguration constructs a declarative configuration of the ClusterClassRef type for use with
// apply.
func ClusterClassRef() *ClusterClassRefApplyConfiguration {
	return &ClusterClassRefApplyConfiguration{}
}

// WithName sets the Name field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the Name field is set to the value of the last call.
func (b *ClusterClassRefApplyConfiguration) WithName(value string) *ClusterClassRefApplyConfiguration {
	b.Name = &value
	return b
}

// WithNamespace sets the Namespace field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the Namespace field is set to the value of the last call.
func (b *ClusterClassRefApplyConfiguration) WithNamespace(value string) *ClusterClassRefApplyConfiguration {
	b.Namespace = &value
	return b
}
