// Code generated by controller-gen-v0.21. DO NOT EDIT.

package v1beta2

// ClusterControlPlaneStatusApplyConfiguration represents a declarative configuration of the ClusterControlPlaneStatus type for use
// with apply.
//
// ClusterControlPlaneStatus groups all the observations about control plane current state.
type ClusterControlPlaneStatusApplyConfiguration struct {
	// desiredReplicas is the total number of desired control plane machines in this cluster.
	DesiredReplicas *int32 `json:"desiredReplicas,omitempty"`
	// replicas is the total number of control plane machines in this cluster.
	// NOTE: replicas also includes machines still being provisioned or being deleted.
	Replicas *int32 `json:"replicas,omitempty"`
	// upToDateReplicas is the number of up-to-date control plane machines in this cluster. A machine is considered up-to-date when Machine's UpToDate condition is true.
	UpToDateReplicas *int32 `json:"upToDateReplicas,omitempty"`
	// readyReplicas is the total number of ready control plane machines in this cluster. A machine is considered ready when Machine's Ready condition is true.
	ReadyReplicas *int32 `json:"readyReplicas,omitempty"`
	// availableReplicas is the total number of available control plane machines in this cluster. A machine is considered available when Machine's Available condition is true.
	AvailableReplicas *int32 `json:"availableReplicas,omitempty"`
	// versions is the aggregated Kubernetes versions in this control plane.
	Versions []StatusVersionApplyConfiguration `json:"versions,omitempty"`
	// upgradePlan reports the list of versions that would be applied to the control plane object according to the upgrade plan.
	// Note:
	// - This field is set only when the Cluster topology is managed by Cluster API and a Cluster upgrade is in progress.
	// - Once a version is applied to the control plane object, it is removed from the list (after a version
	// is applied to a control plane object, it might take some time for the actual upgrade to complete)
	// - During a chained upgrade, the upgrade plan is continuously re-computed, and this field will
	// report only the last known upgrade plan.
	UpgradePlan []StatusUpgradePlanVersionApplyConfiguration `json:"upgradePlan,omitempty"`
}

// ClusterControlPlaneStatusApplyConfiguration constructs a declarative configuration of the ClusterControlPlaneStatus type for use with
// apply.
func ClusterControlPlaneStatus() *ClusterControlPlaneStatusApplyConfiguration {
	return &ClusterControlPlaneStatusApplyConfiguration{}
}

// WithDesiredReplicas sets the DesiredReplicas field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the DesiredReplicas field is set to the value of the last call.
func (b *ClusterControlPlaneStatusApplyConfiguration) WithDesiredReplicas(value int32) *ClusterControlPlaneStatusApplyConfiguration {
	b.DesiredReplicas = &value
	return b
}

// WithReplicas sets the Replicas field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the Replicas field is set to the value of the last call.
func (b *ClusterControlPlaneStatusApplyConfiguration) WithReplicas(value int32) *ClusterControlPlaneStatusApplyConfiguration {
	b.Replicas = &value
	return b
}

// WithUpToDateReplicas sets the UpToDateReplicas field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the UpToDateReplicas field is set to the value of the last call.
func (b *ClusterControlPlaneStatusApplyConfiguration) WithUpToDateReplicas(value int32) *ClusterControlPlaneStatusApplyConfiguration {
	b.UpToDateReplicas = &value
	return b
}

// WithReadyReplicas sets the ReadyReplicas field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the ReadyReplicas field is set to the value of the last call.
func (b *ClusterControlPlaneStatusApplyConfiguration) WithReadyReplicas(value int32) *ClusterControlPlaneStatusApplyConfiguration {
	b.ReadyReplicas = &value
	return b
}

// WithAvailableReplicas sets the AvailableReplicas field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the AvailableReplicas field is set to the value of the last call.
func (b *ClusterControlPlaneStatusApplyConfiguration) WithAvailableReplicas(value int32) *ClusterControlPlaneStatusApplyConfiguration {
	b.AvailableReplicas = &value
	return b
}

// WithVersions adds the given value to the Versions field in the declarative configuration
// and returns the receiver, so that objects can be build by chaining "With" function invocations.
// If called multiple times, values provided by each call will be appended to the Versions field.
func (b *ClusterControlPlaneStatusApplyConfiguration) WithVersions(values ...*StatusVersionApplyConfiguration) *ClusterControlPlaneStatusApplyConfiguration {
	for i := range values {
		if values[i] == nil {
			panic("nil value passed to WithVersions")
		}
		b.Versions = append(b.Versions, *values[i])
	}
	return b
}

// WithUpgradePlan adds the given value to the UpgradePlan field in the declarative configuration
// and returns the receiver, so that objects can be build by chaining "With" function invocations.
// If called multiple times, values provided by each call will be appended to the UpgradePlan field.
func (b *ClusterControlPlaneStatusApplyConfiguration) WithUpgradePlan(values ...*StatusUpgradePlanVersionApplyConfiguration) *ClusterControlPlaneStatusApplyConfiguration {
	for i := range values {
		if values[i] == nil {
			panic("nil value passed to WithUpgradePlan")
		}
		b.UpgradePlan = append(b.UpgradePlan, *values[i])
	}
	return b
}
