// Code generated by controller-gen-v0.20.1-0. DO NOT EDIT.

package v1beta2

// ClusterInitializationStatusApplyConfiguration represents a declarative configuration of the ClusterInitializationStatus type for use
// with apply.
//
// ClusterInitializationStatus provides observations of the Cluster initialization process.
// NOTE: Fields in this struct are part of the Cluster API contract and are used to orchestrate initial Cluster provisioning.
type ClusterInitializationStatusApplyConfiguration struct {
	// infrastructureProvisioned is true when the infrastructure provider reports that Cluster's infrastructure is fully provisioned.
	// NOTE: this field is part of the Cluster API contract, and it is used to orchestrate provisioning.
	// The value of this field is never updated after provisioning is completed.
	InfrastructureProvisioned *bool `json:"infrastructureProvisioned,omitempty"`
	// controlPlaneInitialized denotes when the control plane is functional enough to accept requests.
	// This information is usually used as a signal for starting all the provisioning operations that depends on
	// a functional API server, but do not require a full HA control plane to exists, like e.g. join worker Machines,
	// install core addons like CNI, CPI, CSI etc.
	// NOTE: this field is part of the Cluster API contract, and it is used to orchestrate provisioning.
	// The value of this field is never updated after initialization is completed.
	ControlPlaneInitialized *bool `json:"controlPlaneInitialized,omitempty"`
}

// ClusterInitializationStatusApplyConfiguration constructs a declarative configuration of the ClusterInitializationStatus type for use with
// apply.
func ClusterInitializationStatus() *ClusterInitializationStatusApplyConfiguration {
	return &ClusterInitializationStatusApplyConfiguration{}
}

// WithInfrastructureProvisioned sets the InfrastructureProvisioned field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the InfrastructureProvisioned field is set to the value of the last call.
func (b *ClusterInitializationStatusApplyConfiguration) WithInfrastructureProvisioned(value bool) *ClusterInitializationStatusApplyConfiguration {
	b.InfrastructureProvisioned = &value
	return b
}

// WithControlPlaneInitialized sets the ControlPlaneInitialized field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the ControlPlaneInitialized field is set to the value of the last call.
func (b *ClusterInitializationStatusApplyConfiguration) WithControlPlaneInitialized(value bool) *ClusterInitializationStatusApplyConfiguration {
	b.ControlPlaneInitialized = &value
	return b
}
