// Code generated by controller-gen-v0.20.1-0. DO NOT EDIT.

package v1beta2

// ControlPlaneVariablesApplyConfiguration represents a declarative configuration of the ControlPlaneVariables type for use
// with apply.
//
// ControlPlaneVariables can be used to provide variables for the ControlPlane.
type ControlPlaneVariablesApplyConfiguration struct {
	// overrides can be used to override Cluster level variables.
	Overrides []ClusterVariableApplyConfiguration `json:"overrides,omitempty"`
}

// ControlPlaneVariablesApplyConfiguration constructs a declarative configuration of the ControlPlaneVariables type for use with
// apply.
func ControlPlaneVariables() *ControlPlaneVariablesApplyConfiguration {
	return &ControlPlaneVariablesApplyConfiguration{}
}

// WithOverrides adds the given value to the Overrides field in the declarative configuration
// and returns the receiver, so that objects can be build by chaining "With" function invocations.
// If called multiple times, values provided by each call will be appended to the Overrides field.
func (b *ControlPlaneVariablesApplyConfiguration) WithOverrides(values ...*ClusterVariableApplyConfiguration) *ControlPlaneVariablesApplyConfiguration {
	for i := range values {
		if values[i] == nil {
			panic("nil value passed to WithOverrides")
		}
		b.Overrides = append(b.Overrides, *values[i])
	}
	return b
}
