// Code generated by controller-gen-v0.20.1-0. DO NOT EDIT.

package v1beta2

// ControlPlaneClassMachineInfrastructureTemplateApplyConfiguration represents a declarative configuration of the ControlPlaneClassMachineInfrastructureTemplate type for use
// with apply.
//
// ControlPlaneClassMachineInfrastructureTemplate defines the template for a MachineInfrastructure of a ControlPlane.
type ControlPlaneClassMachineInfrastructureTemplateApplyConfiguration struct {
	// templateRef is a required reference to the template for a MachineInfrastructure of a ControlPlane.
	TemplateRef *ClusterClassTemplateReferenceApplyConfiguration `json:"templateRef,omitempty"`
}

// ControlPlaneClassMachineInfrastructureTemplateApplyConfiguration constructs a declarative configuration of the ControlPlaneClassMachineInfrastructureTemplate type for use with
// apply.
func ControlPlaneClassMachineInfrastructureTemplate() *ControlPlaneClassMachineInfrastructureTemplateApplyConfiguration {
	return &ControlPlaneClassMachineInfrastructureTemplateApplyConfiguration{}
}

// WithTemplateRef sets the TemplateRef field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the TemplateRef field is set to the value of the last call.
func (b *ControlPlaneClassMachineInfrastructureTemplateApplyConfiguration) WithTemplateRef(value *ClusterClassTemplateReferenceApplyConfiguration) *ControlPlaneClassMachineInfrastructureTemplateApplyConfiguration {
	b.TemplateRef = value
	return b
}
