// Code generated by controller-gen-v0.21. DO NOT EDIT.

package v1beta2

// ControlPlaneClassApplyConfiguration represents a declarative configuration of the ControlPlaneClass type for use
// with apply.
//
// ControlPlaneClass defines the class for the control plane.
type ControlPlaneClassApplyConfiguration struct {
	// metadata is the metadata applied to the ControlPlane and the Machines of the ControlPlane
	// if the ControlPlaneTemplate referenced is machine based. If not, it is applied only to the
	// ControlPlane.
	// At runtime this metadata is merged with the corresponding metadata from the topology.
	//
	// This field is supported if and only if the control plane provider template
	// referenced is Machine based.
	Metadata *ObjectMetaApplyConfiguration `json:"metadata,omitempty"`
	// templateRef contains the reference to a provider-specific control plane template.
	TemplateRef *ClusterClassTemplateReferenceApplyConfiguration `json:"templateRef,omitempty"`
	// machineInfrastructure defines the metadata and infrastructure information
	// for control plane machines.
	//
	// This field is supported if and only if the control plane provider template
	// referenced above is Machine based and supports setting replicas.
	MachineInfrastructure *ControlPlaneClassMachineInfrastructureTemplateApplyConfiguration `json:"machineInfrastructure,omitempty"`
	// healthCheck defines a MachineHealthCheck for this ControlPlaneClass.
	// This field is supported if and only if the ControlPlane provider template
	// referenced above is Machine based and supports setting replicas.
	HealthCheck *ControlPlaneClassHealthCheckApplyConfiguration `json:"healthCheck,omitempty"`
	// naming allows changing the naming pattern used when creating the control plane provider object.
	Naming *ControlPlaneClassNamingSpecApplyConfiguration `json:"naming,omitempty"`
	// deletion contains configuration options for Machine deletion.
	Deletion *ControlPlaneClassMachineDeletionSpecApplyConfiguration `json:"deletion,omitempty"`
	// taints are the node taints that Cluster API will manage.
	// This list is not necessarily complete: other Kubernetes components may add or remove other taints from nodes,
	// e.g. the node controller might add the node.kubernetes.io/not-ready taint.
	// Only those taints defined in this list will be added or removed by core Cluster API controllers.
	//
	// There can be at most 64 taints.
	// A pod would have to tolerate all existing taints to run on the corresponding node.
	//
	// NOTE: This list is implemented as a "map" type, meaning that individual elements can be managed by different owners.
	Taints []MachineTaintApplyConfiguration `json:"taints,omitempty"`
	// readinessGates specifies additional conditions to include when evaluating Machine Ready condition.
	//
	// This field can be used e.g. to instruct the machine controller to include in the computation for Machine's ready
	// computation a condition, managed by an external controllers, reporting the status of special software/hardware installed on the Machine.
	//
	// NOTE: If a Cluster defines a custom list of readinessGates for the control plane,
	// such list overrides readinessGates defined in this field.
	// NOTE: Specific control plane provider implementations might automatically extend the list of readinessGates;
	// e.g. the kubeadm control provider adds ReadinessGates for the APIServerPodHealthy, SchedulerPodHealthy conditions, etc.
	ReadinessGates []MachineReadinessGateApplyConfiguration `json:"readinessGates,omitempty"`
}

// ControlPlaneClassApplyConfiguration constructs a declarative configuration of the ControlPlaneClass type for use with
// apply.
func ControlPlaneClass() *ControlPlaneClassApplyConfiguration {
	return &ControlPlaneClassApplyConfiguration{}
}

// WithMetadata sets the Metadata field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the Metadata field is set to the value of the last call.
func (b *ControlPlaneClassApplyConfiguration) WithMetadata(value *ObjectMetaApplyConfiguration) *ControlPlaneClassApplyConfiguration {
	b.Metadata = value
	return b
}

// WithTemplateRef sets the TemplateRef field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the TemplateRef field is set to the value of the last call.
func (b *ControlPlaneClassApplyConfiguration) WithTemplateRef(value *ClusterClassTemplateReferenceApplyConfiguration) *ControlPlaneClassApplyConfiguration {
	b.TemplateRef = value
	return b
}

// WithMachineInfrastructure sets the MachineInfrastructure field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the MachineInfrastructure field is set to the value of the last call.
func (b *ControlPlaneClassApplyConfiguration) WithMachineInfrastructure(value *ControlPlaneClassMachineInfrastructureTemplateApplyConfiguration) *ControlPlaneClassApplyConfiguration {
	b.MachineInfrastructure = value
	return b
}

// WithHealthCheck sets the HealthCheck field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the HealthCheck field is set to the value of the last call.
func (b *ControlPlaneClassApplyConfiguration) WithHealthCheck(value *ControlPlaneClassHealthCheckApplyConfiguration) *ControlPlaneClassApplyConfiguration {
	b.HealthCheck = value
	return b
}

// WithNaming sets the Naming field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the Naming field is set to the value of the last call.
func (b *ControlPlaneClassApplyConfiguration) WithNaming(value *ControlPlaneClassNamingSpecApplyConfiguration) *ControlPlaneClassApplyConfiguration {
	b.Naming = value
	return b
}

// WithDeletion sets the Deletion field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the Deletion field is set to the value of the last call.
func (b *ControlPlaneClassApplyConfiguration) WithDeletion(value *ControlPlaneClassMachineDeletionSpecApplyConfiguration) *ControlPlaneClassApplyConfiguration {
	b.Deletion = value
	return b
}

// WithTaints adds the given value to the Taints field in the declarative configuration
// and returns the receiver, so that objects can be build by chaining "With" function invocations.
// If called multiple times, values provided by each call will be appended to the Taints field.
func (b *ControlPlaneClassApplyConfiguration) WithTaints(values ...*MachineTaintApplyConfiguration) *ControlPlaneClassApplyConfiguration {
	for i := range values {
		if values[i] == nil {
			panic("nil value passed to WithTaints")
		}
		b.Taints = append(b.Taints, *values[i])
	}
	return b
}

// WithReadinessGates adds the given value to the ReadinessGates field in the declarative configuration
// and returns the receiver, so that objects can be build by chaining "With" function invocations.
// If called multiple times, values provided by each call will be appended to the ReadinessGates field.
func (b *ControlPlaneClassApplyConfiguration) WithReadinessGates(values ...*MachineReadinessGateApplyConfiguration) *ControlPlaneClassApplyConfiguration {
	for i := range values {
		if values[i] == nil {
			panic("nil value passed to WithReadinessGates")
		}
		b.ReadinessGates = append(b.ReadinessGates, *values[i])
	}
	return b
}
