// Code generated by controller-gen-v0.20.1-0. DO NOT EDIT.

package v1beta2

// ExternalPatchDefinitionApplyConfiguration represents a declarative configuration of the ExternalPatchDefinition type for use
// with apply.
//
// ExternalPatchDefinition defines an external patch.
// Note: At least one of GeneratePatchesExtension or ValidateTopologyExtension must be set.
type ExternalPatchDefinitionApplyConfiguration struct {
	// generatePatchesExtension references an extension which is called to generate patches.
	GeneratePatchesExtension *string `json:"generatePatchesExtension,omitempty"`
	// validateTopologyExtension references an extension which is called to validate the topology.
	ValidateTopologyExtension *string `json:"validateTopologyExtension,omitempty"`
	// discoverVariablesExtension references an extension which is called to discover variables.
	DiscoverVariablesExtension *string `json:"discoverVariablesExtension,omitempty"`
	// settings defines key value pairs to be passed to the extensions.
	// Values defined here take precedence over the values defined in the
	// corresponding ExtensionConfig.
	Settings map[string]string `json:"settings,omitempty"`
}

// ExternalPatchDefinitionApplyConfiguration constructs a declarative configuration of the ExternalPatchDefinition type for use with
// apply.
func ExternalPatchDefinition() *ExternalPatchDefinitionApplyConfiguration {
	return &ExternalPatchDefinitionApplyConfiguration{}
}

// WithGeneratePatchesExtension sets the GeneratePatchesExtension field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the GeneratePatchesExtension field is set to the value of the last call.
func (b *ExternalPatchDefinitionApplyConfiguration) WithGeneratePatchesExtension(value string) *ExternalPatchDefinitionApplyConfiguration {
	b.GeneratePatchesExtension = &value
	return b
}

// WithValidateTopologyExtension sets the ValidateTopologyExtension field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the ValidateTopologyExtension field is set to the value of the last call.
func (b *ExternalPatchDefinitionApplyConfiguration) WithValidateTopologyExtension(value string) *ExternalPatchDefinitionApplyConfiguration {
	b.ValidateTopologyExtension = &value
	return b
}

// WithDiscoverVariablesExtension sets the DiscoverVariablesExtension field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the DiscoverVariablesExtension field is set to the value of the last call.
func (b *ExternalPatchDefinitionApplyConfiguration) WithDiscoverVariablesExtension(value string) *ExternalPatchDefinitionApplyConfiguration {
	b.DiscoverVariablesExtension = &value
	return b
}

// WithSettings puts the entries into the Settings field in the declarative configuration
// and returns the receiver, so that objects can be build by chaining "With" function invocations.
// If called multiple times, the entries provided by each call will be put on the Settings field,
// overwriting an existing map entries in Settings field with the same key.
func (b *ExternalPatchDefinitionApplyConfiguration) WithSettings(entries map[string]string) *ExternalPatchDefinitionApplyConfiguration {
	if b.Settings == nil && len(entries) > 0 {
		b.Settings = make(map[string]string, len(entries))
	}
	for k, v := range entries {
		b.Settings[k] = v
	}
	return b
}
