// Code generated by controller-gen-v0.20.1-0. DO NOT EDIT.

package v1beta2

// FailureDomainApplyConfiguration represents a declarative configuration of the FailureDomain type for use
// with apply.
//
// FailureDomain is the Schema for Cluster API failure domains.
// It allows controllers to understand how many failure domains a cluster can optionally span across.
type FailureDomainApplyConfiguration struct {
	// name is the name of the failure domain.
	Name *string `json:"name,omitempty"`
	// controlPlane determines if this failure domain is suitable for use by control plane machines.
	ControlPlane *bool `json:"controlPlane,omitempty"`
	// attributes is a free form map of attributes an infrastructure provider might use or require.
	Attributes map[string]string `json:"attributes,omitempty"`
}

// FailureDomainApplyConfiguration constructs a declarative configuration of the FailureDomain type for use with
// apply.
func FailureDomain() *FailureDomainApplyConfiguration {
	return &FailureDomainApplyConfiguration{}
}

// WithName sets the Name field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the Name field is set to the value of the last call.
func (b *FailureDomainApplyConfiguration) WithName(value string) *FailureDomainApplyConfiguration {
	b.Name = &value
	return b
}

// WithControlPlane sets the ControlPlane field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the ControlPlane field is set to the value of the last call.
func (b *FailureDomainApplyConfiguration) WithControlPlane(value bool) *FailureDomainApplyConfiguration {
	b.ControlPlane = &value
	return b
}

// WithAttributes puts the entries into the Attributes field in the declarative configuration
// and returns the receiver, so that objects can be build by chaining "With" function invocations.
// If called multiple times, the entries provided by each call will be put on the Attributes field,
// overwriting an existing map entries in Attributes field with the same key.
func (b *FailureDomainApplyConfiguration) WithAttributes(entries map[string]string) *FailureDomainApplyConfiguration {
	if b.Attributes == nil && len(entries) > 0 {
		b.Attributes = make(map[string]string, len(entries))
	}
	for k, v := range entries {
		b.Attributes[k] = v
	}
	return b
}
