// Code generated by controller-gen-v0.20.1-0. DO NOT EDIT.

package v1beta2

// InfrastructureClassNamingSpecApplyConfiguration represents a declarative configuration of the InfrastructureClassNamingSpec type for use
// with apply.
//
// InfrastructureClassNamingSpec defines the naming strategy for infrastructure objects.
type InfrastructureClassNamingSpecApplyConfiguration struct {
	// template defines the template to use for generating the name of the Infrastructure object.
	// If not defined, it will fallback to `{{ .cluster.name }}-{{ .random }}`.
	// If the templated string exceeds 63 characters, it will be trimmed to 58 characters and will
	// get concatenated with a random suffix of length 5.
	// The templating mechanism provides the following arguments:
	// * `.cluster.name`: The name of the cluster object.
	// * `.random`: A random alphanumeric string, without vowels, of length 5.
	Template *string `json:"template,omitempty"`
}

// InfrastructureClassNamingSpecApplyConfiguration constructs a declarative configuration of the InfrastructureClassNamingSpec type for use with
// apply.
func InfrastructureClassNamingSpec() *InfrastructureClassNamingSpecApplyConfiguration {
	return &InfrastructureClassNamingSpecApplyConfiguration{}
}

// WithTemplate sets the Template field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the Template field is set to the value of the last call.
func (b *InfrastructureClassNamingSpecApplyConfiguration) WithTemplate(value string) *InfrastructureClassNamingSpecApplyConfiguration {
	b.Template = &value
	return b
}
