// Code generated by controller-gen-v0.20.1-0. DO NOT EDIT.

package v1beta2

// InfrastructureClassApplyConfiguration represents a declarative configuration of the InfrastructureClass type for use
// with apply.
//
// InfrastructureClass defines the class for the infrastructure cluster.
type InfrastructureClassApplyConfiguration struct {
	// templateRef contains the reference to a provider-specific infrastructure cluster template.
	TemplateRef *ClusterClassTemplateReferenceApplyConfiguration `json:"templateRef,omitempty"`
	// naming allows changing the naming pattern used when creating the infrastructure cluster object.
	Naming *InfrastructureClassNamingSpecApplyConfiguration `json:"naming,omitempty"`
}

// InfrastructureClassApplyConfiguration constructs a declarative configuration of the InfrastructureClass type for use with
// apply.
func InfrastructureClass() *InfrastructureClassApplyConfiguration {
	return &InfrastructureClassApplyConfiguration{}
}

// WithTemplateRef sets the TemplateRef field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the TemplateRef field is set to the value of the last call.
func (b *InfrastructureClassApplyConfiguration) WithTemplateRef(value *ClusterClassTemplateReferenceApplyConfiguration) *InfrastructureClassApplyConfiguration {
	b.TemplateRef = value
	return b
}

// WithNaming sets the Naming field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the Naming field is set to the value of the last call.
func (b *InfrastructureClassApplyConfiguration) WithNaming(value *InfrastructureClassNamingSpecApplyConfiguration) *InfrastructureClassApplyConfiguration {
	b.Naming = value
	return b
}
