// Code generated by controller-gen-v0.20.1-0. DO NOT EDIT.

package v1beta2

// MachineDeploymentClassBootstrapTemplateApplyConfiguration represents a declarative configuration of the MachineDeploymentClassBootstrapTemplate type for use
// with apply.
//
// MachineDeploymentClassBootstrapTemplate defines the BootstrapTemplate for a MachineDeployment.
type MachineDeploymentClassBootstrapTemplateApplyConfiguration struct {
	// templateRef is a required reference to the BootstrapTemplate for a MachineDeployment.
	TemplateRef *ClusterClassTemplateReferenceApplyConfiguration `json:"templateRef,omitempty"`
}

// MachineDeploymentClassBootstrapTemplateApplyConfiguration constructs a declarative configuration of the MachineDeploymentClassBootstrapTemplate type for use with
// apply.
func MachineDeploymentClassBootstrapTemplate() *MachineDeploymentClassBootstrapTemplateApplyConfiguration {
	return &MachineDeploymentClassBootstrapTemplateApplyConfiguration{}
}

// WithTemplateRef sets the TemplateRef field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the TemplateRef field is set to the value of the last call.
func (b *MachineDeploymentClassBootstrapTemplateApplyConfiguration) WithTemplateRef(value *ClusterClassTemplateReferenceApplyConfiguration) *MachineDeploymentClassBootstrapTemplateApplyConfiguration {
	b.TemplateRef = value
	return b
}
