// Code generated by controller-gen-v0.20.1-0. DO NOT EDIT.

package v1beta2

// MachineDeploymentVariablesApplyConfiguration represents a declarative configuration of the MachineDeploymentVariables type for use
// with apply.
//
// MachineDeploymentVariables can be used to provide variables for a specific MachineDeployment.
type MachineDeploymentVariablesApplyConfiguration struct {
	// overrides can be used to override Cluster level variables.
	Overrides []ClusterVariableApplyConfiguration `json:"overrides,omitempty"`
}

// MachineDeploymentVariablesApplyConfiguration constructs a declarative configuration of the MachineDeploymentVariables type for use with
// apply.
func MachineDeploymentVariables() *MachineDeploymentVariablesApplyConfiguration {
	return &MachineDeploymentVariablesApplyConfiguration{}
}

// WithOverrides adds the given value to the Overrides field in the declarative configuration
// and returns the receiver, so that objects can be build by chaining "With" function invocations.
// If called multiple times, values provided by each call will be appended to the Overrides field.
func (b *MachineDeploymentVariablesApplyConfiguration) WithOverrides(values ...*ClusterVariableApplyConfiguration) *MachineDeploymentVariablesApplyConfiguration {
	for i := range values {
		if values[i] == nil {
			panic("nil value passed to WithOverrides")
		}
		b.Overrides = append(b.Overrides, *values[i])
	}
	return b
}
