// Code generated by controller-gen-v0.20.1-0. DO NOT EDIT.

package v1beta2

// MachineDeploymentClassRolloutSpecApplyConfiguration represents a declarative configuration of the MachineDeploymentClassRolloutSpec type for use
// with apply.
//
// MachineDeploymentClassRolloutSpec defines the rollout behavior.
type MachineDeploymentClassRolloutSpecApplyConfiguration struct {
	// strategy specifies how to roll out control plane Machines.
	Strategy *MachineDeploymentClassRolloutStrategyApplyConfiguration `json:"strategy,omitempty"`
}

// MachineDeploymentClassRolloutSpecApplyConfiguration constructs a declarative configuration of the MachineDeploymentClassRolloutSpec type for use with
// apply.
func MachineDeploymentClassRolloutSpec() *MachineDeploymentClassRolloutSpecApplyConfiguration {
	return &MachineDeploymentClassRolloutSpecApplyConfiguration{}
}

// WithStrategy sets the Strategy field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the Strategy field is set to the value of the last call.
func (b *MachineDeploymentClassRolloutSpecApplyConfiguration) WithStrategy(value *MachineDeploymentClassRolloutStrategyApplyConfiguration) *MachineDeploymentClassRolloutSpecApplyConfiguration {
	b.Strategy = value
	return b
}
