// Code generated by controller-gen-v0.20.1-0. DO NOT EDIT.

package v1beta2

import (
	v1 "k8s.io/client-go/applyconfigurations/meta/v1"
)

// MachineHealthCheckStatusApplyConfiguration represents a declarative configuration of the MachineHealthCheckStatus type for use
// with apply.
//
// MachineHealthCheckStatus defines the observed state of MachineHealthCheck.
type MachineHealthCheckStatusApplyConfiguration struct {
	// conditions represents the observations of a MachineHealthCheck's current state.
	// Known condition types are RemediationAllowed, Paused.
	Conditions []v1.ConditionApplyConfiguration `json:"conditions,omitempty"`
	// expectedMachines is the total number of machines counted by this machine health check
	ExpectedMachines *int32 `json:"expectedMachines,omitempty"`
	// currentHealthy is the total number of healthy machines counted by this machine health check
	CurrentHealthy *int32 `json:"currentHealthy,omitempty"`
	// remediationsAllowed is the number of further remediations allowed by this machine health check before
	// maxUnhealthy short circuiting will be applied
	RemediationsAllowed *int32 `json:"remediationsAllowed,omitempty"`
	// observedGeneration is the latest generation observed by the controller.
	ObservedGeneration *int64 `json:"observedGeneration,omitempty"`
	// targets shows the current list of machines the machine health check is watching
	Targets []string `json:"targets,omitempty"`
	// deprecated groups all the status fields that are deprecated and will be removed when all the nested field are removed.
	Deprecated *MachineHealthCheckDeprecatedStatusApplyConfiguration `json:"deprecated,omitempty"`
}

// MachineHealthCheckStatusApplyConfiguration constructs a declarative configuration of the MachineHealthCheckStatus type for use with
// apply.
func MachineHealthCheckStatus() *MachineHealthCheckStatusApplyConfiguration {
	return &MachineHealthCheckStatusApplyConfiguration{}
}

// WithConditions adds the given value to the Conditions field in the declarative configuration
// and returns the receiver, so that objects can be build by chaining "With" function invocations.
// If called multiple times, values provided by each call will be appended to the Conditions field.
func (b *MachineHealthCheckStatusApplyConfiguration) WithConditions(values ...*v1.ConditionApplyConfiguration) *MachineHealthCheckStatusApplyConfiguration {
	for i := range values {
		if values[i] == nil {
			panic("nil value passed to WithConditions")
		}
		b.Conditions = append(b.Conditions, *values[i])
	}
	return b
}

// WithExpectedMachines sets the ExpectedMachines field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the ExpectedMachines field is set to the value of the last call.
func (b *MachineHealthCheckStatusApplyConfiguration) WithExpectedMachines(value int32) *MachineHealthCheckStatusApplyConfiguration {
	b.ExpectedMachines = &value
	return b
}

// WithCurrentHealthy sets the CurrentHealthy field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the CurrentHealthy field is set to the value of the last call.
func (b *MachineHealthCheckStatusApplyConfiguration) WithCurrentHealthy(value int32) *MachineHealthCheckStatusApplyConfiguration {
	b.CurrentHealthy = &value
	return b
}

// WithRemediationsAllowed sets the RemediationsAllowed field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the RemediationsAllowed field is set to the value of the last call.
func (b *MachineHealthCheckStatusApplyConfiguration) WithRemediationsAllowed(value int32) *MachineHealthCheckStatusApplyConfiguration {
	b.RemediationsAllowed = &value
	return b
}

// WithObservedGeneration sets the ObservedGeneration field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the ObservedGeneration field is set to the value of the last call.
func (b *MachineHealthCheckStatusApplyConfiguration) WithObservedGeneration(value int64) *MachineHealthCheckStatusApplyConfiguration {
	b.ObservedGeneration = &value
	return b
}

// WithTargets adds the given value to the Targets field in the declarative configuration
// and returns the receiver, so that objects can be build by chaining "With" function invocations.
// If called multiple times, values provided by each call will be appended to the Targets field.
func (b *MachineHealthCheckStatusApplyConfiguration) WithTargets(values ...string) *MachineHealthCheckStatusApplyConfiguration {
	for i := range values {
		b.Targets = append(b.Targets, values[i])
	}
	return b
}

// WithDeprecated sets the Deprecated field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the Deprecated field is set to the value of the last call.
func (b *MachineHealthCheckStatusApplyConfiguration) WithDeprecated(value *MachineHealthCheckDeprecatedStatusApplyConfiguration) *MachineHealthCheckStatusApplyConfiguration {
	b.Deprecated = value
	return b
}
