// Code generated by controller-gen-v0.20.1-0. DO NOT EDIT.

package v1beta2

// MachineDeploymentClassInfrastructureTemplateApplyConfiguration represents a declarative configuration of the MachineDeploymentClassInfrastructureTemplate type for use
// with apply.
//
// MachineDeploymentClassInfrastructureTemplate defines the InfrastructureTemplate for a MachineDeployment.
type MachineDeploymentClassInfrastructureTemplateApplyConfiguration struct {
	// templateRef is a required reference to the InfrastructureTemplate for a MachineDeployment.
	TemplateRef *ClusterClassTemplateReferenceApplyConfiguration `json:"templateRef,omitempty"`
}

// MachineDeploymentClassInfrastructureTemplateApplyConfiguration constructs a declarative configuration of the MachineDeploymentClassInfrastructureTemplate type for use with
// apply.
func MachineDeploymentClassInfrastructureTemplate() *MachineDeploymentClassInfrastructureTemplateApplyConfiguration {
	return &MachineDeploymentClassInfrastructureTemplateApplyConfiguration{}
}

// WithTemplateRef sets the TemplateRef field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the TemplateRef field is set to the value of the last call.
func (b *MachineDeploymentClassInfrastructureTemplateApplyConfiguration) WithTemplateRef(value *ClusterClassTemplateReferenceApplyConfiguration) *MachineDeploymentClassInfrastructureTemplateApplyConfiguration {
	b.TemplateRef = value
	return b
}
