// Code generated by controller-gen-v0.20.1-0. DO NOT EDIT.

package v1beta2

import (
	metav1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	types "k8s.io/apimachinery/pkg/types"
	managedfields "k8s.io/apimachinery/pkg/util/managedfields"
	v1 "k8s.io/client-go/applyconfigurations/meta/v1"
	corev1beta2 "sigs.k8s.io/cluster-api/api/core/v1beta2"
	internal "sigs.k8s.io/cluster-api/util/applyconfigurations/internal"
)

// MachineDeploymentApplyConfiguration represents a declarative configuration of the MachineDeployment type for use
// with apply.
//
// MachineDeployment is the Schema for the machinedeployments API.
type MachineDeploymentApplyConfiguration struct {
	v1.TypeMetaApplyConfiguration `json:",inline"`
	// metadata is the standard object's metadata.
	// More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#metadata
	*v1.ObjectMetaApplyConfiguration `json:"metadata,omitempty"`
	// spec is the desired state of MachineDeployment.
	Spec *MachineDeploymentSpecApplyConfiguration `json:"spec,omitempty"`
	// status is the observed state of MachineDeployment.
	Status *MachineDeploymentStatusApplyConfiguration `json:"status,omitempty"`
}

// MachineDeployment constructs a declarative configuration of the MachineDeployment type for use with
// apply.
func MachineDeployment(name, namespace string) *MachineDeploymentApplyConfiguration {
	b := &MachineDeploymentApplyConfiguration{}
	b.WithName(name)
	b.WithNamespace(namespace)
	b.WithKind("MachineDeployment")
	b.WithAPIVersion("cluster.x-k8s.io/v1beta2")
	return b
}

// ExtractMachineDeploymentFrom extracts the applied configuration owned by fieldManager from
// machineDeployment for the specified subresource. Pass an empty string for subresource to extract
// the main resource. Common subresources include "status", "scale", etc.
// machineDeployment must be a unmodified MachineDeployment API object that was retrieved from the Kubernetes API.
// ExtractMachineDeploymentFrom provides a way to perform a extract/modify-in-place/apply workflow.
// Note that an extracted apply configuration will contain fewer fields than what the fieldManager previously
// applied if another fieldManager has updated or force applied any of the previously applied fields.
func ExtractMachineDeploymentFrom(machineDeployment *corev1beta2.MachineDeployment, fieldManager string, subresource string) (*MachineDeploymentApplyConfiguration, error) {
	b := &MachineDeploymentApplyConfiguration{}
	err := managedfields.ExtractInto(machineDeployment, internal.Parser().Type("io.k8s.sigs.cluster-api.api.core.v1beta2.MachineDeployment"), fieldManager, b, subresource)
	if err != nil {
		return nil, err
	}
	b.WithName(machineDeployment.Name)
	b.WithNamespace(machineDeployment.Namespace)

	b.WithKind("MachineDeployment")
	b.WithAPIVersion("cluster.x-k8s.io/v1beta2")
	return b, nil
}

// ExtractMachineDeployment extracts the applied configuration owned by fieldManager from
// machineDeployment. If no managedFields are found in machineDeployment for fieldManager, a
// MachineDeploymentApplyConfiguration is returned with only the Name, Namespace (if applicable),
// APIVersion and Kind populated. It is possible that no managed fields were found for because other
// field managers have taken ownership of all the fields previously owned by fieldManager, or because
// the fieldManager never owned fields any fields.
// machineDeployment must be a unmodified MachineDeployment API object that was retrieved from the Kubernetes API.
// ExtractMachineDeployment provides a way to perform a extract/modify-in-place/apply workflow.
// Note that an extracted apply configuration will contain fewer fields than what the fieldManager previously
// applied if another fieldManager has updated or force applied any of the previously applied fields.
func ExtractMachineDeployment(machineDeployment *corev1beta2.MachineDeployment, fieldManager string) (*MachineDeploymentApplyConfiguration, error) {
	return ExtractMachineDeploymentFrom(machineDeployment, fieldManager, "")
}

// ExtractMachineDeploymentStatus extracts the applied configuration owned by fieldManager from
// machineDeployment for the status subresource.
func ExtractMachineDeploymentStatus(machineDeployment *corev1beta2.MachineDeployment, fieldManager string) (*MachineDeploymentApplyConfiguration, error) {
	return ExtractMachineDeploymentFrom(machineDeployment, fieldManager, "status")
}

func (b MachineDeploymentApplyConfiguration) IsApplyConfiguration() {}

// WithKind sets the Kind field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the Kind field is set to the value of the last call.
func (b *MachineDeploymentApplyConfiguration) WithKind(value string) *MachineDeploymentApplyConfiguration {
	b.TypeMetaApplyConfiguration.Kind = &value
	return b
}

// WithAPIVersion sets the APIVersion field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the APIVersion field is set to the value of the last call.
func (b *MachineDeploymentApplyConfiguration) WithAPIVersion(value string) *MachineDeploymentApplyConfiguration {
	b.TypeMetaApplyConfiguration.APIVersion = &value
	return b
}

// WithName sets the Name field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the Name field is set to the value of the last call.
func (b *MachineDeploymentApplyConfiguration) WithName(value string) *MachineDeploymentApplyConfiguration {
	b.ensureObjectMetaApplyConfigurationExists()
	b.ObjectMetaApplyConfiguration.Name = &value
	return b
}

// WithGenerateName sets the GenerateName field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the GenerateName field is set to the value of the last call.
func (b *MachineDeploymentApplyConfiguration) WithGenerateName(value string) *MachineDeploymentApplyConfiguration {
	b.ensureObjectMetaApplyConfigurationExists()
	b.ObjectMetaApplyConfiguration.GenerateName = &value
	return b
}

// WithNamespace sets the Namespace field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the Namespace field is set to the value of the last call.
func (b *MachineDeploymentApplyConfiguration) WithNamespace(value string) *MachineDeploymentApplyConfiguration {
	b.ensureObjectMetaApplyConfigurationExists()
	b.ObjectMetaApplyConfiguration.Namespace = &value
	return b
}

// WithUID sets the UID field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the UID field is set to the value of the last call.
func (b *MachineDeploymentApplyConfiguration) WithUID(value types.UID) *MachineDeploymentApplyConfiguration {
	b.ensureObjectMetaApplyConfigurationExists()
	b.ObjectMetaApplyConfiguration.UID = &value
	return b
}

// WithResourceVersion sets the ResourceVersion field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the ResourceVersion field is set to the value of the last call.
func (b *MachineDeploymentApplyConfiguration) WithResourceVersion(value string) *MachineDeploymentApplyConfiguration {
	b.ensureObjectMetaApplyConfigurationExists()
	b.ObjectMetaApplyConfiguration.ResourceVersion = &value
	return b
}

// WithGeneration sets the Generation field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the Generation field is set to the value of the last call.
func (b *MachineDeploymentApplyConfiguration) WithGeneration(value int64) *MachineDeploymentApplyConfiguration {
	b.ensureObjectMetaApplyConfigurationExists()
	b.ObjectMetaApplyConfiguration.Generation = &value
	return b
}

// WithCreationTimestamp sets the CreationTimestamp field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the CreationTimestamp field is set to the value of the last call.
func (b *MachineDeploymentApplyConfiguration) WithCreationTimestamp(value metav1.Time) *MachineDeploymentApplyConfiguration {
	b.ensureObjectMetaApplyConfigurationExists()
	b.ObjectMetaApplyConfiguration.CreationTimestamp = &value
	return b
}

// WithDeletionTimestamp sets the DeletionTimestamp field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the DeletionTimestamp field is set to the value of the last call.
func (b *MachineDeploymentApplyConfiguration) WithDeletionTimestamp(value metav1.Time) *MachineDeploymentApplyConfiguration {
	b.ensureObjectMetaApplyConfigurationExists()
	b.ObjectMetaApplyConfiguration.DeletionTimestamp = &value
	return b
}

// WithDeletionGracePeriodSeconds sets the DeletionGracePeriodSeconds field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the DeletionGracePeriodSeconds field is set to the value of the last call.
func (b *MachineDeploymentApplyConfiguration) WithDeletionGracePeriodSeconds(value int64) *MachineDeploymentApplyConfiguration {
	b.ensureObjectMetaApplyConfigurationExists()
	b.ObjectMetaApplyConfiguration.DeletionGracePeriodSeconds = &value
	return b
}

// WithLabels puts the entries into the Labels field in the declarative configuration
// and returns the receiver, so that objects can be build by chaining "With" function invocations.
// If called multiple times, the entries provided by each call will be put on the Labels field,
// overwriting an existing map entries in Labels field with the same key.
func (b *MachineDeploymentApplyConfiguration) WithLabels(entries map[string]string) *MachineDeploymentApplyConfiguration {
	b.ensureObjectMetaApplyConfigurationExists()
	if b.ObjectMetaApplyConfiguration.Labels == nil && len(entries) > 0 {
		b.ObjectMetaApplyConfiguration.Labels = make(map[string]string, len(entries))
	}
	for k, v := range entries {
		b.ObjectMetaApplyConfiguration.Labels[k] = v
	}
	return b
}

// WithAnnotations puts the entries into the Annotations field in the declarative configuration
// and returns the receiver, so that objects can be build by chaining "With" function invocations.
// If called multiple times, the entries provided by each call will be put on the Annotations field,
// overwriting an existing map entries in Annotations field with the same key.
func (b *MachineDeploymentApplyConfiguration) WithAnnotations(entries map[string]string) *MachineDeploymentApplyConfiguration {
	b.ensureObjectMetaApplyConfigurationExists()
	if b.ObjectMetaApplyConfiguration.Annotations == nil && len(entries) > 0 {
		b.ObjectMetaApplyConfiguration.Annotations = make(map[string]string, len(entries))
	}
	for k, v := range entries {
		b.ObjectMetaApplyConfiguration.Annotations[k] = v
	}
	return b
}

// WithOwnerReferences adds the given value to the OwnerReferences field in the declarative configuration
// and returns the receiver, so that objects can be build by chaining "With" function invocations.
// If called multiple times, values provided by each call will be appended to the OwnerReferences field.
func (b *MachineDeploymentApplyConfiguration) WithOwnerReferences(values ...*v1.OwnerReferenceApplyConfiguration) *MachineDeploymentApplyConfiguration {
	b.ensureObjectMetaApplyConfigurationExists()
	for i := range values {
		if values[i] == nil {
			panic("nil value passed to WithOwnerReferences")
		}
		b.ObjectMetaApplyConfiguration.OwnerReferences = append(b.ObjectMetaApplyConfiguration.OwnerReferences, *values[i])
	}
	return b
}

// WithFinalizers adds the given value to the Finalizers field in the declarative configuration
// and returns the receiver, so that objects can be build by chaining "With" function invocations.
// If called multiple times, values provided by each call will be appended to the Finalizers field.
func (b *MachineDeploymentApplyConfiguration) WithFinalizers(values ...string) *MachineDeploymentApplyConfiguration {
	b.ensureObjectMetaApplyConfigurationExists()
	for i := range values {
		b.ObjectMetaApplyConfiguration.Finalizers = append(b.ObjectMetaApplyConfiguration.Finalizers, values[i])
	}
	return b
}

func (b *MachineDeploymentApplyConfiguration) ensureObjectMetaApplyConfigurationExists() {
	if b.ObjectMetaApplyConfiguration == nil {
		b.ObjectMetaApplyConfiguration = &v1.ObjectMetaApplyConfiguration{}
	}
}

// WithSpec sets the Spec field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the Spec field is set to the value of the last call.
func (b *MachineDeploymentApplyConfiguration) WithSpec(value *MachineDeploymentSpecApplyConfiguration) *MachineDeploymentApplyConfiguration {
	b.Spec = value
	return b
}

// WithStatus sets the Status field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the Status field is set to the value of the last call.
func (b *MachineDeploymentApplyConfiguration) WithStatus(value *MachineDeploymentStatusApplyConfiguration) *MachineDeploymentApplyConfiguration {
	b.Status = value
	return b
}

// GetKind retrieves the value of the Kind field in the declarative configuration.
func (b *MachineDeploymentApplyConfiguration) GetKind() *string {
	return b.TypeMetaApplyConfiguration.Kind
}

// GetAPIVersion retrieves the value of the APIVersion field in the declarative configuration.
func (b *MachineDeploymentApplyConfiguration) GetAPIVersion() *string {
	return b.TypeMetaApplyConfiguration.APIVersion
}

// GetName retrieves the value of the Name field in the declarative configuration.
func (b *MachineDeploymentApplyConfiguration) GetName() *string {
	b.ensureObjectMetaApplyConfigurationExists()
	return b.ObjectMetaApplyConfiguration.Name
}

// GetNamespace retrieves the value of the Namespace field in the declarative configuration.
func (b *MachineDeploymentApplyConfiguration) GetNamespace() *string {
	b.ensureObjectMetaApplyConfigurationExists()
	return b.ObjectMetaApplyConfiguration.Namespace
}
