// Code generated by controller-gen-v0.20.1-0. DO NOT EDIT.

package v1beta2

// MachinePoolClassNamingSpecApplyConfiguration represents a declarative configuration of the MachinePoolClassNamingSpec type for use
// with apply.
//
// MachinePoolClassNamingSpec defines the naming strategy for MachinePool objects.
type MachinePoolClassNamingSpecApplyConfiguration struct {
	// template defines the template to use for generating the name of the MachinePool object.
	// If not defined, it will fallback to `{{ .cluster.name }}-{{ .machinePool.topologyName }}-{{ .random }}`.
	// If the templated string exceeds 63 characters, it will be trimmed to 58 characters and will
	// get concatenated with a random suffix of length 5.
	// The templating mechanism provides the following arguments:
	// * `.cluster.name`: The name of the cluster object.
	// * `.random`: A random alphanumeric string, without vowels, of length 5.
	// * `.machinePool.topologyName`: The name of the MachinePool topology (Cluster.spec.topology.workers.machinePools[].name).
	Template *string `json:"template,omitempty"`
}

// MachinePoolClassNamingSpecApplyConfiguration constructs a declarative configuration of the MachinePoolClassNamingSpec type for use with
// apply.
func MachinePoolClassNamingSpec() *MachinePoolClassNamingSpecApplyConfiguration {
	return &MachinePoolClassNamingSpecApplyConfiguration{}
}

// WithTemplate sets the Template field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the Template field is set to the value of the last call.
func (b *MachinePoolClassNamingSpecApplyConfiguration) WithTemplate(value string) *MachinePoolClassNamingSpecApplyConfiguration {
	b.Template = &value
	return b
}
