// Code generated by controller-gen-v0.20.1-0. DO NOT EDIT.

package v1beta2

import (
	intstr "k8s.io/apimachinery/pkg/util/intstr"
)

// MachineHealthCheckRemediationTriggerIfApplyConfiguration represents a declarative configuration of the MachineHealthCheckRemediationTriggerIf type for use
// with apply.
//
// MachineHealthCheckRemediationTriggerIf configures if remediations are triggered.
type MachineHealthCheckRemediationTriggerIfApplyConfiguration struct {
	// unhealthyLessThanOrEqualTo specifies that remediations are only triggered if the number of
	// unhealthy Machines is less than or equal to the configured value.
	// unhealthyInRange takes precedence if set.
	UnhealthyLessThanOrEqualTo *intstr.IntOrString `json:"unhealthyLessThanOrEqualTo,omitempty"`
	// unhealthyInRange specifies that remediations are only triggered if the number of
	// unhealthy Machines is in the configured range.
	// Takes precedence over unhealthyLessThanOrEqualTo.
	// Eg. "[3-5]" - This means that remediation will be allowed only when:
	// (a) there are at least 3 unhealthy Machines (and)
	// (b) there are at most 5 unhealthy Machines
	UnhealthyInRange *string `json:"unhealthyInRange,omitempty"`
}

// MachineHealthCheckRemediationTriggerIfApplyConfiguration constructs a declarative configuration of the MachineHealthCheckRemediationTriggerIf type for use with
// apply.
func MachineHealthCheckRemediationTriggerIf() *MachineHealthCheckRemediationTriggerIfApplyConfiguration {
	return &MachineHealthCheckRemediationTriggerIfApplyConfiguration{}
}

// WithUnhealthyLessThanOrEqualTo sets the UnhealthyLessThanOrEqualTo field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the UnhealthyLessThanOrEqualTo field is set to the value of the last call.
func (b *MachineHealthCheckRemediationTriggerIfApplyConfiguration) WithUnhealthyLessThanOrEqualTo(value intstr.IntOrString) *MachineHealthCheckRemediationTriggerIfApplyConfiguration {
	b.UnhealthyLessThanOrEqualTo = &value
	return b
}

// WithUnhealthyInRange sets the UnhealthyInRange field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the UnhealthyInRange field is set to the value of the last call.
func (b *MachineHealthCheckRemediationTriggerIfApplyConfiguration) WithUnhealthyInRange(value string) *MachineHealthCheckRemediationTriggerIfApplyConfiguration {
	b.UnhealthyInRange = &value
	return b
}
