// Code generated by controller-gen-v0.20.1-0. DO NOT EDIT.

package v1beta2

// MachineDeletionSpecApplyConfiguration represents a declarative configuration of the MachineDeletionSpec type for use
// with apply.
//
// MachineDeletionSpec contains configuration options for Machine deletion.
type MachineDeletionSpecApplyConfiguration struct {
	// nodeDrainTimeoutSeconds is the total amount of time that the controller will spend on draining a node.
	// The default value is 0, meaning that the node can be drained without any time limitations.
	// NOTE: nodeDrainTimeoutSeconds is different from `kubectl drain --timeout`
	NodeDrainTimeoutSeconds *int32 `json:"nodeDrainTimeoutSeconds,omitempty"`
	// nodeVolumeDetachTimeoutSeconds is the total amount of time that the controller will spend on waiting for all volumes
	// to be detached. The default value is 0, meaning that the volumes can be detached without any time limitations.
	NodeVolumeDetachTimeoutSeconds *int32 `json:"nodeVolumeDetachTimeoutSeconds,omitempty"`
	// nodeDeletionTimeoutSeconds defines how long the controller will attempt to delete the Node that the Machine
	// hosts after the Machine is marked for deletion. A duration of 0 will retry deletion indefinitely.
	// Defaults to 10 seconds.
	NodeDeletionTimeoutSeconds *int32 `json:"nodeDeletionTimeoutSeconds,omitempty"`
}

// MachineDeletionSpecApplyConfiguration constructs a declarative configuration of the MachineDeletionSpec type for use with
// apply.
func MachineDeletionSpec() *MachineDeletionSpecApplyConfiguration {
	return &MachineDeletionSpecApplyConfiguration{}
}

// WithNodeDrainTimeoutSeconds sets the NodeDrainTimeoutSeconds field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the NodeDrainTimeoutSeconds field is set to the value of the last call.
func (b *MachineDeletionSpecApplyConfiguration) WithNodeDrainTimeoutSeconds(value int32) *MachineDeletionSpecApplyConfiguration {
	b.NodeDrainTimeoutSeconds = &value
	return b
}

// WithNodeVolumeDetachTimeoutSeconds sets the NodeVolumeDetachTimeoutSeconds field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the NodeVolumeDetachTimeoutSeconds field is set to the value of the last call.
func (b *MachineDeletionSpecApplyConfiguration) WithNodeVolumeDetachTimeoutSeconds(value int32) *MachineDeletionSpecApplyConfiguration {
	b.NodeVolumeDetachTimeoutSeconds = &value
	return b
}

// WithNodeDeletionTimeoutSeconds sets the NodeDeletionTimeoutSeconds field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the NodeDeletionTimeoutSeconds field is set to the value of the last call.
func (b *MachineDeletionSpecApplyConfiguration) WithNodeDeletionTimeoutSeconds(value int32) *MachineDeletionSpecApplyConfiguration {
	b.NodeDeletionTimeoutSeconds = &value
	return b
}
