// Code generated by controller-gen-v0.20.1-0. DO NOT EDIT.

package v1beta2

// MachineInitializationStatusApplyConfiguration represents a declarative configuration of the MachineInitializationStatus type for use
// with apply.
//
// MachineInitializationStatus provides observations of the Machine initialization process.
// NOTE: Fields in this struct are part of the Cluster API contract and are used to orchestrate initial Machine provisioning.
type MachineInitializationStatusApplyConfiguration struct {
	// infrastructureProvisioned is true when the infrastructure provider reports that Machine's infrastructure is fully provisioned.
	// NOTE: this field is part of the Cluster API contract, and it is used to orchestrate provisioning.
	// The value of this field is never updated after provisioning is completed.
	InfrastructureProvisioned *bool `json:"infrastructureProvisioned,omitempty"`
	// bootstrapDataSecretCreated is true when the bootstrap provider reports that the Machine's boostrap secret is created.
	// NOTE: this field is part of the Cluster API contract, and it is used to orchestrate provisioning.
	// The value of this field is never updated after provisioning is completed.
	BootstrapDataSecretCreated *bool `json:"bootstrapDataSecretCreated,omitempty"`
}

// MachineInitializationStatusApplyConfiguration constructs a declarative configuration of the MachineInitializationStatus type for use with
// apply.
func MachineInitializationStatus() *MachineInitializationStatusApplyConfiguration {
	return &MachineInitializationStatusApplyConfiguration{}
}

// WithInfrastructureProvisioned sets the InfrastructureProvisioned field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the InfrastructureProvisioned field is set to the value of the last call.
func (b *MachineInitializationStatusApplyConfiguration) WithInfrastructureProvisioned(value bool) *MachineInitializationStatusApplyConfiguration {
	b.InfrastructureProvisioned = &value
	return b
}

// WithBootstrapDataSecretCreated sets the BootstrapDataSecretCreated field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the BootstrapDataSecretCreated field is set to the value of the last call.
func (b *MachineInitializationStatusApplyConfiguration) WithBootstrapDataSecretCreated(value bool) *MachineInitializationStatusApplyConfiguration {
	b.BootstrapDataSecretCreated = &value
	return b
}
