// Code generated by controller-gen-v0.20.1-0. DO NOT EDIT.

package v1beta2

// MachineHealthCheckRemediationApplyConfiguration represents a declarative configuration of the MachineHealthCheckRemediation type for use
// with apply.
//
// MachineHealthCheckRemediation configures if and how remediations are triggered if a Machine is unhealthy.
type MachineHealthCheckRemediationApplyConfiguration struct {
	// triggerIf configures if remediations are triggered.
	// If this field is not set, remediations are always triggered.
	TriggerIf *MachineHealthCheckRemediationTriggerIfApplyConfiguration `json:"triggerIf,omitempty"`
	// templateRef is a reference to a remediation template
	// provided by an infrastructure provider.
	//
	// This field is completely optional, when filled, the MachineHealthCheck controller
	// creates a new object from the template referenced and hands off remediation of the machine to
	// a controller that lives outside of Cluster API.
	TemplateRef *MachineHealthCheckRemediationTemplateReferenceApplyConfiguration `json:"templateRef,omitempty"`
}

// MachineHealthCheckRemediationApplyConfiguration constructs a declarative configuration of the MachineHealthCheckRemediation type for use with
// apply.
func MachineHealthCheckRemediation() *MachineHealthCheckRemediationApplyConfiguration {
	return &MachineHealthCheckRemediationApplyConfiguration{}
}

// WithTriggerIf sets the TriggerIf field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the TriggerIf field is set to the value of the last call.
func (b *MachineHealthCheckRemediationApplyConfiguration) WithTriggerIf(value *MachineHealthCheckRemediationTriggerIfApplyConfiguration) *MachineHealthCheckRemediationApplyConfiguration {
	b.TriggerIf = value
	return b
}

// WithTemplateRef sets the TemplateRef field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the TemplateRef field is set to the value of the last call.
func (b *MachineHealthCheckRemediationApplyConfiguration) WithTemplateRef(value *MachineHealthCheckRemediationTemplateReferenceApplyConfiguration) *MachineHealthCheckRemediationApplyConfiguration {
	b.TemplateRef = value
	return b
}
