// Code generated by controller-gen-v0.20.1-0. DO NOT EDIT.

package v1beta2

// MachinePoolClassInfrastructureTemplateApplyConfiguration represents a declarative configuration of the MachinePoolClassInfrastructureTemplate type for use
// with apply.
//
// MachinePoolClassInfrastructureTemplate defines the InfrastructureTemplate for a MachinePool.
type MachinePoolClassInfrastructureTemplateApplyConfiguration struct {
	// templateRef is a required reference to the InfrastructureTemplate for a MachinePool.
	TemplateRef *ClusterClassTemplateReferenceApplyConfiguration `json:"templateRef,omitempty"`
}

// MachinePoolClassInfrastructureTemplateApplyConfiguration constructs a declarative configuration of the MachinePoolClassInfrastructureTemplate type for use with
// apply.
func MachinePoolClassInfrastructureTemplate() *MachinePoolClassInfrastructureTemplateApplyConfiguration {
	return &MachinePoolClassInfrastructureTemplateApplyConfiguration{}
}

// WithTemplateRef sets the TemplateRef field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the TemplateRef field is set to the value of the last call.
func (b *MachinePoolClassInfrastructureTemplateApplyConfiguration) WithTemplateRef(value *ClusterClassTemplateReferenceApplyConfiguration) *MachinePoolClassInfrastructureTemplateApplyConfiguration {
	b.TemplateRef = value
	return b
}
