// Code generated by controller-gen-v0.20.1-0. DO NOT EDIT.

package v1beta2

import (
	corev1beta2 "sigs.k8s.io/cluster-api/api/core/v1beta2"
)

// MachineHealthCheckV1Beta1DeprecatedStatusApplyConfiguration represents a declarative configuration of the MachineHealthCheckV1Beta1DeprecatedStatus type for use
// with apply.
//
// MachineHealthCheckV1Beta1DeprecatedStatus groups all the status fields that are deprecated and will be removed when support for v1beta1 will be dropped.
// See https://github.com/kubernetes-sigs/cluster-api/blob/main/docs/proposals/20240916-improve-status-in-CAPI-resources.md for more context.
type MachineHealthCheckV1Beta1DeprecatedStatusApplyConfiguration struct {
	// conditions defines current service state of the MachineHealthCheck.
	//
	// Deprecated: This field is deprecated and is going to be removed when support for v1beta1 will be dropped. Please see https://github.com/kubernetes-sigs/cluster-api/blob/main/docs/proposals/20240916-improve-status-in-CAPI-resources.md for more details.
	Conditions *corev1beta2.Conditions `json:"conditions,omitempty"`
}

// MachineHealthCheckV1Beta1DeprecatedStatusApplyConfiguration constructs a declarative configuration of the MachineHealthCheckV1Beta1DeprecatedStatus type for use with
// apply.
func MachineHealthCheckV1Beta1DeprecatedStatus() *MachineHealthCheckV1Beta1DeprecatedStatusApplyConfiguration {
	return &MachineHealthCheckV1Beta1DeprecatedStatusApplyConfiguration{}
}

// WithConditions sets the Conditions field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the Conditions field is set to the value of the last call.
func (b *MachineHealthCheckV1Beta1DeprecatedStatusApplyConfiguration) WithConditions(value corev1beta2.Conditions) *MachineHealthCheckV1Beta1DeprecatedStatusApplyConfiguration {
	b.Conditions = &value
	return b
}
