// Code generated by controller-gen-v0.20.1-0. DO NOT EDIT.

package v1beta2

import (
	v1 "k8s.io/client-go/applyconfigurations/meta/v1"
)

// MachineDrainRulePodSelectorApplyConfiguration represents a declarative configuration of the MachineDrainRulePodSelector type for use
// with apply.
//
// MachineDrainRulePodSelector defines to which Pods this MachineDrainRule should be applied.
type MachineDrainRulePodSelectorApplyConfiguration struct {
	// selector is a label selector which selects Pods by their labels.
	// This field follows standard label selector semantics; if not present or
	// empty, it selects all Pods.
	//
	// If namespaceSelector is also set, then the selector as a whole selects
	// Pods matching selector in Namespaces selected by namespaceSelector.
	// If namespaceSelector is not set, it selects all Pods matching selector in
	// all Namespaces.
	Selector *v1.LabelSelectorApplyConfiguration `json:"selector,omitempty"`
	// namespaceSelector is a label selector which selects Pods by the labels of
	// their Namespaces.
	// This field follows standard label selector semantics; if not present or
	// empty, it selects Pods of all Namespaces.
	//
	// If selector is also set, then the selector as a whole selects
	// Pods matching selector in Namespaces selected by namespaceSelector.
	// If selector is not set, it selects all Pods in Namespaces selected by
	// namespaceSelector.
	NamespaceSelector *v1.LabelSelectorApplyConfiguration `json:"namespaceSelector,omitempty"`
}

// MachineDrainRulePodSelectorApplyConfiguration constructs a declarative configuration of the MachineDrainRulePodSelector type for use with
// apply.
func MachineDrainRulePodSelector() *MachineDrainRulePodSelectorApplyConfiguration {
	return &MachineDrainRulePodSelectorApplyConfiguration{}
}

// WithSelector sets the Selector field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the Selector field is set to the value of the last call.
func (b *MachineDrainRulePodSelectorApplyConfiguration) WithSelector(value *v1.LabelSelectorApplyConfiguration) *MachineDrainRulePodSelectorApplyConfiguration {
	b.Selector = value
	return b
}

// WithNamespaceSelector sets the NamespaceSelector field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the NamespaceSelector field is set to the value of the last call.
func (b *MachineDrainRulePodSelectorApplyConfiguration) WithNamespaceSelector(value *v1.LabelSelectorApplyConfiguration) *MachineDrainRulePodSelectorApplyConfiguration {
	b.NamespaceSelector = value
	return b
}
