// Code generated by controller-gen-v0.21. DO NOT EDIT.

package v1beta2

import (
	v1 "k8s.io/apimachinery/pkg/apis/meta/v1"
)

// MachineDeploymentTopologyRolloutSpecApplyConfiguration represents a declarative configuration of the MachineDeploymentTopologyRolloutSpec type for use
// with apply.
//
// MachineDeploymentTopologyRolloutSpec defines the rollout behavior.
type MachineDeploymentTopologyRolloutSpecApplyConfiguration struct {
	// after is a field to indicate a rollout should be performed
	// after the specified time even if no changes have been made to the
	// MachineDeployment.
	// Example: In the YAML the time can be specified in the RFC3339 format.
	// To specify the rolloutAfter target as March 9, 2023, at 9 am UTC
	// use "2023-03-09T09:00:00Z".
	After *v1.Time `json:"after,omitempty"`
	// strategy specifies how to roll out control plane Machines.
	Strategy *MachineDeploymentTopologyRolloutStrategyApplyConfiguration `json:"strategy,omitempty"`
}

// MachineDeploymentTopologyRolloutSpecApplyConfiguration constructs a declarative configuration of the MachineDeploymentTopologyRolloutSpec type for use with
// apply.
func MachineDeploymentTopologyRolloutSpec() *MachineDeploymentTopologyRolloutSpecApplyConfiguration {
	return &MachineDeploymentTopologyRolloutSpecApplyConfiguration{}
}

// WithAfter sets the After field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the After field is set to the value of the last call.
func (b *MachineDeploymentTopologyRolloutSpecApplyConfiguration) WithAfter(value v1.Time) *MachineDeploymentTopologyRolloutSpecApplyConfiguration {
	b.After = &value
	return b
}

// WithStrategy sets the Strategy field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the Strategy field is set to the value of the last call.
func (b *MachineDeploymentTopologyRolloutSpecApplyConfiguration) WithStrategy(value *MachineDeploymentTopologyRolloutStrategyApplyConfiguration) *MachineDeploymentTopologyRolloutSpecApplyConfiguration {
	b.Strategy = value
	return b
}
