// Code generated by controller-gen-v0.20.1-0. DO NOT EDIT.

package v1beta2

// MachineDeprecatedStatusApplyConfiguration represents a declarative configuration of the MachineDeprecatedStatus type for use
// with apply.
//
// MachineDeprecatedStatus groups all the status fields that are deprecated and will be removed in a future version.
// See https://github.com/kubernetes-sigs/cluster-api/blob/main/docs/proposals/20240916-improve-status-in-CAPI-resources.md for more context.
type MachineDeprecatedStatusApplyConfiguration struct {
	// v1beta1 groups all the status fields that are deprecated and will be removed when support for v1beta1 will be dropped.
	//
	// Deprecated: This field is deprecated and is going to be removed when support for v1beta1 will be dropped. Please see https://github.com/kubernetes-sigs/cluster-api/blob/main/docs/proposals/20240916-improve-status-in-CAPI-resources.md for more details.
	V1Beta1 *MachineV1Beta1DeprecatedStatusApplyConfiguration `json:"v1beta1,omitempty"`
}

// MachineDeprecatedStatusApplyConfiguration constructs a declarative configuration of the MachineDeprecatedStatus type for use with
// apply.
func MachineDeprecatedStatus() *MachineDeprecatedStatusApplyConfiguration {
	return &MachineDeprecatedStatusApplyConfiguration{}
}

// WithV1Beta1 sets the V1Beta1 field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the V1Beta1 field is set to the value of the last call.
func (b *MachineDeprecatedStatusApplyConfiguration) WithV1Beta1(value *MachineV1Beta1DeprecatedStatusApplyConfiguration) *MachineDeprecatedStatusApplyConfiguration {
	b.V1Beta1 = value
	return b
}
