// Code generated by controller-gen-v0.20.1-0. DO NOT EDIT.

package v1beta2

import (
	v1 "k8s.io/client-go/applyconfigurations/meta/v1"
)

// MachineHealthCheckSpecApplyConfiguration represents a declarative configuration of the MachineHealthCheckSpec type for use
// with apply.
//
// MachineHealthCheckSpec defines the desired state of MachineHealthCheck.
type MachineHealthCheckSpecApplyConfiguration struct {
	// clusterName is the name of the Cluster this object belongs to.
	ClusterName *string `json:"clusterName,omitempty"`
	// selector is a label selector to match machines whose health will be exercised
	Selector *v1.LabelSelectorApplyConfiguration `json:"selector,omitempty"`
	// checks are the checks that are used to evaluate if a Machine is healthy.
	//
	// Independent of this configuration the MachineHealthCheck controller will always
	// flag Machines with `cluster.x-k8s.io/remediate-machine` annotation and
	// Machines with deleted Nodes as unhealthy.
	//
	// Furthermore, if checks.nodeStartupTimeoutSeconds is not set it
	// is defaulted to 10 minutes and evaluated accordingly.
	Checks *MachineHealthCheckChecksApplyConfiguration `json:"checks,omitempty"`
	// remediation configures if and how remediations are triggered if a Machine is unhealthy.
	//
	// If remediation or remediation.triggerIf is not set,
	// remediation will always be triggered for unhealthy Machines.
	//
	// If remediation or remediation.templateRef is not set,
	// the OwnerRemediated condition will be set on unhealthy Machines to trigger remediation via
	// the owner of the Machines, for example a MachineSet or a KubeadmControlPlane.
	Remediation *MachineHealthCheckRemediationApplyConfiguration `json:"remediation,omitempty"`
}

// MachineHealthCheckSpecApplyConfiguration constructs a declarative configuration of the MachineHealthCheckSpec type for use with
// apply.
func MachineHealthCheckSpec() *MachineHealthCheckSpecApplyConfiguration {
	return &MachineHealthCheckSpecApplyConfiguration{}
}

// WithClusterName sets the ClusterName field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the ClusterName field is set to the value of the last call.
func (b *MachineHealthCheckSpecApplyConfiguration) WithClusterName(value string) *MachineHealthCheckSpecApplyConfiguration {
	b.ClusterName = &value
	return b
}

// WithSelector sets the Selector field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the Selector field is set to the value of the last call.
func (b *MachineHealthCheckSpecApplyConfiguration) WithSelector(value *v1.LabelSelectorApplyConfiguration) *MachineHealthCheckSpecApplyConfiguration {
	b.Selector = value
	return b
}

// WithChecks sets the Checks field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the Checks field is set to the value of the last call.
func (b *MachineHealthCheckSpecApplyConfiguration) WithChecks(value *MachineHealthCheckChecksApplyConfiguration) *MachineHealthCheckSpecApplyConfiguration {
	b.Checks = value
	return b
}

// WithRemediation sets the Remediation field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the Remediation field is set to the value of the last call.
func (b *MachineHealthCheckSpecApplyConfiguration) WithRemediation(value *MachineHealthCheckRemediationApplyConfiguration) *MachineHealthCheckSpecApplyConfiguration {
	b.Remediation = value
	return b
}
