// Code generated by controller-gen-v0.20.1-0. DO NOT EDIT.

package v1beta2

import (
	intstr "k8s.io/apimachinery/pkg/util/intstr"
)

// MachineDeploymentClassRolloutStrategyRollingUpdateApplyConfiguration represents a declarative configuration of the MachineDeploymentClassRolloutStrategyRollingUpdate type for use
// with apply.
//
// MachineDeploymentClassRolloutStrategyRollingUpdate is used to control the desired behavior of rolling update.
type MachineDeploymentClassRolloutStrategyRollingUpdateApplyConfiguration struct {
	// maxUnavailable is the maximum number of machines that can be unavailable during the update.
	// Value can be an absolute number (ex: 5) or a percentage of desired
	// machines (ex: 10%).
	// Absolute number is calculated from percentage by rounding down.
	// This can not be 0 if MaxSurge is 0.
	// Defaults to 0.
	// Example: when this is set to 30%, the old MachineSet can be scaled
	// down to 70% of desired machines immediately when the rolling update
	// starts. Once new machines are ready, old MachineSet can be scaled
	// down further, followed by scaling up the new MachineSet, ensuring
	// that the total number of machines available at all times
	// during the update is at least 70% of desired machines.
	MaxUnavailable *intstr.IntOrString `json:"maxUnavailable,omitempty"`
	// maxSurge is the maximum number of machines that can be scheduled above the
	// desired number of machines.
	// Value can be an absolute number (ex: 5) or a percentage of
	// desired machines (ex: 10%).
	// This can not be 0 if MaxUnavailable is 0.
	// Absolute number is calculated from percentage by rounding up.
	// Defaults to 1.
	// Example: when this is set to 30%, the new MachineSet can be scaled
	// up immediately when the rolling update starts, such that the total
	// number of old and new machines do not exceed 130% of desired
	// machines. Once old machines have been killed, new MachineSet can
	// be scaled up further, ensuring that total number of machines running
	// at any time during the update is at most 130% of desired machines.
	MaxSurge *intstr.IntOrString `json:"maxSurge,omitempty"`
}

// MachineDeploymentClassRolloutStrategyRollingUpdateApplyConfiguration constructs a declarative configuration of the MachineDeploymentClassRolloutStrategyRollingUpdate type for use with
// apply.
func MachineDeploymentClassRolloutStrategyRollingUpdate() *MachineDeploymentClassRolloutStrategyRollingUpdateApplyConfiguration {
	return &MachineDeploymentClassRolloutStrategyRollingUpdateApplyConfiguration{}
}

// WithMaxUnavailable sets the MaxUnavailable field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the MaxUnavailable field is set to the value of the last call.
func (b *MachineDeploymentClassRolloutStrategyRollingUpdateApplyConfiguration) WithMaxUnavailable(value intstr.IntOrString) *MachineDeploymentClassRolloutStrategyRollingUpdateApplyConfiguration {
	b.MaxUnavailable = &value
	return b
}

// WithMaxSurge sets the MaxSurge field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the MaxSurge field is set to the value of the last call.
func (b *MachineDeploymentClassRolloutStrategyRollingUpdateApplyConfiguration) WithMaxSurge(value intstr.IntOrString) *MachineDeploymentClassRolloutStrategyRollingUpdateApplyConfiguration {
	b.MaxSurge = &value
	return b
}
