// Code generated by controller-gen-v0.20.1-0. DO NOT EDIT.

package v1beta2

import (
	corev1beta2 "sigs.k8s.io/cluster-api/api/core/v1beta2"
)

// MachineDrainRuleDrainConfigApplyConfiguration represents a declarative configuration of the MachineDrainRuleDrainConfig type for use
// with apply.
//
// MachineDrainRuleDrainConfig configures if and how Pods are drained.
type MachineDrainRuleDrainConfigApplyConfiguration struct {
	// behavior defines the drain behavior.
	// Can be either "Drain", "Skip", or "WaitCompleted".
	// "Drain" means that the Pods to which this MachineDrainRule applies will be drained.
	// If behavior is set to "Drain" the order in which Pods are drained can be configured
	// with the order field. When draining Pods of a Node the Pods will be grouped by order
	// and one group after another will be drained (by increasing order). Cluster API will
	// wait until all Pods of a group are terminated / removed from the Node before starting
	// with the next group.
	// "Skip" means that the Pods to which this MachineDrainRule applies will be skipped during drain.
	// "WaitCompleted" means that the pods to which this MachineDrainRule applies will never be evicted
	// and we wait for them to be completed, it is enforced that pods marked with this behavior always have Order=0.
	Behavior *corev1beta2.MachineDrainRuleDrainBehavior `json:"behavior,omitempty"`
	// order defines the order in which Pods are drained.
	// Pods with higher order are drained after Pods with lower order.
	// order can only be set if behavior is set to "Drain".
	// If order is not set, 0 will be used.
	// Valid values for order are from -2147483648 to 2147483647 (inclusive).
	Order *int32 `json:"order,omitempty"`
}

// MachineDrainRuleDrainConfigApplyConfiguration constructs a declarative configuration of the MachineDrainRuleDrainConfig type for use with
// apply.
func MachineDrainRuleDrainConfig() *MachineDrainRuleDrainConfigApplyConfiguration {
	return &MachineDrainRuleDrainConfigApplyConfiguration{}
}

// WithBehavior sets the Behavior field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the Behavior field is set to the value of the last call.
func (b *MachineDrainRuleDrainConfigApplyConfiguration) WithBehavior(value corev1beta2.MachineDrainRuleDrainBehavior) *MachineDrainRuleDrainConfigApplyConfiguration {
	b.Behavior = &value
	return b
}

// WithOrder sets the Order field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the Order field is set to the value of the last call.
func (b *MachineDrainRuleDrainConfigApplyConfiguration) WithOrder(value int32) *MachineDrainRuleDrainConfigApplyConfiguration {
	b.Order = &value
	return b
}
