// Code generated by controller-gen-v0.20.1-0. DO NOT EDIT.

package v1beta2

// MachineDrainRuleSpecApplyConfiguration represents a declarative configuration of the MachineDrainRuleSpec type for use
// with apply.
//
// MachineDrainRuleSpec defines the spec of a MachineDrainRule.
type MachineDrainRuleSpecApplyConfiguration struct {
	// drain configures if and how Pods are drained.
	Drain *MachineDrainRuleDrainConfigApplyConfiguration `json:"drain,omitempty"`
	// machines defines to which Machines this MachineDrainRule should be applied.
	//
	// If machines is not set, the MachineDrainRule applies to all Machines in the Namespace.
	// If machines contains multiple selectors, the results are ORed.
	// Within a single Machine selector the results of selector and clusterSelector are ANDed.
	// Machines will be selected from all Clusters in the Namespace unless otherwise
	// restricted with the clusterSelector.
	//
	// Example: Selects control plane Machines in all Clusters or
	// Machines with label "os" == "linux" in Clusters with label
	// "stage" == "production".
	//
	// - selector:
	// matchExpressions:
	// - key: cluster.x-k8s.io/control-plane
	// operator: Exists
	// - selector:
	// matchLabels:
	// os: linux
	// clusterSelector:
	// matchExpressions:
	// - key: stage
	// operator: In
	// values:
	// - production
	Machines []MachineDrainRuleMachineSelectorApplyConfiguration `json:"machines,omitempty"`
	// pods defines to which Pods this MachineDrainRule should be applied.
	//
	// If pods is not set, the MachineDrainRule applies to all Pods in all Namespaces.
	// If pods contains multiple selectors, the results are ORed.
	// Within a single Pod selector the results of selector and namespaceSelector are ANDed.
	// Pods will be selected from all Namespaces unless otherwise
	// restricted with the namespaceSelector.
	//
	// Example: Selects Pods with label "app" == "logging" in all Namespaces or
	// Pods with label "app" == "prometheus" in the "monitoring"
	// Namespace.
	//
	// - selector:
	// matchExpressions:
	// - key: app
	// operator: In
	// values:
	// - logging
	// - selector:
	// matchLabels:
	// app: prometheus
	// namespaceSelector:
	// matchLabels:
	// kubernetes.io/metadata.name: monitoring
	Pods []MachineDrainRulePodSelectorApplyConfiguration `json:"pods,omitempty"`
}

// MachineDrainRuleSpecApplyConfiguration constructs a declarative configuration of the MachineDrainRuleSpec type for use with
// apply.
func MachineDrainRuleSpec() *MachineDrainRuleSpecApplyConfiguration {
	return &MachineDrainRuleSpecApplyConfiguration{}
}

// WithDrain sets the Drain field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the Drain field is set to the value of the last call.
func (b *MachineDrainRuleSpecApplyConfiguration) WithDrain(value *MachineDrainRuleDrainConfigApplyConfiguration) *MachineDrainRuleSpecApplyConfiguration {
	b.Drain = value
	return b
}

// WithMachines adds the given value to the Machines field in the declarative configuration
// and returns the receiver, so that objects can be build by chaining "With" function invocations.
// If called multiple times, values provided by each call will be appended to the Machines field.
func (b *MachineDrainRuleSpecApplyConfiguration) WithMachines(values ...*MachineDrainRuleMachineSelectorApplyConfiguration) *MachineDrainRuleSpecApplyConfiguration {
	for i := range values {
		if values[i] == nil {
			panic("nil value passed to WithMachines")
		}
		b.Machines = append(b.Machines, *values[i])
	}
	return b
}

// WithPods adds the given value to the Pods field in the declarative configuration
// and returns the receiver, so that objects can be build by chaining "With" function invocations.
// If called multiple times, values provided by each call will be appended to the Pods field.
func (b *MachineDrainRuleSpecApplyConfiguration) WithPods(values ...*MachineDrainRulePodSelectorApplyConfiguration) *MachineDrainRuleSpecApplyConfiguration {
	for i := range values {
		if values[i] == nil {
			panic("nil value passed to WithPods")
		}
		b.Pods = append(b.Pods, *values[i])
	}
	return b
}
