// Code generated by controller-gen-v0.20.1-0. DO NOT EDIT.

package v1beta2

import (
	corev1beta2 "sigs.k8s.io/cluster-api/api/core/v1beta2"
)

// MachineDeploymentDeletionSpecApplyConfiguration represents a declarative configuration of the MachineDeploymentDeletionSpec type for use
// with apply.
//
// MachineDeploymentDeletionSpec contains configuration options for MachineDeployment deletion.
type MachineDeploymentDeletionSpecApplyConfiguration struct {
	// order defines the order in which Machines are deleted when downscaling.
	// Defaults to "Random".  Valid values are "Random, "Newest", "Oldest"
	Order *corev1beta2.MachineSetDeletionOrder `json:"order,omitempty"`
}

// MachineDeploymentDeletionSpecApplyConfiguration constructs a declarative configuration of the MachineDeploymentDeletionSpec type for use with
// apply.
func MachineDeploymentDeletionSpec() *MachineDeploymentDeletionSpecApplyConfiguration {
	return &MachineDeploymentDeletionSpecApplyConfiguration{}
}

// WithOrder sets the Order field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the Order field is set to the value of the last call.
func (b *MachineDeploymentDeletionSpecApplyConfiguration) WithOrder(value corev1beta2.MachineSetDeletionOrder) *MachineDeploymentDeletionSpecApplyConfiguration {
	b.Order = &value
	return b
}
