// Code generated by controller-gen-v0.20.1-0. DO NOT EDIT.

package v1beta2

// MachineDeploymentTopologyRolloutSpecApplyConfiguration represents a declarative configuration of the MachineDeploymentTopologyRolloutSpec type for use
// with apply.
//
// MachineDeploymentTopologyRolloutSpec defines the rollout behavior.
type MachineDeploymentTopologyRolloutSpecApplyConfiguration struct {
	// strategy specifies how to roll out control plane Machines.
	Strategy *MachineDeploymentTopologyRolloutStrategyApplyConfiguration `json:"strategy,omitempty"`
}

// MachineDeploymentTopologyRolloutSpecApplyConfiguration constructs a declarative configuration of the MachineDeploymentTopologyRolloutSpec type for use with
// apply.
func MachineDeploymentTopologyRolloutSpec() *MachineDeploymentTopologyRolloutSpecApplyConfiguration {
	return &MachineDeploymentTopologyRolloutSpecApplyConfiguration{}
}

// WithStrategy sets the Strategy field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the Strategy field is set to the value of the last call.
func (b *MachineDeploymentTopologyRolloutSpecApplyConfiguration) WithStrategy(value *MachineDeploymentTopologyRolloutStrategyApplyConfiguration) *MachineDeploymentTopologyRolloutSpecApplyConfiguration {
	b.Strategy = value
	return b
}
