// Code generated by controller-gen-v0.20.1-0. DO NOT EDIT.

package v1beta2

// MachineDeploymentClassHealthCheckApplyConfiguration represents a declarative configuration of the MachineDeploymentClassHealthCheck type for use
// with apply.
//
// MachineDeploymentClassHealthCheck defines a MachineHealthCheck for MachineDeployment machines.
type MachineDeploymentClassHealthCheckApplyConfiguration struct {
	// checks are the checks that are used to evaluate if a Machine is healthy.
	//
	// Independent of this configuration the MachineHealthCheck controller will always
	// flag Machines with `cluster.x-k8s.io/remediate-machine` annotation and
	// Machines with deleted Nodes as unhealthy.
	//
	// Furthermore, if checks.nodeStartupTimeoutSeconds is not set it
	// is defaulted to 10 minutes and evaluated accordingly.
	Checks *MachineDeploymentClassHealthCheckChecksApplyConfiguration `json:"checks,omitempty"`
	// remediation configures if and how remediations are triggered if a Machine is unhealthy.
	//
	// If remediation or remediation.triggerIf is not set,
	// remediation will always be triggered for unhealthy Machines.
	//
	// If remediation or remediation.templateRef is not set,
	// the OwnerRemediated condition will be set on unhealthy Machines to trigger remediation via
	// the owner of the Machines, for example a MachineSet or a KubeadmControlPlane.
	Remediation *MachineDeploymentClassHealthCheckRemediationApplyConfiguration `json:"remediation,omitempty"`
}

// MachineDeploymentClassHealthCheckApplyConfiguration constructs a declarative configuration of the MachineDeploymentClassHealthCheck type for use with
// apply.
func MachineDeploymentClassHealthCheck() *MachineDeploymentClassHealthCheckApplyConfiguration {
	return &MachineDeploymentClassHealthCheckApplyConfiguration{}
}

// WithChecks sets the Checks field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the Checks field is set to the value of the last call.
func (b *MachineDeploymentClassHealthCheckApplyConfiguration) WithChecks(value *MachineDeploymentClassHealthCheckChecksApplyConfiguration) *MachineDeploymentClassHealthCheckApplyConfiguration {
	b.Checks = value
	return b
}

// WithRemediation sets the Remediation field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the Remediation field is set to the value of the last call.
func (b *MachineDeploymentClassHealthCheckApplyConfiguration) WithRemediation(value *MachineDeploymentClassHealthCheckRemediationApplyConfiguration) *MachineDeploymentClassHealthCheckApplyConfiguration {
	b.Remediation = value
	return b
}
