// Code generated by controller-gen-v0.20.1-0. DO NOT EDIT.

package v1beta2

import (
	corev1beta2 "sigs.k8s.io/cluster-api/api/core/v1beta2"
)

// MachineSetDeletionSpecApplyConfiguration represents a declarative configuration of the MachineSetDeletionSpec type for use
// with apply.
//
// MachineSetDeletionSpec contains configuration options for MachineSet deletion.
type MachineSetDeletionSpecApplyConfiguration struct {
	// order defines the order in which Machines are deleted when downscaling.
	// Defaults to "Random".  Valid values are "Random, "Newest", "Oldest"
	Order *corev1beta2.MachineSetDeletionOrder `json:"order,omitempty"`
}

// MachineSetDeletionSpecApplyConfiguration constructs a declarative configuration of the MachineSetDeletionSpec type for use with
// apply.
func MachineSetDeletionSpec() *MachineSetDeletionSpecApplyConfiguration {
	return &MachineSetDeletionSpecApplyConfiguration{}
}

// WithOrder sets the Order field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the Order field is set to the value of the last call.
func (b *MachineSetDeletionSpecApplyConfiguration) WithOrder(value corev1beta2.MachineSetDeletionOrder) *MachineSetDeletionSpecApplyConfiguration {
	b.Order = &value
	return b
}
