// Code generated by controller-gen-v0.20.1-0. DO NOT EDIT.

package v1beta2

import (
	corev1beta2 "sigs.k8s.io/cluster-api/api/core/v1beta2"
)

// MachineDeploymentTopologyRolloutStrategyApplyConfiguration represents a declarative configuration of the MachineDeploymentTopologyRolloutStrategy type for use
// with apply.
//
// MachineDeploymentTopologyRolloutStrategy describes how to replace existing machines
// with new ones.
type MachineDeploymentTopologyRolloutStrategyApplyConfiguration struct {
	// type of rollout. Allowed values are RollingUpdate and OnDelete.
	// Default is RollingUpdate.
	Type *corev1beta2.MachineDeploymentRolloutStrategyType `json:"type,omitempty"`
	// rollingUpdate is the rolling update config params. Present only if
	// type = RollingUpdate.
	RollingUpdate *MachineDeploymentTopologyRolloutStrategyRollingUpdateApplyConfiguration `json:"rollingUpdate,omitempty"`
}

// MachineDeploymentTopologyRolloutStrategyApplyConfiguration constructs a declarative configuration of the MachineDeploymentTopologyRolloutStrategy type for use with
// apply.
func MachineDeploymentTopologyRolloutStrategy() *MachineDeploymentTopologyRolloutStrategyApplyConfiguration {
	return &MachineDeploymentTopologyRolloutStrategyApplyConfiguration{}
}

// WithType sets the Type field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the Type field is set to the value of the last call.
func (b *MachineDeploymentTopologyRolloutStrategyApplyConfiguration) WithType(value corev1beta2.MachineDeploymentRolloutStrategyType) *MachineDeploymentTopologyRolloutStrategyApplyConfiguration {
	b.Type = &value
	return b
}

// WithRollingUpdate sets the RollingUpdate field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the RollingUpdate field is set to the value of the last call.
func (b *MachineDeploymentTopologyRolloutStrategyApplyConfiguration) WithRollingUpdate(value *MachineDeploymentTopologyRolloutStrategyRollingUpdateApplyConfiguration) *MachineDeploymentTopologyRolloutStrategyApplyConfiguration {
	b.RollingUpdate = value
	return b
}
