// Code generated by controller-gen-v0.20.1-0. DO NOT EDIT.

package v1beta2

// MachinePoolVariablesApplyConfiguration represents a declarative configuration of the MachinePoolVariables type for use
// with apply.
//
// MachinePoolVariables can be used to provide variables for a specific MachinePool.
type MachinePoolVariablesApplyConfiguration struct {
	// overrides can be used to override Cluster level variables.
	Overrides []ClusterVariableApplyConfiguration `json:"overrides,omitempty"`
}

// MachinePoolVariablesApplyConfiguration constructs a declarative configuration of the MachinePoolVariables type for use with
// apply.
func MachinePoolVariables() *MachinePoolVariablesApplyConfiguration {
	return &MachinePoolVariablesApplyConfiguration{}
}

// WithOverrides adds the given value to the Overrides field in the declarative configuration
// and returns the receiver, so that objects can be build by chaining "With" function invocations.
// If called multiple times, values provided by each call will be appended to the Overrides field.
func (b *MachinePoolVariablesApplyConfiguration) WithOverrides(values ...*ClusterVariableApplyConfiguration) *MachinePoolVariablesApplyConfiguration {
	for i := range values {
		if values[i] == nil {
			panic("nil value passed to WithOverrides")
		}
		b.Overrides = append(b.Overrides, *values[i])
	}
	return b
}
