// Code generated by controller-gen-v0.20.1-0. DO NOT EDIT.

package v1beta2

import (
	v1 "k8s.io/apimachinery/pkg/apis/meta/v1"
)

// MachineDeletionStatusApplyConfiguration represents a declarative configuration of the MachineDeletionStatus type for use
// with apply.
//
// MachineDeletionStatus is the deletion state of the Machine.
type MachineDeletionStatusApplyConfiguration struct {
	// nodeDrainStartTime is the time when the drain of the node started and is used to determine
	// if the nodeDrainTimeoutSeconds is exceeded.
	// Only present when the Machine has a deletionTimestamp and draining the node had been started.
	NodeDrainStartTime *v1.Time `json:"nodeDrainStartTime,omitempty"`
	// waitForNodeVolumeDetachStartTime is the time when waiting for volume detachment started
	// and is used to determine if the nodeVolumeDetachTimeoutSeconds is exceeded.
	// Detaching volumes from nodes is usually done by CSI implementations and the current state
	// is observed from the node's `.Status.VolumesAttached` field.
	// Only present when the Machine has a deletionTimestamp and waiting for volume detachments had been started.
	WaitForNodeVolumeDetachStartTime *v1.Time `json:"waitForNodeVolumeDetachStartTime,omitempty"`
}

// MachineDeletionStatusApplyConfiguration constructs a declarative configuration of the MachineDeletionStatus type for use with
// apply.
func MachineDeletionStatus() *MachineDeletionStatusApplyConfiguration {
	return &MachineDeletionStatusApplyConfiguration{}
}

// WithNodeDrainStartTime sets the NodeDrainStartTime field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the NodeDrainStartTime field is set to the value of the last call.
func (b *MachineDeletionStatusApplyConfiguration) WithNodeDrainStartTime(value v1.Time) *MachineDeletionStatusApplyConfiguration {
	b.NodeDrainStartTime = &value
	return b
}

// WithWaitForNodeVolumeDetachStartTime sets the WaitForNodeVolumeDetachStartTime field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the WaitForNodeVolumeDetachStartTime field is set to the value of the last call.
func (b *MachineDeletionStatusApplyConfiguration) WithWaitForNodeVolumeDetachStartTime(value v1.Time) *MachineDeletionStatusApplyConfiguration {
	b.WaitForNodeVolumeDetachStartTime = &value
	return b
}
