// Code generated by controller-gen-v0.20.1-0. DO NOT EDIT.

package v1beta2

// NetworkRangesApplyConfiguration represents a declarative configuration of the NetworkRanges type for use
// with apply.
//
// NetworkRanges represents ranges of network addresses.
type NetworkRangesApplyConfiguration struct {
	// cidrBlocks is a list of CIDR blocks.
	CIDRBlocks []string `json:"cidrBlocks,omitempty"`
}

// NetworkRangesApplyConfiguration constructs a declarative configuration of the NetworkRanges type for use with
// apply.
func NetworkRanges() *NetworkRangesApplyConfiguration {
	return &NetworkRangesApplyConfiguration{}
}

// WithCIDRBlocks adds the given value to the CIDRBlocks field in the declarative configuration
// and returns the receiver, so that objects can be build by chaining "With" function invocations.
// If called multiple times, values provided by each call will be appended to the CIDRBlocks field.
func (b *NetworkRangesApplyConfiguration) WithCIDRBlocks(values ...string) *NetworkRangesApplyConfiguration {
	for i := range values {
		b.CIDRBlocks = append(b.CIDRBlocks, values[i])
	}
	return b
}
