// Code generated by controller-gen-v0.20.1-0. DO NOT EDIT.

package v1beta2

// PatchSelectorMatchMachinePoolClassApplyConfiguration represents a declarative configuration of the PatchSelectorMatchMachinePoolClass type for use
// with apply.
//
// PatchSelectorMatchMachinePoolClass selects templates referenced
// in specific MachinePoolClasses in .spec.workers.machinePools.
type PatchSelectorMatchMachinePoolClassApplyConfiguration struct {
	// names selects templates by class names.
	Names []string `json:"names,omitempty"`
}

// PatchSelectorMatchMachinePoolClassApplyConfiguration constructs a declarative configuration of the PatchSelectorMatchMachinePoolClass type for use with
// apply.
func PatchSelectorMatchMachinePoolClass() *PatchSelectorMatchMachinePoolClassApplyConfiguration {
	return &PatchSelectorMatchMachinePoolClassApplyConfiguration{}
}

// WithNames adds the given value to the Names field in the declarative configuration
// and returns the receiver, so that objects can be build by chaining "With" function invocations.
// If called multiple times, values provided by each call will be appended to the Names field.
func (b *PatchSelectorMatchMachinePoolClassApplyConfiguration) WithNames(values ...string) *PatchSelectorMatchMachinePoolClassApplyConfiguration {
	for i := range values {
		b.Names = append(b.Names, values[i])
	}
	return b
}
