// Code generated by controller-gen-v0.20.1-0. DO NOT EDIT.

package v1beta2

// PatchSelectorMatchMachineDeploymentClassApplyConfiguration represents a declarative configuration of the PatchSelectorMatchMachineDeploymentClass type for use
// with apply.
//
// PatchSelectorMatchMachineDeploymentClass selects templates referenced
// in specific MachineDeploymentClasses in .spec.workers.machineDeployments.
type PatchSelectorMatchMachineDeploymentClassApplyConfiguration struct {
	// names selects templates by class names.
	Names []string `json:"names,omitempty"`
}

// PatchSelectorMatchMachineDeploymentClassApplyConfiguration constructs a declarative configuration of the PatchSelectorMatchMachineDeploymentClass type for use with
// apply.
func PatchSelectorMatchMachineDeploymentClass() *PatchSelectorMatchMachineDeploymentClassApplyConfiguration {
	return &PatchSelectorMatchMachineDeploymentClassApplyConfiguration{}
}

// WithNames adds the given value to the Names field in the declarative configuration
// and returns the receiver, so that objects can be build by chaining "With" function invocations.
// If called multiple times, values provided by each call will be appended to the Names field.
func (b *PatchSelectorMatchMachineDeploymentClassApplyConfiguration) WithNames(values ...string) *PatchSelectorMatchMachineDeploymentClassApplyConfiguration {
	for i := range values {
		b.Names = append(b.Names, values[i])
	}
	return b
}
