// Code generated by controller-gen-v0.20.1-0. DO NOT EDIT.

package v1beta2

// PatchSelectorMatchApplyConfiguration represents a declarative configuration of the PatchSelectorMatch type for use
// with apply.
//
// PatchSelectorMatch selects templates based on where they are referenced.
// Note: The selector must match at least one template.
// Note: The results of selection based on the individual fields are ORed.
type PatchSelectorMatchApplyConfiguration struct {
	// controlPlane selects templates referenced in .spec.ControlPlane.
	// Note: this will match the controlPlane and also the controlPlane
	// machineInfrastructure (depending on the kind and apiVersion).
	ControlPlane *bool `json:"controlPlane,omitempty"`
	// infrastructureCluster selects templates referenced in .spec.infrastructure.
	InfrastructureCluster *bool `json:"infrastructureCluster,omitempty"`
	// machineDeploymentClass selects templates referenced in specific MachineDeploymentClasses in
	// .spec.workers.machineDeployments.
	MachineDeploymentClass *PatchSelectorMatchMachineDeploymentClassApplyConfiguration `json:"machineDeploymentClass,omitempty"`
	// machinePoolClass selects templates referenced in specific MachinePoolClasses in
	// .spec.workers.machinePools.
	MachinePoolClass *PatchSelectorMatchMachinePoolClassApplyConfiguration `json:"machinePoolClass,omitempty"`
}

// PatchSelectorMatchApplyConfiguration constructs a declarative configuration of the PatchSelectorMatch type for use with
// apply.
func PatchSelectorMatch() *PatchSelectorMatchApplyConfiguration {
	return &PatchSelectorMatchApplyConfiguration{}
}

// WithControlPlane sets the ControlPlane field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the ControlPlane field is set to the value of the last call.
func (b *PatchSelectorMatchApplyConfiguration) WithControlPlane(value bool) *PatchSelectorMatchApplyConfiguration {
	b.ControlPlane = &value
	return b
}

// WithInfrastructureCluster sets the InfrastructureCluster field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the InfrastructureCluster field is set to the value of the last call.
func (b *PatchSelectorMatchApplyConfiguration) WithInfrastructureCluster(value bool) *PatchSelectorMatchApplyConfiguration {
	b.InfrastructureCluster = &value
	return b
}

// WithMachineDeploymentClass sets the MachineDeploymentClass field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the MachineDeploymentClass field is set to the value of the last call.
func (b *PatchSelectorMatchApplyConfiguration) WithMachineDeploymentClass(value *PatchSelectorMatchMachineDeploymentClassApplyConfiguration) *PatchSelectorMatchApplyConfiguration {
	b.MachineDeploymentClass = value
	return b
}

// WithMachinePoolClass sets the MachinePoolClass field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the MachinePoolClass field is set to the value of the last call.
func (b *PatchSelectorMatchApplyConfiguration) WithMachinePoolClass(value *PatchSelectorMatchMachinePoolClassApplyConfiguration) *PatchSelectorMatchApplyConfiguration {
	b.MachinePoolClass = value
	return b
}
