// Code generated by controller-gen-v0.20.1-0. DO NOT EDIT.

package v1beta2

// PatchSelectorApplyConfiguration represents a declarative configuration of the PatchSelector type for use
// with apply.
//
// PatchSelector defines on which templates the patch should be applied.
// Note: Matching on APIVersion and Kind is mandatory, to enforce that the patches are
// written for the correct version. The version of the references in the ClusterClass may
// be automatically updated during reconciliation if there is a newer version for the same contract.
// Note: The results of selection based on the individual fields are ANDed.
type PatchSelectorApplyConfiguration struct {
	// apiVersion filters templates by apiVersion.
	// apiVersion must be fully qualified domain name followed by / and a version.
	APIVersion *string `json:"apiVersion,omitempty"`
	// kind filters templates by kind.
	// kind must consist of alphanumeric characters or '-', start with an alphabetic character, and end with an alphanumeric character.
	Kind *string `json:"kind,omitempty"`
	// matchResources selects templates based on where they are referenced.
	MatchResources *PatchSelectorMatchApplyConfiguration `json:"matchResources,omitempty"`
}

// PatchSelectorApplyConfiguration constructs a declarative configuration of the PatchSelector type for use with
// apply.
func PatchSelector() *PatchSelectorApplyConfiguration {
	return &PatchSelectorApplyConfiguration{}
}

// WithAPIVersion sets the APIVersion field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the APIVersion field is set to the value of the last call.
func (b *PatchSelectorApplyConfiguration) WithAPIVersion(value string) *PatchSelectorApplyConfiguration {
	b.APIVersion = &value
	return b
}

// WithKind sets the Kind field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the Kind field is set to the value of the last call.
func (b *PatchSelectorApplyConfiguration) WithKind(value string) *PatchSelectorApplyConfiguration {
	b.Kind = &value
	return b
}

// WithMatchResources sets the MatchResources field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the MatchResources field is set to the value of the last call.
func (b *PatchSelectorApplyConfiguration) WithMatchResources(value *PatchSelectorMatchApplyConfiguration) *PatchSelectorApplyConfiguration {
	b.MatchResources = value
	return b
}
