// Code generated by controller-gen-v0.21. DO NOT EDIT.

package v1beta2

// StatusUpgradePlanVersionApplyConfiguration represents a declarative configuration of the StatusUpgradePlanVersion type for use
// with apply.
//
// StatusUpgradePlanVersion groups upgrade plan version-related status information.
type StatusUpgradePlanVersionApplyConfiguration struct {
	// version is the Kubernetes version.
	Version *string `json:"version,omitempty"`
}

// StatusUpgradePlanVersionApplyConfiguration constructs a declarative configuration of the StatusUpgradePlanVersion type for use with
// apply.
func StatusUpgradePlanVersion() *StatusUpgradePlanVersionApplyConfiguration {
	return &StatusUpgradePlanVersionApplyConfiguration{}
}

// WithVersion sets the Version field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the Version field is set to the value of the last call.
func (b *StatusUpgradePlanVersionApplyConfiguration) WithVersion(value string) *StatusUpgradePlanVersionApplyConfiguration {
	b.Version = &value
	return b
}
