// Code generated by controller-gen-v0.21. DO NOT EDIT.

package v1beta2

// StatusVersionApplyConfiguration represents a declarative configuration of the StatusVersion type for use
// with apply.
//
// StatusVersion groups version-related status information.
type StatusVersionApplyConfiguration struct {
	// version is the Kubernetes version.
	Version *string `json:"version,omitempty"`
	// replicas is the number of replicas at this version.
	Replicas *int32 `json:"replicas,omitempty"`
}

// StatusVersionApplyConfiguration constructs a declarative configuration of the StatusVersion type for use with
// apply.
func StatusVersion() *StatusVersionApplyConfiguration {
	return &StatusVersionApplyConfiguration{}
}

// WithVersion sets the Version field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the Version field is set to the value of the last call.
func (b *StatusVersionApplyConfiguration) WithVersion(value string) *StatusVersionApplyConfiguration {
	b.Version = &value
	return b
}

// WithReplicas sets the Replicas field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the Replicas field is set to the value of the last call.
func (b *StatusVersionApplyConfiguration) WithReplicas(value int32) *StatusVersionApplyConfiguration {
	b.Replicas = &value
	return b
}
