// Code generated by controller-gen-v0.20.1-0. DO NOT EDIT.

package v1beta2

// TopologyApplyConfiguration represents a declarative configuration of the Topology type for use
// with apply.
//
// Topology encapsulates the information of the managed resources.
type TopologyApplyConfiguration struct {
	// classRef is the ref to the ClusterClass that should be used for the topology.
	ClassRef *ClusterClassRefApplyConfiguration `json:"classRef,omitempty"`
	// version is the Kubernetes version of the cluster.
	Version *string `json:"version,omitempty"`
	// controlPlane describes the cluster control plane.
	ControlPlane *ControlPlaneTopologyApplyConfiguration `json:"controlPlane,omitempty"`
	// workers encapsulates the different constructs that form the worker nodes
	// for the cluster.
	Workers *WorkersTopologyApplyConfiguration `json:"workers,omitempty"`
	// variables can be used to customize the Cluster through
	// patches. They must comply to the corresponding
	// VariableClasses defined in the ClusterClass.
	Variables []ClusterVariableApplyConfiguration `json:"variables,omitempty"`
}

// TopologyApplyConfiguration constructs a declarative configuration of the Topology type for use with
// apply.
func Topology() *TopologyApplyConfiguration {
	return &TopologyApplyConfiguration{}
}

// WithClassRef sets the ClassRef field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the ClassRef field is set to the value of the last call.
func (b *TopologyApplyConfiguration) WithClassRef(value *ClusterClassRefApplyConfiguration) *TopologyApplyConfiguration {
	b.ClassRef = value
	return b
}

// WithVersion sets the Version field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the Version field is set to the value of the last call.
func (b *TopologyApplyConfiguration) WithVersion(value string) *TopologyApplyConfiguration {
	b.Version = &value
	return b
}

// WithControlPlane sets the ControlPlane field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the ControlPlane field is set to the value of the last call.
func (b *TopologyApplyConfiguration) WithControlPlane(value *ControlPlaneTopologyApplyConfiguration) *TopologyApplyConfiguration {
	b.ControlPlane = value
	return b
}

// WithWorkers sets the Workers field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the Workers field is set to the value of the last call.
func (b *TopologyApplyConfiguration) WithWorkers(value *WorkersTopologyApplyConfiguration) *TopologyApplyConfiguration {
	b.Workers = value
	return b
}

// WithVariables adds the given value to the Variables field in the declarative configuration
// and returns the receiver, so that objects can be build by chaining "With" function invocations.
// If called multiple times, values provided by each call will be appended to the Variables field.
func (b *TopologyApplyConfiguration) WithVariables(values ...*ClusterVariableApplyConfiguration) *TopologyApplyConfiguration {
	for i := range values {
		if values[i] == nil {
			panic("nil value passed to WithVariables")
		}
		b.Variables = append(b.Variables, *values[i])
	}
	return b
}
