// Code generated by controller-gen-v0.20.1-0. DO NOT EDIT.

package v1beta2

// VariableSchemaApplyConfiguration represents a declarative configuration of the VariableSchema type for use
// with apply.
//
// VariableSchema defines the schema of a variable.
type VariableSchemaApplyConfiguration struct {
	// openAPIV3Schema defines the schema of a variable via OpenAPI v3
	// schema. The schema is a subset of the schema used in
	// Kubernetes CRDs.
	OpenAPIV3Schema *JSONSchemaPropsApplyConfiguration `json:"openAPIV3Schema,omitempty"`
}

// VariableSchemaApplyConfiguration constructs a declarative configuration of the VariableSchema type for use with
// apply.
func VariableSchema() *VariableSchemaApplyConfiguration {
	return &VariableSchemaApplyConfiguration{}
}

// WithOpenAPIV3Schema sets the OpenAPIV3Schema field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the OpenAPIV3Schema field is set to the value of the last call.
func (b *VariableSchemaApplyConfiguration) WithOpenAPIV3Schema(value *JSONSchemaPropsApplyConfiguration) *VariableSchemaApplyConfiguration {
	b.OpenAPIV3Schema = value
	return b
}
