// Code generated by controller-gen-v0.21. DO NOT EDIT.

package v1beta2

// WorkersStatusApplyConfiguration represents a declarative configuration of the WorkersStatus type for use
// with apply.
//
// WorkersStatus groups all the observations about workers current state.
type WorkersStatusApplyConfiguration struct {
	// desiredReplicas is the total number of desired worker machines in this cluster.
	DesiredReplicas *int32 `json:"desiredReplicas,omitempty"`
	// replicas is the total number of worker machines in this cluster.
	// NOTE: replicas also includes machines still being provisioned or being deleted.
	Replicas *int32 `json:"replicas,omitempty"`
	// upToDateReplicas is the number of up-to-date worker machines in this cluster. A machine is considered up-to-date when Machine's UpToDate condition is true.
	UpToDateReplicas *int32 `json:"upToDateReplicas,omitempty"`
	// readyReplicas is the total number of ready worker machines in this cluster. A machine is considered ready when Machine's Ready condition is true.
	ReadyReplicas *int32 `json:"readyReplicas,omitempty"`
	// availableReplicas is the total number of available worker machines in this cluster. A machine is considered available when Machine's Available condition is true.
	AvailableReplicas *int32 `json:"availableReplicas,omitempty"`
	// versions is the aggregated Kubernetes versions in cluster workers.
	Versions []StatusVersionApplyConfiguration `json:"versions,omitempty"`
	// upgradePlan reports the list of versions that would be applied to the worker objects (all MachineDeployments and MachinePools).
	// Note:
	// - This field is set only when the Cluster topology is managed by Cluster API and a Cluster upgrade is in progress.
	// - Once a version is applied to the worker objects, it is removed from the list (after a version
	// is applied to a worker object, it might take some time for the actual upgrade to complete)
	// - During a chained upgrade, the upgrade plan is continuously re-computed, and this field will
	// report only the last known upgrade plan.
	UpgradePlan []StatusUpgradePlanVersionApplyConfiguration `json:"upgradePlan,omitempty"`
}

// WorkersStatusApplyConfiguration constructs a declarative configuration of the WorkersStatus type for use with
// apply.
func WorkersStatus() *WorkersStatusApplyConfiguration {
	return &WorkersStatusApplyConfiguration{}
}

// WithDesiredReplicas sets the DesiredReplicas field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the DesiredReplicas field is set to the value of the last call.
func (b *WorkersStatusApplyConfiguration) WithDesiredReplicas(value int32) *WorkersStatusApplyConfiguration {
	b.DesiredReplicas = &value
	return b
}

// WithReplicas sets the Replicas field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the Replicas field is set to the value of the last call.
func (b *WorkersStatusApplyConfiguration) WithReplicas(value int32) *WorkersStatusApplyConfiguration {
	b.Replicas = &value
	return b
}

// WithUpToDateReplicas sets the UpToDateReplicas field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the UpToDateReplicas field is set to the value of the last call.
func (b *WorkersStatusApplyConfiguration) WithUpToDateReplicas(value int32) *WorkersStatusApplyConfiguration {
	b.UpToDateReplicas = &value
	return b
}

// WithReadyReplicas sets the ReadyReplicas field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the ReadyReplicas field is set to the value of the last call.
func (b *WorkersStatusApplyConfiguration) WithReadyReplicas(value int32) *WorkersStatusApplyConfiguration {
	b.ReadyReplicas = &value
	return b
}

// WithAvailableReplicas sets the AvailableReplicas field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the AvailableReplicas field is set to the value of the last call.
func (b *WorkersStatusApplyConfiguration) WithAvailableReplicas(value int32) *WorkersStatusApplyConfiguration {
	b.AvailableReplicas = &value
	return b
}

// WithVersions adds the given value to the Versions field in the declarative configuration
// and returns the receiver, so that objects can be build by chaining "With" function invocations.
// If called multiple times, values provided by each call will be appended to the Versions field.
func (b *WorkersStatusApplyConfiguration) WithVersions(values ...*StatusVersionApplyConfiguration) *WorkersStatusApplyConfiguration {
	for i := range values {
		if values[i] == nil {
			panic("nil value passed to WithVersions")
		}
		b.Versions = append(b.Versions, *values[i])
	}
	return b
}

// WithUpgradePlan adds the given value to the UpgradePlan field in the declarative configuration
// and returns the receiver, so that objects can be build by chaining "With" function invocations.
// If called multiple times, values provided by each call will be appended to the UpgradePlan field.
func (b *WorkersStatusApplyConfiguration) WithUpgradePlan(values ...*StatusUpgradePlanVersionApplyConfiguration) *WorkersStatusApplyConfiguration {
	for i := range values {
		if values[i] == nil {
			panic("nil value passed to WithUpgradePlan")
		}
		b.UpgradePlan = append(b.UpgradePlan, *values[i])
	}
	return b
}
