// Code generated by controller-gen-v0.20.1-0. DO NOT EDIT.

package v1beta2

// WorkersTopologyApplyConfiguration represents a declarative configuration of the WorkersTopology type for use
// with apply.
//
// WorkersTopology represents the different sets of worker nodes in the cluster.
type WorkersTopologyApplyConfiguration struct {
	// machineDeployments is a list of machine deployments in the cluster.
	MachineDeployments []MachineDeploymentTopologyApplyConfiguration `json:"machineDeployments,omitempty"`
	// machinePools is a list of machine pools in the cluster.
	MachinePools []MachinePoolTopologyApplyConfiguration `json:"machinePools,omitempty"`
}

// WorkersTopologyApplyConfiguration constructs a declarative configuration of the WorkersTopology type for use with
// apply.
func WorkersTopology() *WorkersTopologyApplyConfiguration {
	return &WorkersTopologyApplyConfiguration{}
}

// WithMachineDeployments adds the given value to the MachineDeployments field in the declarative configuration
// and returns the receiver, so that objects can be build by chaining "With" function invocations.
// If called multiple times, values provided by each call will be appended to the MachineDeployments field.
func (b *WorkersTopologyApplyConfiguration) WithMachineDeployments(values ...*MachineDeploymentTopologyApplyConfiguration) *WorkersTopologyApplyConfiguration {
	for i := range values {
		if values[i] == nil {
			panic("nil value passed to WithMachineDeployments")
		}
		b.MachineDeployments = append(b.MachineDeployments, *values[i])
	}
	return b
}

// WithMachinePools adds the given value to the MachinePools field in the declarative configuration
// and returns the receiver, so that objects can be build by chaining "With" function invocations.
// If called multiple times, values provided by each call will be appended to the MachinePools field.
func (b *WorkersTopologyApplyConfiguration) WithMachinePools(values ...*MachinePoolTopologyApplyConfiguration) *WorkersTopologyApplyConfiguration {
	for i := range values {
		if values[i] == nil {
			panic("nil value passed to WithMachinePools")
		}
		b.MachinePools = append(b.MachinePools, *values[i])
	}
	return b
}
