apiVersion: cluster.x-k8s.io/v1beta1
kind: Cluster
metadata:
  name: "my-cluster"
  namespace: default
  labels:
    cni: "my-cluster-crs-0"
spec:
  clusterNetwork:
    services:
      cidrBlocks: ['10.128.0.0/12']
    pods:
      cidrBlocks: ['192.168.0.0/16']
    serviceDomain: 'cluster.local'
  topology:
    class: "quick-start"
    version: "v1.22.2"
    controlPlane:
      replicas: 1
    variables:
    - name: "subnets4"
      value:
#        subnets1: [ ]
        #- topologyField: value
#        subnets2: [ ]
        #- topologyField: value
#        subnets3: [ ]
        #- topologyField: value
        #  uuid: uuid-1

        # https://cluster-api-aws.sigs.k8s.io/topics/bring-your-own-aws-infrastructure.html?highlight=subnets#placing-ec2-instances-in-specific-subnets
        # Use case 1: bring your own infra (ids are set)
        - topologyField: value1
          id: "uuid-1"
        - topologyField: value2
          id: "uuid-2"

        # Use case 2: create infra (config is set, id isn't)
#        subnets4:
#        - topologyField: value1
#          cidrBlock: "1.2.3.4/24"
#        - topologyField: value2
#          cidrBlock: "1.2.3.5/24"

        # Use case 3: CAPA just creates default subnets
        # => in that case we just don't set the subnets at all
