//go:build !ignore_autogenerated
// +build !ignore_autogenerated

/*
Copyright The Kubernetes Authors.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by controller-gen. DO NOT EDIT.

package v1alpha3

import (
	runtime "k8s.io/apimachinery/pkg/runtime"
)

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *AfterClusterUpgradeRequest) DeepCopyInto(out *AfterClusterUpgradeRequest) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.Cluster.DeepCopyInto(&out.Cluster)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new AfterClusterUpgradeRequest.
func (in *AfterClusterUpgradeRequest) DeepCopy() *AfterClusterUpgradeRequest {
	if in == nil {
		return nil
	}
	out := new(AfterClusterUpgradeRequest)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *AfterClusterUpgradeRequest) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *AfterControlPlaneInitializedRequest) DeepCopyInto(out *AfterControlPlaneInitializedRequest) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.Cluster.DeepCopyInto(&out.Cluster)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new AfterControlPlaneInitializedRequest.
func (in *AfterControlPlaneInitializedRequest) DeepCopy() *AfterControlPlaneInitializedRequest {
	if in == nil {
		return nil
	}
	out := new(AfterControlPlaneInitializedRequest)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *AfterControlPlaneInitializedRequest) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *AfterControlPlaneUpgradeRequest) DeepCopyInto(out *AfterControlPlaneUpgradeRequest) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.Cluster.DeepCopyInto(&out.Cluster)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new AfterControlPlaneUpgradeRequest.
func (in *AfterControlPlaneUpgradeRequest) DeepCopy() *AfterControlPlaneUpgradeRequest {
	if in == nil {
		return nil
	}
	out := new(AfterControlPlaneUpgradeRequest)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *AfterControlPlaneUpgradeRequest) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *BeforeClusterCreateRequest) DeepCopyInto(out *BeforeClusterCreateRequest) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.Cluster.DeepCopyInto(&out.Cluster)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new BeforeClusterCreateRequest.
func (in *BeforeClusterCreateRequest) DeepCopy() *BeforeClusterCreateRequest {
	if in == nil {
		return nil
	}
	out := new(BeforeClusterCreateRequest)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *BeforeClusterCreateRequest) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *BeforeClusterDeleteRequest) DeepCopyInto(out *BeforeClusterDeleteRequest) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.Cluster.DeepCopyInto(&out.Cluster)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new BeforeClusterDeleteRequest.
func (in *BeforeClusterDeleteRequest) DeepCopy() *BeforeClusterDeleteRequest {
	if in == nil {
		return nil
	}
	out := new(BeforeClusterDeleteRequest)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *BeforeClusterDeleteRequest) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *BeforeClusterUpgradeRequest) DeepCopyInto(out *BeforeClusterUpgradeRequest) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.Cluster.DeepCopyInto(&out.Cluster)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new BeforeClusterUpgradeRequest.
func (in *BeforeClusterUpgradeRequest) DeepCopy() *BeforeClusterUpgradeRequest {
	if in == nil {
		return nil
	}
	out := new(BeforeClusterUpgradeRequest)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *BeforeClusterUpgradeRequest) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *BlockingResponse) DeepCopyInto(out *BlockingResponse) {
	*out = *in
	out.TypeMeta = in.TypeMeta
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new BlockingResponse.
func (in *BlockingResponse) DeepCopy() *BlockingResponse {
	if in == nil {
		return nil
	}
	out := new(BlockingResponse)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *BlockingResponse) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *DiscoveryHookRequest) DeepCopyInto(out *DiscoveryHookRequest) {
	*out = *in
	out.TypeMeta = in.TypeMeta
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new DiscoveryHookRequest.
func (in *DiscoveryHookRequest) DeepCopy() *DiscoveryHookRequest {
	if in == nil {
		return nil
	}
	out := new(DiscoveryHookRequest)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *DiscoveryHookRequest) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *DiscoveryHookResponse) DeepCopyInto(out *DiscoveryHookResponse) {
	*out = *in
	out.TypeMeta = in.TypeMeta
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new DiscoveryHookResponse.
func (in *DiscoveryHookResponse) DeepCopy() *DiscoveryHookResponse {
	if in == nil {
		return nil
	}
	out := new(DiscoveryHookResponse)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *DiscoveryHookResponse) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *NonBlockingResponse) DeepCopyInto(out *NonBlockingResponse) {
	*out = *in
	out.TypeMeta = in.TypeMeta
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new NonBlockingResponse.
func (in *NonBlockingResponse) DeepCopy() *NonBlockingResponse {
	if in == nil {
		return nil
	}
	out := new(NonBlockingResponse)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *NonBlockingResponse) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}
