# Add the CR configuration from the config map.
volumeMounts:
 - mountPath: /etc/config
   name: config-volume

volumes:
 - configMap:
     name: kube-state-metrics-crd-config
   name: config-volume

extraArgs:
- "--custom-resource-state-config-file=/etc/config/crd-config.yaml"

rbac:
  extraRules:
  - apiGroups:
    - apiextensions.k8s.io
    resources:
    - customresourcedefinitions
    verbs:
    - get
    - list
    - watch
  - apiGroups:
    - cluster.x-k8s.io
    resources:
    - clusterclasses
    - clusters
    - machinedeployments
    - machinepools
    - machinesets
    - machines
    - machinehealthchecks
    verbs:
    - get
    - list
    - watch
  - apiGroups:
    - controlplane.cluster.x-k8s.io
    resources:
    - kubeadmcontrolplanes
    verbs:
    - get
    - list
    - watch
  - apiGroups:
    - bootstrap.cluster.x-k8s.io
    resources:
    - kubeadmconfigs
    verbs:
    - get
    - list
    - watch
